### ISSUE TITLE
Security: Enabling image inlining by default via markdown is a deanonymization vulnerability

### ISSUE THREAD

**Issue by scotthdsa** [LemmyNet/lemmy#1036]
### Issue Summary

By using markdown image embedding syntax:

```![alt text](url)```

Along with a link that collects IPs, an attacker may harvest IPs that visit the page.

This can be combined with the "auto display" feature of the direct messages, so that an attacker can message a user with an IP grabbing link and immediately get a result back from that user.

The impact is that individual users can trivially have their IPs unmasked.

### Steps to Reproduce

1. host an image somewhere and `tail -f` the weblogs containing image ```https://mysite.com/myimage.jpg```
2. have two browsers open with user A and user B logged in
3. send a message from A to B with content ```![gotcha](https://mysite.com/myimage.jpg)```
4. user B's request for the image, along with IP address and user agent, will show up in the weblogs

### Suggested Remediations

This vulnerability can be addressed with one of the following, in order of most complex to least:

1. Run an image proxy that forwards images and pass any embedded links through it by tweaking the markdown parser
2. Disable linking to external resources using CSP headers
3. Disable inline images in markdown

**Comment by Sosthene-Guedon** [comment]
I suggest another option, which would be to simply to interpret an inline external image in a comment/post as the user not wanting to download the image, and then re-upload it to Lemmy. (That's like 5 clicks, way too much :laughing: )
So Lemmy should do it for the user.

That would mean detecting it in the markdown of the post, downloading the image, and updating the link to the local copy of the image.

Advantages:
- The image is still shown in the Lemmy UI if its origin isn't available anymore
- Moderation is easier since it is the same as with any other post.
 If the images are simply proxied, someone could point an image to a URL they control and change it at will, and serve something weird to a subset of requests (for example 1 in 10) and still be very likely to seem perfectly normal to moderators.

**Comment by Nutomic** [comment]
@Sosthene-Guedon That could potentially be a lot of data which needs to be stored forever. Especially if the same logic is used for federated comments, with imges embedded from the same domain. Proxying seems like a better solution to me.

**Comment by Nutomic** [comment]
A better solution for this issue would be a new API endpoint which allows proxying images through the Lemmy server. Then any remote servers will only see the server IP.

**Comment by ninanator** [comment]
After some investigation, I think maybe adding something like https://github.com/cactus/go-camo may be the best option to resolve this via the proxy route. This is the still-maintained version of the same library that GitHub uses to [solve this same problem](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls) and is [currently recommended by Gitlab for self-hosted instances to solve this issue](https://docs.gitlab.com/ee/security/asset_proxy.html).

Some thoughts:
1. There are [images available](https://github.com/cactus/go-camo#containers), but "untested". Will need to see if these images actually work. If not, is the increase in deployment difficulty manageable for server owners? Is it worth trying to package a binary with the docker files?
2. Easiest way to parse incoming content would probably be to create a new markdown rule that handles creating the new URLs as part of walking through the tree. It looks like the existing parser will allow us to do so without automatically spitting out HTML, just need to double check. Would most likely need to cover endpoints associated with `private_message`, `post`, and `comment`.
3. Create a new preview endpoint for the UI, so that when users preview Markdown it uses the go-camo URL. It looks like GitHub is smart enough to only call the endpoint if images are in the comment. I'm familiar with TypeScript and FE paradigms so I could probably handle that portion as well.

@dessalines @Nutomic Let me know if you think this is worth exploring further. Thanks!
