### ISSUE TITLE
support alttext for images

### ISSUE THREAD

**Issue by r0qstr** [LemmyNet/lemmy#1086]
### Is your proposal related to a problem?

Imagecontent is not accessible for people with impaired eye sight.

### Describe the solution you'd like

Added support to specify an alttext for images one is about to post.

**Comment by dessalines** [comment]
For image posts, I could set the alt-text to the post title. But for images uploaded from comments, or linked from other platforms, there's nothing I could do but have people provide image transcriptions.

**Comment by r0qstr** [comment]
I'd say having people writing the alt text with blind people in mind is better than just taking the post title.
we kind of implemented it in our reddit community (automoderator and stickied comment) and it's got accepted pretty fast and well.

**Comment by dessalines** [comment]
That's a good rule for a community to have, I agree. 

For posts, I can't do alt text for those, because there's no guarantee the links are, or have, images. Links could go to articles, videos, anything. The only option there would be to add a second field, like `link_description`, which I don't really want to do. So I think for image posts, just taking the title, and communities asking to transcribe image posts is the best thing for now.

As far as images in comments, its all markdown, so `![alt-text](link)` works.

**Comment by r0qstr** [comment]
taking the title is no improvement since that is already accessible to screenreaders but does not necessarily describe the picture.
Isn't a conditional field "Alt-Text" possible, based on the fileending/website the the URL is pointing to? reddit uses this for its automod: https://www.reddit.com/wiki/automoderator/standard-conditions#wiki_standard.3A_image_hosting_sites

**Comment by dessalines** [comment]
The only image posts lemmy supports are direct image links, so they don't have any meta-data / description fields.

**Comment by dessalines** [comment]
I'll close this for now, both because there's no guarantee that the post url is an image (it could be anything), and images in comments and post bodies already support alt-text via markdown. Communities that would like to support alt-text, could have a rule to put the alt-text for the image either in the first comment, or the post body.

**Comment by alexture** [comment]
Bumping this accessibility issue.

[With r/blind moving to Lemmy](https://beehaw.org/post/686974), it's probably even more important.

This is not about SEO but about actively describing an image. Per the post above, we can add a caption to an inline image, but not to an image post. I would recommend having a field for alt text for image posts, similar as on Mastodon where you can click "no description" once the photo is uploaded (but not published yet) to add your alt text.

**Comment by ruffsl** [comment]
This was something that was discussed recently from a Programming Humor post, specifically extending the submission process for image posts to include an input field for alt text. Glad to have found this ticket and current discussion. Related;
- https://programming.dev/comment/376841

One thing I was a little concerned about was ensuring user provided alt text is subject to the same level of visibility and public scrutiny as the rest of post details, as when moderating post titles and body texts for accuracy or relevance.
- https://rblind.com/comment/90411

Perhaps it would be wise for image post alt text, provided by the OP, to be similarly shown like an article summery for URL posts?

**Comment by flamingo-cant-draw** [comment]
Couldn't you just check the Content-type of the URL, like what happens when a [thumbnail](https://github.com/LemmyNet/lemmy/blob/3f79eacb53c8a1bb0e23c4bd9037606a7cc58857/crates/api_common/src/request.rs#L125C1-L125C1) is generated, and only allow an `alt_text` field if it has an `image/` type?

**Comment by dessalines** [comment]
True... I don't see any reason not to add an additional optional field here.

**Comment by Nutomic** [comment]
What would be the benefit of a separate alt_text field as opposed to putting it in the post body? Seems like it would be the same in the end.

**Comment by db0** [comment]
It's not the same. The post body might have entirely different content. You can't always flood it with alt-text descriptions and it is also unnecessary for those without accessibility issues to have it always visible like that. Likewise accessibility software won't work correctly with it, as they expect proper use of the alt-text html property.

Alt text must certainly be an option when uploading an image. Embedded images into the post/comments already provide this possibility since it's part of the markdown syntax.

**Comment by Coehill** [comment]
Additionally, having a dedicated alt-text html property will give users the explicit option to add in alt-text and promote its use.  Even using markdown syntax for embedded images in posts/comments is insufficient because users need to a) explicitly choose to add alt text and b) understand what markdown syntax is and how to use it.  

In Mastodon, there is an "Add alt text" textbox whenever you upload an image.  Since it's so obvious and easy, many people use it and now Mastodon is one of the most accessible social media platforms.

The way I see it, Description is a _post_ description whereas alt text is an _image_ description.

**Comment by dessalines** [comment]
> In Mastodon, there is an "Add alt text" textbox whenever you upload an image.

For markdown fields, this one is a UI issue, since markdown does support alt text. You'll need to open issues in the various UIs for adding an alt-text field.
