### ISSUE TITLE
Move api and apub code into separate workspaces

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1115]
To get some better separation between different parts of the code, and possibly speed up compilation time. This is currently tricky, as api, apub and websocket have circular dependencies on each other which need to be removed somehow. My previous, failed attempt is [here](https://yerbamate.dev/LemmyNet/lemmy/pulls/94#issuecomment-1058). The problematic imports can be found like this (using ripgrep, or change to grep):

- `rg websocket:: src/api/`
- `rg apub:: src/api/`
- `rg api:: src/apub/`
- `rg websocket:: src/apub/`
- `rg api:: src/websocket/`
- `rg apub:: src/websocket/`

At the very least, we need to remove some of these imports so that it becomes a [directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph). But ideally we would remove all interdependencies, so that they can be built in parallel.

**Comment by Nutomic** [comment]
Made some progress with this. Here are the remaining imports which are problematic:

- in api: `use crate::apub::{ActorType, ApubLikeableType, ApubObjectType, fetcher::search_by_apub_id};`
- in websocket: `use crate::api::Perform;`

**Comment by dessalines** [comment]
I went over them, and I don't see a way out for them.

> use crate::apub::{ActorType, ApubLikeableType, ApubObjectType, fetcher::search_by_apub_id};

The API needs to be able to call things like `send_create` (which is on ApubObjectType), so that API actions can get federated. This seems unavoidable to me. This is fine anyway since its our main application, using the apub one like a library, like it does everything else.

> use crate::api::Perform;

The websocket isn't **really** separate from the API, its just another network way to do API actions. It'd be like asking how do we separate http routes from the API. 

> in apub: use crate::LemmyContext; (specifically context.chat_server().do_send())

The apub needs to get the running instance of chat_server, otherwise received federated messages wouldn't be able to send websocket notifs to clients. This is kind of a unique case, since its a library (sort of) that needs our running websocket chatserver. But when you look at its functionality, it does need the websocket server passed to it to be able to send those notifs.

I can't think of a good way to get rid of any of these, when you look at what they're doing.

**Comment by Nutomic** [comment]
Fixed in https://yerbamate.dev/LemmyNet/lemmy/pulls/107
