### ISSUE TITLE
Provide appropriate status codes

### ISSUE THREAD

**Issue by shilangyu** [LemmyNet/lemmy#1120]
### Is your proposal related to a problem?

Yes. As an API consumer, I am having a hard time recognizing what when wrong with a request. Currently the only status codes I have encountered are:

- 200: everything went fine
- 400: SOMETHING was wrong with the request (ranges from incorrect parameters to bad auth)
- 500: SOMETHING was wrong on the server side (for example rate limit)

Currently I match the text in the error message to find out what went wrong (as you can imagine, this is very frail and sensitive to minor changes). However even this doesn't always work, [some responses](https://dev.lemmy.ml/api/v1/user) don't return a json at all.

### Describe the solution you'd like

Provide appropriate status codes. I probably don't have to list them, but here are a few as an example:

- 429 for limit rate
- 401 for invalid `auth`
- 403 for a normal user trying to access admin endpoints

### Describe alternatives you've considered

Keep matching error messages and hope it doesn't break?

### Additional context

I'm not very familiar with the codebase but one of the offending code seems to be [this](https://github.com/LemmyNet/lemmy/blob/bd0e69b2bbda8e37190f506e5858cf9c5b2abbfd/server/src/routes/api.rs#L186) (every error is being mapped to a 400). 

I am willing to help with this from the implementation aspect as well as with providing more examples where a more appropriate status code could be used.

**Comment by dessalines** [comment]
I'm not necessarily opposed to this, but what does this add? The point is to present *users* or testers with a readable error message in their language that they can then tell the developers about. HTTP status codes are useless there.

> Currently I match the text in the error message to find out what went wrong

Why are you doing this. If you are building a client of some kind, just translate that message and present it to users in some way, via a toasty or something.

Not to mention websocket, which is far preferred over the HTTP client, wouldn't have these. Both currently return i18n strings, that are all translated and presented to the user.

**Comment by shilangyu** [comment]
This purely benefits developers, and this is what I'm after. In my case, I'm creating a lemmy API client with strongly typed requests, responses, **and errors**. So for example: if I encounter a rate limit I want to throw an appropriate error (let's say `RateLimitException`) so it can be elegantly handled. And like I said, currently the only thing I can do is analyze the error message and translate it to a typed error.

>
> > Currently I match the text in the error message to find out what went wrong
>
> Why are you doing this.

What other choice do I have? A rate limit error message is `Too many requests. type: Message, IP: 123.123.123.123, 180 per 60 seconds.`, so I am forced to `if (errorMessage.contains("Too many requests")) throw RateLimitException();`. Unless I'm missing something obvious, I currently don't see other ways to handle it.

A status code would immediately convey what went wrong. If message string matching is the preferred and expected way to handle errors then fell free to close this issue.

> Not to mention websocket, which is far preferred over the HTTP client

Websockets do not fit my use-case.

**Comment by dessalines** [comment]
Maybe if you showed me your code I could see why forwarding numbers as opposed to string messages is preferred. There are tons of error types, I don't see why numbers for a specific set of types would help you. This could result in a ton of arbitrary groupings of error messages under status codes, unless that is you wanted different exception types for every single error we have.

> Too many requests. type: Message, IP: 123.123.123.123, 180 per 60 seconds.

This is a case of us not correctly using i18n strings, which we should for that error message (its a dynamic one with extra info so its a bit tougher). You can consider the i18n strings for the error messages, the strongly typed keyset of error types. If you want to strongly type errors, rather than just forwarding the strings, then use the i18n strings as keys to switch on.

> if (errorMessage.contains("Too many requests")) throw RateLimitException();

Why do this. just `throw LemmyException(errorMessage)`. Then you've correctly forwarded the error message from the API to whatever is using your API client. I finished a lemmy javascript http and websocket api a few weeks ago, and just forward these string messages as errors.

> A status code would immediately convey what went wrong.

Sentences work better than numbers at telling you what's going wrong.

**Comment by shilangyu** [comment]
> You can consider the i18n strings for the error messages, the strongly typed keyset of error types. If you want to strongly type errors, rather than just forwarding the strings, then use the i18n strings as keys to switch on.

I think I'm missing something crucial here, are those i18n strings something standard? Or listed somewhere? If they are consistently returned then this is a misunderstanding on my part, sorry. This would solve the issue that I am facing.

**Comment by dessalines** [comment]
They are listed in the [en.json transalations](https://github.com/LemmyNet/lemmy/blob/main/ui/translations/en.json#L246), but to get a full list of them, run `rg "APIError:err\(" server/src/api`
