### ISSUE TITLE
auto import from reddit

### ISSUE THREAD

**Issue by ralyodio** [LemmyNet/lemmy#119]
would be cool do seed an instance of Lemmy with reddit sub's rss feed.

**Comment by pojntfx** [comment]
I totally agree. This would also make people switch to Lemmy way more quickly.

**Comment by dessalines** [comment]
Ya I agree, I've written reddit importers before. This would be something that, once I get the API #99 up, then it would be very easy to import posts and comments. This will probably take a backseat to federation unless someone else wants to add it.

**Comment by dessalines** [comment]
This is a priority now because I'm realizing that as lemmy picks up steam, having a reddit import bot will help add some content for ppl to discuss.

**Comment by Nutomic** [comment]
Is it really necessary to add this as a feature directly in Lemmy? That might encourage a lot of crossposting spam. Wouldnt it be better to write an external bot that does the crossposting?

**Comment by dessalines** [comment]
Ya, a bot / script would be super easy to write. There's so many ways to do this too,and questions, like 

- should it work only for single posts, or should it be a backup of an entire subreddit?
- What about comments? (Probably 80% of good content is comments, not posts). Should it pull all comments and put them as the importers username?
- Should it be a script, or wired into lemmy so that when you paste a reddit post into the URL, a button pops up to `import` from reddit. Same question for community imports.

And the spam this might bring is definitely a concern.

**Comment by Nutomic** [comment]
Someone on lemmygrad wrote a script for this.
