### ISSUE TITLE
Discussion of pros, cons, and implementation of the slur system

### ISSUE THREAD

**Issue by Lambdanaut** [LemmyNet/lemmy#1224]
So what's the rub?
-------------------

At the moment there is a static slur regex that blanket-captures all uses of specifically chosen words:

* https://github.com/LemmyNet/lemmy/blob/main/lemmy_utils/src/utils.rs#L10

There is definitely well-intentioned reasoning behind this addition. One potential benefit is that it may keep discussions more civil and baseline across all Lemmy instances. This is something that has been commented on, and although it's hard to say how much of the civility of Lemmy is due to a slur filter, it must be a factor.
Another potential is that a slur filter could allow marginalized individuals to feel safer by reducing the possibility of seeing a trigger word. 

On the other hand, there are potential drawbacks and harm an implementation like this could bring. Many individuals feel strongly about identifying with these words. It could potentially further marginalize individuals that identify with certain slurs, such as `N***r`, `F**got`, `Sl*t`, etc. A slur filter sadly excludes a large number of those the filter is meant to protect. It also kills any discussion of the etymology of these words. For instance, `C*nt` has been used for centuries in a completely non-obscene manner. Romantically, even. The etymology isn't able to be discussed with the filter in place, and at best discussion of the roots and culture of these words would be highly discouraged. Assuming Lemmy wishes to become big, this can have a drastic negative disconnect between us and our understanding of these words and how they have grown to be what they are in society. If we don't understand the past, we are doomed to repeat it. 

One of the greatest aspects of the fediverse is that each instance can define their own rules and other instances can decide whether to federate based on that. A static, hard-coded slur filter steps in-between this and creates an unnecessary barrier-of-entry that keeps instances from being able to decide their own rules. Instead it enforces an Anglophone list of bad-words that every instance must obey unless the admins are skilled enough to create a fork. This rule is centralized and controlled by the software developers rather than the instance admins, taking control out of the fediverse and into centralized hands. 

This is not to say that a slur filter isn't a great feature with lots of potential benefit to discussion, however it's clear that a centralized, statically defined, Anglophone, regex expression is not the best way it can be done. 

So what options do we have?
-----------------------------

@orthecreedence created this PR in June with a potential option: 

* https://github.com/LemmyNet/lemmy/pull/816#issuecomment-644694838

I think something like that is in the right direction, though at the moment it's been closed by the primary code authors as being too liberal a solution. 

Given that, it leaves me scratching my head as to what solutions we can propose. So I'd like to start by asking the primary code maintainers: 

* What goals are we trying to accomplish with a slur filter?
* How can we design the slur filter to best avoid the marginalizing effects while still accomplishing these goals?

**Comment by orthecreedence** [comment]
Thanks for opening the discussion. I'd like to mention that this particular issue is a blocker for me not just using Lemmy, but contributing to it as well. As it is, I can't personally support a system that claims decentralized operation but then centralizes something like what words can or cannot be uttered. This, to me, is something that is extremely community-specific. A community of car mechanics will surely use the shorthand "tranny" to mean "transmission." A group of black people might *want* to say the n-word in their discussions of the history of the word, or even use it in casual conversation. 

It seems to me the slur filter takes a very one-sided approach to the problem by imagining the *worst case* for a particular word's usage and banning it outright for everyone *based on that (mis)conception.* Words don't always have universal meanings, but quite often *contextual* meaning that the overall system (Lemmy) itself cannot determine. So why not follow Lemmy's mantra of decentralization and allow communities to make this decision for themselves?

I think the stated opposition to the feature doesn't achieve its goal: you cannot in any way bar a right-winger from using a decentralized system. That's the point of a decentralized system! If right wingers want to use the system, they should be free too...and if you don't like their use of words or ideas, you can choose not to associate with their instance. This is already built into the ActivityPub protocol. On top of this, any right winger could fork Lemmy, apply my PR, and federate with the rest of the Lemmy environment almost as easily as someone can run Lemmy straight from the canned Docker instance. In other words, the feature censors most users of the system in order to ward off groups of people that can easily sidestep the feature.

Language usage and moderation is, at its core, a function of communities and the context of those communities. I believe if the creators of Lemmy truly want a decentralized system, they need to release control of any centralized aspects of the project (like the slur filter) and allow the communities using it to decide for themselves how they want their particular instances used.

*A tool for open and decentralized communication cannot have censorship built in at the highest level*.

**Comment by dessalines** [comment]
You're correct that we do want lemmy to be welcoming for all; no one should feel worried about being demeaned for their ethnicity or sexuality as is the case on so many other platforms. We value this as much as if not more than decentralization.

But the overall *existence* of a slur filter is not up for debate: there will always be one, as anti-bigotry is one of our main values outlined in the [Code of Conduct](https://github.com/LemmyNet/lemmy/blob/master/CODE_OF_CONDUCT.md). 

What is, and will always be up for discussion, is adding / removing / altering *specific* slurs in the filter. So far **we've gotten zero PRs / issues** about either correcting false positives in the slur regex, or discussion around specific slurs.

If someone wants to make a bigot-friendly fork of lemmy, there's not much we can do about that unfortunately, but its on them to maintain it, we're not going to help them out. They can either join existing bigoted platforms like voat or gab, or build their own.

> What goals are we trying to accomplish with a slur filter?

Keeping out bigots, we've been very explicit about that.

> How can we design the slur filter to best avoid the marginalizing effects while still accomplishing these goals?

I disagree with your idea that slurs are "okay" as long as a member of the targeted group says so. These are public communities, openly available for all to see, on the internet, where anyone can claim to be of any group. Bigots love the Milo Yiannopoulos's of the world who give them permission to be racist / transphobic / homophobic ; take a look at the subreddit https://www.reddit.com/r/AsABlackMan/ if you want to see examples of people who either are, or claim to be members of a group, giving sanction to others to be racist / bigoted against "their" group. 

> In other words, the feature censors most users of the system in order to ward off groups of people that can easily sidestep the feature.

Nothing would make me happier than to drive bigots away from lemmy to other platforms. I'd encourage you to contribute to these bigoted alternatives if the main blocker to joining this project is that we replace slurs with *removed*. 

I'm closing this one as we've made our stance on this clear many times, but if you have specific slurs you think should be removed / added, you're free to open other issues.
