### ISSUE TITLE
Lemmy doesnt run / build / compile on Rust 1.48 and nightly

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1270]
Due to a problem in the [config-rs crate](https://github.com/mehcode/config-rs/issues/158)

**Comment by Nutomic** [comment]
I have disabled our integration tests, as they are failing due to the crash in `config-rs`. We need to enable them again once that is fixed.

https://github.com/LemmyNet/lemmy/commit/841ad8476cf2f4a63204ff85bba56b4785962acd#diff-7ff815b68943f08bef79f083c09e55ca8c18db8e25033034b12fa31f1d43dab4

**Comment by dessalines** [comment]
Based on @canop 's recommendations [here](https://github.com/Canop/deser-hjson/issues/2), and because ~4 libraries are abandoned (`config-rs`, `serde-yaml`, `hjson-rust (serde-hjson)`, `linked-hash-map`), and I think our best bet is to :

- Remove `config-rs` entirely.
- Use @canop 's `deser-hjson` library, which should be straightforward since we have a well-typed config anyway.
- Use this [rust merge](https://docs.rs/merge/0.1.0/merge/) library, in order to merge our default and custom config
- Then the only thing we're missing is environment variables, which we *could* do away with entirely.

**Comment by Nutomic** [comment]
This is fixed now, Lemmy runs on Rust 1.50 and nightly :)

**Comment by dessalines** [comment]
Yaaaaaaay.
