### ISSUE TITLE
Error with Docker setup

### ISSUE THREAD

**Issue by mstdn** [LemmyNet/lemmy#1505]
### Issue Summary

Hello all! I am again installing Lemmy via Docket on 18.04. I use the latest release and following the install guide nicely. When I run the Docker-compose command I get the following error:

Pulling lemmy (dessalines/lemmy:0.10.0-rc.7)...
0.10.0-rc.7: Pulling from dessalines/lemmy
ERROR: no matching manifest for linux/amd64 in the manifest list entries

### Steps to Reproduce

Follow Docker guide and compose for the first time.

### Technical details

* LOG: Attaching to
* 18.04 
* Not yet

**Comment by dessalines** [comment]
One issue is our bad, that is a release candidate that probably shouldn't be used in production. The correct versions for both lemmy and lemmy-ui is `0.9.9` . @Nutomic I have to edit the `deploy.sh` so that RC releases don't overwrite those docker files.

But I also do need a log to figure out the error.

**Comment by Nutomic** [comment]
@mstdn Please close your issue after it is resolved.

https://mstdn.social/@stux/105919096814606543
