### ISSUE TITLE
Restrictions for new users

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1579]
The majority of problematic actions on lemmy.ml which require moderation are made by new users. This includes spam, but also trolling and harassment. So I propose to add a new instance setting which would limit the actions of new users, something along these lines:

| Action              | Requirements            |
|---------------------|-------------------------|
| Vote                | none                    |
| Create comment      | 5 votes made  |
| Create post         | 5 comments created |
| Send private message| 1 post created          |
| Create community    | 5 posts created         |

Only posts/comments with positive vote count would count towards these requirements. So if a new user makes 5 comments but each of them has a negative score, then they still cant create any post (only once they make 5 comments with positive vote count). Each post/comment needs to have at least 5 votes received, to make sure that multiple users read it.

All the numbers here are preliminary, for now they serve mainly to explain the idea. They can be changed later, and it should be possible for instance admins to configure them. Eg simply by adding config options for requirements for each user action. Or even with a Lua script which returns allowed/not allowed for each user based on their post/comment history and can be edited by the admin (this is probably overkill).

**Comment by dessalines** [comment]
In light of new spam attacks, I do think something like this would be effective.

**Comment by gaywallet** [comment]
Some thoughts on this: 

1. If we lock commenting behind voting, people will learn and simply spam votes in order to comment, easily subverting the purpose of this. 
2. Posts and comments should be weighed equally - restricting a DM to a single post or comment would be more equitable towards how people interact with a website and discourage people from just creating a random talk post with nonsense to be able to DM. 
3. While people often do not like time-restrictions such as cannot post/comment for 24-72 hours after account creation, it works very well at stopping the behavior that is often triggered by someone seeing something they don't like, and creating an account to spam hate speech on the post/comment they do not like. 
4. Having tools which allow each instance to hold comments for manual approval for new users (under a certain amount of actions or within a certain timeframe) is an effective way to accomplish the same, and allowing instances to turn this on or off based on their needs allows people to moderate in a way that is effective for _their_ community. 
5. I don't think it's necessary at this time, but more advanced tools such as paying attention to the IP addresses and timing of when accounts are created and looking for anomalies such as a bunch of accounts being created at the same IP address or being created within a short time frame (unusual account creation behavior) to be surfaced to some kind of log for moderators can also be useful. Parts of this can be certainly subverted (cycling VPNs to create new accounts) but it works fairly well at scale on most current websites.

**Comment by Nutomic** [comment]
> Having tools which allow each instance to hold comments for manual approval for new users (under a certain amount of actions or within a certain timeframe) is an effective way to accomplish the same, and allowing instances to turn this on or off based on their needs allows people to moderate in a way that is effective for their community.

I think this would be very effective, and could be a good alternative to registration applications in some cases. 

> I don't think it's necessary at this time, but more advanced tools such as paying attention to the IP addresses and timing of when accounts are created and looking for anomalies such as a bunch of accounts being created at the same IP address or being created within a short time frame (unusual account creation behavior) to be surfaced to some kind of log for moderators can also be useful. Parts of this can be certainly subverted (cycling VPNs to create new accounts) but it works fairly well at scale on most current websites.

Referrers might also be a useful indicator, in case the instance link got posted somewhere.

**Comment by dessalines** [comment]
Fortunately the registration applications have pretty much put a stop to spam (apart from federating with servers that still don't have that turned on).

**Comment by Nutomic** [comment]
Described this in more detail and easier to implement in https://github.com/LemmyNet/lemmy/issues/2601
