### ISSUE TITLE
redirect youtube videos to invidius

### ISSUE THREAD

**Issue by J0hsHH** [LemmyNet/lemmy#1591]
nitter.net has support for it in settings
https://github.com/iv-org/invidious

**Comment by dessalines** [comment]
Thats discussed in some threads like this one: https://lemmy.ml/post/61041

For the record, im against the back end overwriting links, I think a link aggregator should mostly be unopinionated / agnostic about the types of links posted.

Also I think browser plugins are better suited to this, since these alternative YouTube and twitter front ends go down constantly.

**Comment by J0hsHH** [comment]
ok

**Comment by qazip** [comment]
I agree with @dessalines. Please, don't do this. This kind of thing would fight against seeing Lemmy becoming massively used by everyone.

Just use an extension like he recommended. That way you'll see that behaviour everywhere and not just a few sites.
