### ISSUE TITLE
ActivityPub compliance issues in actors

### ISSUE THREAD

**Issue by grishka** [LemmyNet/lemmy#1609]
A quick list of what I noticed about Lemmy's user actors.

- There are no `followers` and `following` collections. [The spec](https://www.w3.org/TR/activitypub/#actor-objects) says that these "should" be provided. Some implementations (Mastodon probably?) require them.
- There is `matrixUserId` but no corresponding declaration in `@context`.

**Comment by Nutomic** [comment]
> There are no followers and following collections. The spec says that these "should" be provided. Some implementations (Mastodon probably?) require them.

We dont want to make followers/following users public for privacy reasons (and its also not public on Reddit). We could serve empty collections like we do for the user outbox, but that would indicate that we support this funcionality when we actually dont. I think its better to not have the endpoints at all, so that other software can cleanly handle this and hide the followers list for Lemmy actors.

> There is matrixUserId but no corresponding declaration in @context.

This is fixed [in the code](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/extensions/context.rs#L21) but not released yet. Though it is always possible that there is something wrong with our context, because I still dont really understand how it works (and we never actually parse it from other instances).

**Comment by Nutomic** [comment]
Gonna close this, please comment or make a new issue if you notice any more incompatibilities.

**Comment by grishka** [comment]
(just so you know — Lemmy actors are now compatible with Smithereen)
![image](https://user-images.githubusercontent.com/1478258/126296576-dd467383-d8d5-4e3c-98d7-a43fa6b35a59.png)
![image](https://user-images.githubusercontent.com/1478258/126296799-5b91c7b4-00a1-41ee-9f1e-eb1bb65c8526.png)

**Comment by dessalines** [comment]
Sweet!
