### ISSUE TITLE
Activitypub post history fetching is currently broken.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1621]
When I subscribe to a new federated community via the search box, it no longer pulls some older posts.

**Comment by Nutomic** [comment]
The problem is [here](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/fetcher/community.rs#L161), and was introduced when I split the apub code in two crates (apub and apub_receive). That function essentially depends on the entire code of apub_receive, and because circular dependencies are not allowed, I only see two options to solve it:

- merge apub and apub_receive into one crate again (slows compilation, code organization will be worse)
- pass a reference to the receive_announce function into fetch_community_outbox, like we do [here](https://github.com/LemmyNet/lemmy/blob/main/src/main.rs#L73) (problem is that we might have to pass this function in a lot of different places)

**Comment by dessalines** [comment]
I vote for option 1. The compile time improvements are a nice to have, but its all relative anyway, and I'd rather not sacrifice code clarity by doing metaprogramming workarounds. And you can still organize them into separate folders, they'd just be in the same crate. But if it turns out that `#2` is easier and still readable, that's fine too.
