### ISSUE TITLE
Uploading images anywhere on the instance gives an error.

### ISSUE THREAD

**Issue by YaBoiMason** [LemmyNet/lemmy#1645]
Hi, I'm trying to upload an icon for the image and banner for my site, but when I do, this error comes up in the bottom left, in a small red toast notification:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
It also happens when I try to upload an image for a post.
All that appears in the browser console is this:
```
DEPRECATION NOTICE: "backgroundColor" is being deprecated. Please use the "style.background" property.
```

**Comment by weex** [comment]
What version of lemmy are you running and what kind of image? The inspector in your browser may help also to see what JSON is actually being sent to the server but version is first thing to check since it could be an old bug that's been fixed. I was just able to upload a jpeg to lemmy.ml without issue.

**Comment by YaBoiMason** [comment]
I forgot to close the issue, but it just strangely fixed itself out of nowhere.
