### ISSUE TITLE
Consider renaming "blocks" to muting or hiding

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1832]
On Mastodon, when user A blocks user B, it means that B cant see any posts from A. There is also muting, which means that A wont see posts from B (but B can still see posts from A).

What we have in Lemmy is essentially the same as muting in Mastodon, so using the term blocking could be very misleading. For this reason we should consider changing the name.

**Comment by dessalines** [comment]
Reddit has no distinction between the two, only blocks, which I think are similar to mutes. 

I personally don't like the two-way blocking because that gives one user power over what another user sees, rather than controlling what they themselves see. If you block a user, you don't want to receive abuse from them, or see their posts or comments. Blocking their side changes nothing about what you see, and gives you control over the content they see.

Also in reddit, imagine a post with hundreds of comments, a blocked user might still want to interact with that post. If two-way blocking were implemented, they wouldn't even see it.

**Comment by MaximilianKohler** [comment]
FYI, reddit implemented "true block" in recent years. Blocking users now prevents them from seeing or interacting with your content.

There are pros and cons. It can be nice to block certain toxic users but it's easy to abuse as well.

**Comment by DraconicNEO** [comment]
> FYI, reddit implemented "true block" in recent years. Blocking users now prevents them from seeing or interacting with your content.
> 
> There are pros and cons. It can be nice to block certain toxic users but it's easy to abuse as well.

I think that a true Block shouldn't hide your content from them, since that doesn't make sense on a public platform. It's main and only merit is functioning as a form of soft-ban or lockout against targeting you or your posts.
Ultimately as easy as it is to abuse it has ended up being more useful in my opinion since it stops people who would otherwise keep going without having to wait for moderation.
