### ISSUE TITLE
Card is garbled.

### ISSUE THREAD

**Issue by karasugawasu** [LemmyNet/lemmy#1858]
### Issue Summary
The card may be garbled in some URL.

This is what it looks like on my site.
https://lm.korako.me/post/4701

This did not happen before v0.12.2 at least.

### Steps to Reproduce

1. Create New Post
2. Set URL & Create (ex: https://pangya.mygame.in.th/movement/activity_view.asp?id=MjAyMTEwMTgwOTIzMTA
3. When I check the card, it is garbled.

### Technical details

* What OS are you trying to install lemmy on? 
　Ubuntu 20.10
* Any browser console errors?
  Nothing

※Sorry for my poor English, this text was created at DeepL ...m(_ _)m

**Comment by rgroothuijsen** [comment]
This appears to be a problem with [converting the HTML metadata to text](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/request.rs#L69). It expects UTF-8 by default, but the site metadata specifies "windows-874" encoding instead. Since the encoding can't be known in advance, the text would have to re-encoded after fetching the site.
