### ISSUE TITLE
Only top-mod can appoint new mods in community

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy#1890]
### Is your proposal related to a problem?

At the moment, any community moderator can promote new moderators, however, I believe it is a problem.
I may want to get someone to help me moderate a community, but not want to give them the administrative power of adding more people to the team.
It can be rather risky and while you can certainly just keep a close eye on your mods, I'd rather have a way to prevent possible mishaps than letting them pass and having to clean them afterwards.

### Describe the solution you'd like

I suggest only the top mod (oldest one; aka community admin since that attribute got nuked in #1541) has such administrative powers.

### Describe alternatives you've considered

I haven't considered any other alternatives, but I'd like to discuss this further.

### Additional context

[Matrix conversation](https://matrix.to/#/!BZVTUuEiNmRcbFeLeI:matrix.org/$163646840018MRpvN:cyberia.club)

**Comment by dessalines** [comment]
This behavior is taken from reddit, and I don't know that its a good idea to prevent mods from appointing new ones below them: tons of subs have absent top moderators, or even a few top mods that are absent. By only letting the top moderator add new ones, you effectively kill a community as soon as they go missing.

Its also kind of a non issue, because higher up moderators can remove lower ones, so if a rogue mod started appointing a bunch without discussion, they and all the lower ones can easily be removed.

Of course lemmy does let admins transfer communities if any mod does go absent and the community is stuck, but I imagine on some large instances this wouldn't be preferred.

**Comment by grace3359020** [comment]
How to make money
Good news, domili scooter provides link sharing, and you can get 5% commission for all customers who you share to buy products
For details, please contact: domili@163.com
URL: domili.top
