### ISSUE TITLE
Incomplete list of "Linked Instances"

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#1928]
Is it possible, that the open federation method of Lemmy blocks adding Mastodon/Pleroma instances to the "Linked Instances" list on the instances page? On lemmy.ml as well as fapsi.be the Mastodon/Pleroma instances aren't shown there, but on lemmy.pt they do.  
The only difference between lemmy.pt and lemmy.ml​/​fapsi.be is, that .pt is using the whitelist system without strict whitelisting. I saw same issue with feddit.de, which is using strict whitelisting.

**Comment by dessalines** [comment]
Right now to build that `linked_instances` list, we're using lemmy's connected federated communities. It then appends the allowlisted instances.

https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/lib.rs#L239

We should probably find another way to do this.

It should probably also be separated into its own endpoint, rather than served with `GetSite`, but I'll make another issue for that.

**Comment by Nutomic** [comment]
@dessalines The current approach works fine, problem is that it only takes the domains from federated communities (which Mastodon/Pleroma dont have). So it would be enough to repeat the same logic for users as well.

**Comment by dessalines** [comment]
It wouldn't be ideal performance-wise IMO, because every user has a distinct `actor_id`. IE the query iis : 

```
explain analyze select distinct actor_id from person;
 HashAggregate  (cost=2358.22..2512.80 rows=15458 width=29) (actual time=26.452..32.096 rows=15490 loops=1)
   Group Key: actor_id
   ->  Seq Scan on person  (cost=0.00..2319.58 rows=15458 width=29) (actual time=0.016..10.723 rows=15490 loops=1)
 Planning Time: 0.148 ms
 Execution Time: 34.639 ms
(5 rows)
```

35 ms wouldn't be *too bad* if fetching the instances were extracted into its own endpoint, but that number is only going to get worse with more users. 

The community numbers are so small that it's neglible, which is why we haven't noticed a performance problem there:

```
lemmy=# explain analyze select distinct actor_id from community;
                                                                      QUERY PLAN                                                                 
------------------------------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=0.28..413.13 rows=2563 width=29) (actual time=0.087..1.727 rows=2563 loops=1)
   ->  Index Only Scan using idx_community_actor_id on community  (cost=0.28..406.72 rows=2563 width=29) (actual time=0.084..1.041 rows=2563 loops=1)
         Heap Fetches: 271
 Planning Time: 5.136 ms
 Execution Time: 1.897 ms
(5 rows)
```

**Comment by dessalines** [comment]
As mentioned in https://github.com/LemmyNet/lemmy-ui/issues/720 , if we added an instance table, and instance_id columns to the person and community tables, we'd be able to filter by instance, and have a way to view only posts or communities from specific instances in the front ends.
