### ISSUE TITLE
Federate masto favorites or likes into lemmy votes?

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1968]
This is more of a question for @Nutomic  than a request. 

I'm guessing that masto favorites or pleroma likes, send an apub _like_, but not a _create like_ as lemmy does. Maybe we could double send this activity like we do with comment creates, to see if we could federate likes.

**Comment by Nutomic** [comment]
Mastodon does send likes, but they are marked as private, and rejected by Lemmy (which requires likes to be public). This is because Lemmy sends them to other instances that follow the community. We could ignore the privacy but that doesnt seem nice. 

We could send Likes in a format that Mastodon understands, but someone needs to reverse engineer the Mastodon activities (i dont have any motivation to do that). And it might not make much sense because the meaning of like is different in both projects.

It would also be possible to receive likes from Mastodon if we ignore the privacy (after all its not exposed through the api), but it seems problematic if some users can only upvote but not downvote.

**Comment by dessalines** [comment]
Ah... seems not really worth it then. I wonder if pleroma also marks them as private.

**Comment by UserThre3** [comment]
@Nutomic @dessalines 

I'm on Mastodon and would happily have the "like" button work as an upvote, no downvote needed. It's two different formats, I always believe in the lowest common denominator.

I also think the privacy thing for Mastodon likes is more for technical reasons rather than direct privacy. I don't have an expectation that my likes will be hidden on a public post on Mastodon, in fact; they're publicly visible. If anything I'd expect my vote/like to be more anonymous with Lemmy's upvote system.

It would also be nice to see upvotes as likes on Mastodon, but I completely understand that all of this has a low to none-level of priority.

**Comment by Nutomic** [comment]
Fixed in https://github.com/LemmyNet/lemmy/pull/2301
