### ISSUE TITLE
Limit downvotes by new users

### ISSUE THREAD

**Issue by dayinjing** [LemmyNet/lemmy#1981]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

I see some people like to create a new account just to downvote everything

### Describe the solution you'd like

Limit downvotes for new users or users with a karma threshold

### Describe alternatives you've considered

Making a user wait to vote on post until their account is of a certain age. That should also work

### Additional context

n/a

**Comment by dessalines** [comment]
We're working on options to require email verification, and a registration application for new accounts, so that should alleviate some of this.

I'm overall hesitant to add complicated levels of restrictions for new users, unless its very well thought out. Trying to avoid the stack-overflowification / power user affect that these usually end up leading to.
