### ISSUE TITLE
Implement per community downvote restriction

### ISSUE THREAD

**Issue by dayinjing** [LemmyNet/lemmy#2011]
### Is your proposal related to a problem?

Some communities would like downvotes while others may not. Currently a admin user can disable downvotes site wide; however a moderator of a community does not have the fine tune control to disable downvotes for their specific community.

This becomes especially troubling when someone enables federation for a community on a server where nobody likes the content but the one person who enabled it. 

### Describe the solution you'd like

Allow admins, moderators to disable downvotes for a community when site wide downvotes are enabled

### Describe alternatives you've considered

Give a admin/mod the ability to disable downvotes from foreign instance on their home instance while allowing them to show up on the foreign instance.

**Comment by dessalines** [comment]
The main issue here is brigades from other instances, and that doesn't only take the form of downvoting; it also can be creating comments, posts, upvoting certain comments / posts while downvoting others, etc.

To me only disabling downvotes doesn't really fix the root issue or its wider problems. The only real way to stop brigades from unfriendly instances, is to block those instances.

**Comment by dayinjing** [comment]
> The main issue here is brigades from other instances, and that doesn't only take the form of downvoting; it also can be creating comments, posts, upvoting certain comments / posts while downvoting others, etc.
> 
> To me only disabling downvotes doesn't really fix the root issue or its wider problems. The only real way to stop brigades from unfriendly instances, is to block those instances.
> 
> edit: I wouldn't necessarily be opposed if someone coded this, but they should know that its only fixing one of many symptoms of a larger problem.

These are great points but as instances grow larger it will get harder and harder to make that argument. Larger instances who post about another instance post will make it appear like brigading. 

I think fine tune control of how other instances effect each other will make federation a over all better experience. 

Maybe make this a epic. Allow instances to disable down votes from other instances, disable comments or post or both ect..

**Comment by UnderwhelmedExplorer** [comment]
I strongly agree with @webbongithub. To add, harassing downvotes (such as downvotes due to brigading users or users who downvote a community’s posts instead of blocking the community) can’t be removed by mods, unlike harassing posts or comments. I like the idea of allow/blocklisting downvotes on the instance level that was proposed in #4086, but this won’t help if harassing downvotes are coming from within the community’s instance or from another instance where downvotes are allowed. Certain communities might prefer to disable downvotes altogether if they’re concerned about harassing downvotes ruining their community. Although mods of these communities could create a new instance with downvotes disabled, they might not have the expertise, money, or capacity to do this.
