### ISSUE TITLE
A easier way to change the hostname

### ISSUE THREAD

**Issue by gnh1201** [LemmyNet/lemmy#2018]
### Is your proposal related to a problem?

After deploying Lemmy, I tried to change my hostname, but it failed. The hostname does not change just by modifying `lemmy.hjson`.

This is necessary for solving the problem (A) in which thumbnails are not created and the problem (B) in which communities cannot be found after changing hostname.

   * Example of (A): Couldn't change `my_domain` to my own domain

```
https://my_domain/pictrs/image/50a29df9-fe2b-4cb7-8140-1e138c326e0f.png?format=webp&thumbnail=256`
```

   * Example of (B): If I modify the hostname of `lemmy.hjson`, there is a problem that I cannot find a community.

```
{error: 'couldnt_find_community'}
```

### Describe the solution you'd like

I need a easier way to change the hostname

### Describe alternatives you've considered

For now, I think I need to manually modify my hostname by accessing postrgre.

**Comment by Nutomic** [comment]
Changing the hostname after installation is not supported, because it would require changing all actor_ids and other fields on all federated instances. In theory it would be possible to send a federate message like "instance domain changed from X to Y, please rewrite everything". But that would be a lot of effort, and would probably create security problems (someone could hack an instance and move it to their own domain). So I consider this issue out of scope and would close it, along with your two related issues.

If you want to change domains, you should either reinstall, or fix things in the database manually.

**Comment by gnh1201** [comment]
Ok. Please let me know which field to change. I don't think we should just change the actor_id.

**Comment by gnh1201** [comment]
I succeeded in migrating to the changed hostname.

First, I gave up the transfer of user data. Because there was no way to recreate it. Then I recreated the communities through the UI.

After that, I proceeded with the migration of the post and post aggs tables.

**Comment by dessalines** [comment]
Agree with @Nutomic here, I don't think we want to support changing the hostname.
