### ISSUE TITLE
Sitemods

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2071]
Sitemods are privledged users that can remove comments/posts etc across the instance, but don’t have access to site configuration like admins do.

![](https://www.hexbear.net/pictrs/image/AxvqDQkKz4.png)

![](https://www.hexbear.net/pictrs/image/V0ILtegqql.png)

**Comment by dessalines** [comment]
Also if the sole purpose of this is to just not allow instance config changes, I'd be totally find with removing that, as it doesn't really work right now anyway. Then we could avoid all this extra complication of adding types and layers of admins.

**Comment by not-layla** [comment]
@dessalines It's not just for changes to the configuration file, it's for anything under `/admin`.

@Nutomic The point is instance owners can get help with site-wide moderation without having to trust them with access to `/admin`. I suppose voting *could* solve this issue but (a) it still means making new admins have equal power as old admins, and (b) democratic moderation is still a very very long way away I'm guessing.

**Comment by dessalines** [comment]
We should probably re-organize these all under the `/admin` route, but the current admin API actions are:

- Dealing with registrations
- Adding other admins
- Banning users
- Transferring communities
- Removing communities
- Removing user content ( doesn't DB delete anything )
- Getting and saving the site config
- Transferring the site (only available to the top admin, so not applicable)

Before creating complicated layers of admins, we need to discuss which of those actions if any need to be restricted in some way to a subset of admins. A note that **none of those actions** can actually delete anything in the database, and the only one that has the potential to bork the site, is saving site config.

IMO rather than creating a separate type of admin, we should mark out the ones that maybe only the top admin should be able to do. The only one I see there, is saving the site config, and *maybe* removing communities.

**Comment by TheCoolZone** [comment]
The distinction between moderators and admins is a decades old concept, so I'm not really seeing why the idea is contentious? Attaching examples of phpBB configs that have been around since at least the early 2000s. The granularity is there because there are time when admins trust a global moderator just enough to manage individual users or support comm moderators but don't trust them with management of comms themselves.

IMO, part of this has to do with user perception of moderation activities. If bad mods are promoted to too high of a level too early and need to have a bunch of their decisions reversed, then it immediately lowers user trust in site moderation generally. This is something I've personally witnessed on other sites and is just a realistic potential outcome of things regardless of design ideology.

![845_116_s_g_Forum_Users_Permissionsne68i](https://user-images.githubusercontent.com/103394534/162650800-31845623-9ec5-46db-b9b9-4baf78e08f7f.png)

![edu_phpbb_permissions_moderators_new-mod-group-added-768x517](https://user-images.githubusercontent.com/103394534/162650832-41ce0a4b-3ffa-4719-abb1-b14ccb1afac0.png)

**Comment by pixlguru** [comment]
imho for now it would be ok to just hide the server-config from the UI until there is a more evaluated solution. 
this is basically preventing me from assigning others as admins right now.

**Comment by dessalines** [comment]
@Nutomic What are your thoughts on just removing the config_hjson stuff? That's caused more trouble than its worth IMO, and it does expose some dangerous things.

**Comment by Nutomic** [comment]
I am mostly fine to that, but not having direct access to federation allowlist/blocklist would be a big limitation. Same might be true for the slur filter, but probably less important.

So if we do that, I think we need to move at least the allowlist and blocklist into database.

**Comment by dessalines** [comment]
> So if we do that, I think we need to move at least the allowlist and blocklist into database.

I def think that's a good idea, also even for the slur filter too. I'll open up an issue.

**Comment by poVoq** [comment]
I think it is useful, even if not for purely technical reasons.

First of all it allows giving people some recognition for vital moderation work and also allows making the admin accounts a bit more fully featured than they are right now.

**Comment by dessalines** [comment]
This is probably moot now, since we've moved all the site wiring into the lemmy.hjson, and the configuration into the database.

The only destructive things that admins can really do now, is purging (which deletes things from the database, and they're not restorable). 

Besides that, I can't think of any action that would differentiate a "Sitemod" from an admin.

**Comment by not-layla** [comment]
The remaining concern I have is mainly semantic but I still think it's worth discussing.

I think there's still value in having a concept of a sitemod versus an admin. An admin is seen to be a leader of the community, someone who makes decisions and steers the community as a whole. A sitemod means someone who's a mod on all communities. The difference being that admins make decision on site policy/announcements, sitemods are there to help deal with spam, trolls, etc.

We *could* probably make all sitemods on Hex admins, but the hierarchy won't be obvious anymore.

**Comment by poVoq** [comment]
I agree that the distinction is worth-while, however I see admins more as those running the infrastructure and due to the inherent power-imbalance resulting from that, might rather feel especially reluctant to intervene in community disputes or make policy decisions unilaterally BDFL style (although sometimes that's unavoidable).

**Comment by dessalines** [comment]
I'd need a specific list of abilities / actions that differentiate the two.

**Comment by poVoq** [comment]
For example, block remote users instance wide, but not block full instance?

**Comment by dessalines** [comment]
I disagree with that one, sitemods should def be able to block instances, that's the main way lemmy servers are being attacked currently (open federation, someone spins up a malicious instance, and does nazi-spam).

**Comment by poVoq** [comment]
Maybe temporary instance blocks only?

**Comment by not-layla** [comment]
A temporary instance block sounds like a good compromise to me. Something the Admins can then decide on making permanent, which imo is above what a sitemod should be able to do.

**Comment by dessalines** [comment]
We don't have temporary instance blocks even for admins yet, so that's a separate issue.

**Comment by not-layla** [comment]
So do we agree that sitemods will be able to do the following?

- Temporarily block instances (will require a new issue)
- Remove posts comments anywhere on the instance
- Ban users
- Lock posts
- Appoint/remove mods
- Feature posts instance-wide

There are probably some things I'm missing, but hopefully that gives a rough idea of the privileges sitemods should have.

**Comment by poVoq** [comment]
> Appoint/remove mods

I think that will also require a separate issue as Admins also seem to be unable to do that? I know there is a way to do it somehow, but I have not yet found it in the UI.

**Comment by not-layla** [comment]
On Hexbear, admins and sitemods make somebody a mod by pressing the `appoint as mod` button on a comment the account they're modding made in that community. I recently made a community on Lemmygrad and it seems to work similarly for a comm-mods, not sure about admins on Lemmy though.

**Comment by poVoq** [comment]
Ah, never mind. Its the same on Lemmy. The problem is just that a site Admin can not do it on themselves it seems.

**Comment by dessalines** [comment]
@not-layla None of those are things that admins can't already do. Again I need a list of things that **differentiate** the two, not the things they'd have in common.

**Comment by not-layla** [comment]
Is there a full list of actions an admin can do? If not, I think these are the differences:

- Sitemods can only block/defederate instances temporarily
- Sitemods can't access any site configuration (if it still exists, I don't have a local Lemmy instance running anymore, but e.g. they can't access anything under `/admin`).
  - Create/remove communities
  - Disabling/enabling community creation
  - Turn off/on registration
  - Turn off/on downvotes
- Sitemods can't promote other users to sitemod
- Sitemods can't promote community users to community moderator
- Sitemods can't mass-delete/purge an account's history

**Comment by dessalines** [comment]
> - Sitemods can only block/defederate instances temporarily

Doesn't exist, and also seems arbitrary, since blocks could be undone at the click of a button anyway.

> - Sitemods can't access any site configuration (if it still exists, I don't have a local Lemmy instance running anymore, but e.g. they can't access anything under `/admin`).

https://github.com/LemmyNet/lemmy/blob/main/src/api_routes_http.rs#L326

The only thing I see there, that should be limited (probably to only the top admin honestly, not even to regular admins), should be the purging, because of how dangerous that is.

>   - Create/remove communities
>   - Disabling/enabling community creation
>   - Turn off/on registration
>   - Turn off/on downvotes

These all seem arbitrary, and not necessary, especially since they're easily reversible right away. I doubt you could get two people to agree on what set of abilities should be granted to tier-1 admins vs tier-2, tier-3, tier-4 admins... etc.

> - Sitemods can't promote other users to sitemod
> - Sitemods can't promote community users to community moderator

Maybe... but as these actions are reversible, and the hierarchy is still preserved (IE one rogue mod who appoints a bunch of alts for example, can be easily fixed by a mod higher than them in the list), its not necessary.

> - Sitemods can't mass-delete/purge an account's history

Probably the only case I can see where 2-tiers of admins are necessary... and probably only the site creator should be able to do this, because of how destructive it can be.

---

I don't really see a case for maintaining complicated layers of admins, with different abilities chosen arbitrarily, when all of these actions are easily reversible, and the hierarchy prevents rogue mods from doing any real damage. 

I also dislike business-logic related suggestions, that complicate, rather than simplify. One could make the case for several tiers of admins, all with different sets of abilities chosen arbitrarily by whoever's making the request. Lets keep it simple, and just have admins and mods.

**Comment by Nutomic** [comment]
One way to solve this would be a functionality to let admins define different user roles with custom permissions, like in phpBB for example. However that would be quite complicated to implement.

![Uploading Screenshot_20230131_211734.png…]()

**Comment by not-layla** [comment]
Yeah, that's also more similar to how Reddit lets you define certain permissions for each moderator.

**Comment by not-layla** [comment]
Closing.

I still think something like sitemods is very nice but it wasn't worth the extra maintenance burden for us. A permissions based system similar to Reddit would be quite nice but is out of scope for this issue, someone else can create that.

**Comment by DraconicNEO** [comment]
I think that there is merit in separating moderation and administration permissions for those at the site level. On Mastodon they have moderation actions related to Suspending users, approving users, removing posts, defederation, and the like in a separate tab than administration, things like instance configuration, database, that sort of stuff. 

It's good to have them separated, since a bad moderator could seriously break an instance badly with access to the admin tools, but less damage can be done with only access to moderation features, bans and post removal can be reversed. Deleted data can't always be recovered. So having global moderators separate from admins is a good idea since it allows giving them the authority to moderate the instance without the risk they may permanently break stuff.
