### ISSUE TITLE
Restrict registered usernames (e.g. not allow slur-filled usernames)

### ISSUE THREAD

**Issue by GitOffMyBack** [LemmyNet/lemmy#2084]
### Is your proposal related to a problem?

Someone had registered to our instance with the name of “hitlerschild” and we don't want slur-filled usernames on our instance.

### Describe the solution you'd like

Maybe, a slur filter for account creation?

### Describe alternatives you've considered

An alternative would be that all new accounts would need approval from an administrator/moderator.

**Comment by gaywallet** [comment]
As someone with a username that sometimes gets filtered, I would like to suggest that if something is implemented that a default should be selected that is pretty conservative with regards to what is blocked (obvious slurs, like the f word rather than things that aren't obviously a slur, like gay) and allows for people to manually edit the regex code to suit their needs.

**Comment by dessalines** [comment]
This is already done, use the `slur_filter` setting in your `config.hjson`.

https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/src/user/create.rs#L113
