### ISSUE TITLE
Lower rate limit for search

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2153]
We are getting a few spammers that are exploiting the high rate limit for search, which can be an expensive operation, using the very permissive messaging rate limit. 

Instead of adding a different one, I'll lower it to the comment rate limit (6 per 600 seconds) for now.

**Comment by this-josh** [comment]
I appreciate this issue was closed over a year ago, but it may be worth reviewing.

As a new user of Lemmy I inherently want to conduct a large quantity of searching to best understand what is already here. This rate limit is providing significant friction. I dare say a lot of new users will be searching for similar things to me - the major Reddit communities.
