### ISSUE TITLE
Dont use "subscribed" as default view for new users

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2195]
![Screenshot_20220405_125933](https://user-images.githubusercontent.com/1044450/161739757-b6ffbe99-4223-4e2d-aae3-8cd273c66d78.jpg)

When a user signs up, he will only be subscribed to the instance's default community. So if he doesnt find the buttons for local/all, he will not see any other content. So i think it makes sense to use local or all as default view for new accounts, and let them change it to local manually after subscribing to some communities.

Similarly, users without login will see the local view by default, which can be very inactive on small instances. So in some cases, it would make sense to show all by default. Maybe it should be configurable by the admin?

Alternatively we could make the subscribed/local/all buttons more obvious in the frontend.

**Comment by tafiti** [comment]
I think it should be configurable from the admin side. 
I also think it is a good practice for admins to include a sidebar line that helps new members know the differences between local/subscribed/all.

**Comment by dessalines** [comment]
We used to have All be the default view for not logged in users, and decided against all can be mostly filled with federated posts, and isn't a representation of what your instance is going for. I def think we should leave that to local, and not keep going back and forth.

I do agree tho that it would probably be best to have local be the default for newly signed up users too... a lot, after getting redirected to the communities page after signing up, only subscribe to a few communities. 

> I also think it is a good practice for admins to include a sidebar line that helps new members know the differences between local/subscribed/all.

This already exists, the little help icon right on the filter bar goes to a page that describes what all those mean.

As far as making this configurable, I don't know that its that necessary, since its already a user preference.

**Comment by tafiti** [comment]
For instances that are selective on who they federate with, their identity is largely maintained when you view by `all` instead of local. I would also argue that this showcases federation right from the bat in that a random visitor gets to see what the ecosystem actually looks like. 
On many occasions, a member of a "small" instance prefers to subscribe on to a major community, like c/privacy on a "bigger" community and those posts form a core stream of posts on those "smaller" instances. A new visitor may never know about all this if they just landed to /local and do not know about the options. Defaults matter. 

Instead of hardcoding a default, what if admins can get to choose between all and local?

**Comment by Nutomic** [comment]
Another example are users who visit one of the "recommended instances" on join-lemmy.org. Those users are probably interested to content from the overall Lemmy network, not just from the particular instance. On the other hand, someone who directly joins an instance covering a particular topic is probably most interested in local posts.

So i agree that the only good solution is to make it configurable for instance admins. A single setting which applies to users both with and without login should be enough (with options being local or all).

**Comment by dessalines** [comment]
Its doable, it'd be a `default_post_listing_type` in the site table.
