### ISSUE TITLE
Posts deleted by the creator or a mod still show up on remote instances

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#2212]
### Issue Summary
Posts deleted by the creator or a mod still show up on remote instances  
1. fetches still return posts 
2. posts already fetched dont get the federated delete signal

### Steps to Reproduce

1. make post and delete it as mod or creator
2. fetch community remotely
3. observe post is there
#### OR
1. make post
2. fetch community remotely
4. delete post as creator or mod
5. refresh community and observe post is still there

### Technical details

IDK if this is a known issue or what.

**Comment by Nutomic** [comment]
There are two different cases where this behaviour can happen. The first is when you fetch a community, it also fetches a list of last 20 posts. Before Lemmy 0.16.3, this list also included deleted/removed posts. This was fixed in https://github.com/LemmyNet/lemmy/pull/2184.

The other case is if you fetch a post (or fetch a community which includes posts), but dont subscribe to the community. The way that Activitypub works is that actions (like delete) ar sent by an actor (community in this case) to its followers. So if no one on your instance follows the community, you wont receive the delete. Only workaround is to enter the post url in search, then your instance will note that the item was deleted, and mark it as such.

**Comment by dessalines** [comment]
Based on the "reproduce bug" steps, this can probably be closed as it was fixed by #2184
