### ISSUE TITLE
Check to make sure Instances are live

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2221]
### Issue Summary

 Re: https://lemmy.ml/instances

When you are looking through this list of instances, you find a lot of them are not active. This takes away from the user experience and could give a bad first impression to people.

My suggestion would be to run an automated check once a day or once a week and exclude them from the list if they are not active.

Examples of dead links included in the instances list:
https://eope.xyz/
https://forum.purplerabbit.xyz/
https://lemmy.161.social/
https://lemmy.2labz.com/
etc

**Comment by dessalines** [comment]
Seems like a good idea, especially in order to not keep sending dead instances activities. 

It is complicated tho by the fact that an instance might go down for a while, then come back up. @Nutomic might have some ideas. I'd rather it not have to be explicitly defined ( IE add the dead instances to the blocklist ), but that might be unavoidable.

**Comment by Nutomic** [comment]
If its only about the /instances page, it should be easy enough to list only instances from which we received a new post in the last 30 days.

**Comment by dessalines** [comment]
It might go beyond that... that lemmy will try to push activities to instances that have been dead, potentially for more than a year.

**Comment by Nutomic** [comment]
Yes thats a separate issue.
