### ISSUE TITLE
PeerTube vote federation issues

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#2310]
### Issue Summary
There are two issues:
1. If you remote-view a peertube instance from lemmy, and vote on a video, the vote will get counted twice on lemmy.
2. If you vote on a peertube instance, that vote will not show up on lemmy.

### Steps to Reproduce

1. sign into both peertube and lemmy accounts
2. View a peertube video from lemmy and from peertube
   1. Vote from lemmy and see it count double (1)
   2. Vote from Peertube and see it **not** show up on lemmy (2)

### Technical details
IDK if the second one is an issue with lemmy or peetube =/

**Comment by Nutomic** [comment]
The second problem (Peertube votes not reaching Lemmy) is because Peertube seems to send votes in a completely different way from Lemmy, namely by sending `Update/Video` which contains a likes collection. Lemmy instead sends a `Vote` activity.

I can also reproduce the problem with Lemmy votes being counted twice. But there is nothing received from Peertube, so this looks like a problem inside of Lemmy.

**Comment by Nutomic** [comment]
Very old issue, please open a new one if there are still problems.
