### ISSUE TITLE
Proposal to modify the current Lemmy RSS feed setting, to allow downloading all the RSS feed items

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy#2319]
Currently, any RSS app allows downloading only ten items of the RSS feed of a Lemmy community (New or Hot, etc.).
After the first download of ten items, it added the newest ones once created.
I propose to modify the current Lemmy RSS feed setting to allow downloading all the RSS feed items, or, at least, leaving the user to choose how many items to download.

**Comment by dessalines** [comment]
I'd rather this just have a sane default, I'm not sure what would be best.

**Comment by Nutomic** [comment]
Its impossible to return all items, because that might be hundreds or thousands in an old community. This would use a lot of server resources to generate. And the purpose of an RSS feed is to get updated about new items, so it gets fetched frequently. Usually when a reader fetches a feed, there will only be a few new items, the older ones are already known and essentially useless. So we can increase the number of items to 20 or so, but i dont see any use for a count param. 

If you use RSS feeds for some other purpose than a feed reader, then you should use the api instead.

**Comment by vn971** [comment]
For anyone browsing this in the future, if you want to limit the number of feeds _to a lower value_, you can specify it with `&limit=5` for example. I've found it useful to only fetch a few posts per week maximum for a certain community, and not like 20 items.
