### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2338]
I have had a few instances where a user has set up a community and I did not realize it. Is it possible to get a notification like we do when somebody comments on a post or replies to a comment.I would just like to know when a new community is set up so I can see what it is about.

Also how to I add myself as a moderator to communities set up by users.

**Comment by dessalines** [comment]
If you are an admin, you don't need to add yourself as moderator, you already have full control over every community.

You can also limit new community creation to admin_only in the site settings.

Notifs are only for replies, messages, and mentions, so I'm not sure how the notif you're talking about would work. If you submit a PR for some way to do it tho, I'd be happy to take a look. Otherwise just keep an eye on your instance and you'll see posts from the new communities on your front page anyway.

**Comment by Kap2022** [comment]
thx
