### ISSUE TITLE
Require admin approval for creating new communities

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#236]
Right now any user can create any community they want. That can be problematic in various ways. For example, admins might not want to have communities about certain topics at all (porn, illegal content, etc). Or they might only want a certain group of people to be mods. 

To achieve this now, admins or mods (afaik) have to monitor new communities at all times, and retroactively delete any that they dont like. A required approval step would make this easier.

**Comment by dessalines** [comment]
Both of the options have pros and cons. The two options:

- Let ppl comment, post, and create any community, with little to no barriers. This is how reddit works now.
  - Good: ppl can get excited about adding content quickly, not having to wait for approval. 
  - Bad: as you said, you have to play janitor and clean up shitty comments, communities, and posts after they've been made.
- Have approval processes for communities and or posts / comments. 

I lean towards the first one, that you let ppl create communities and then remove them after the fact. After all they could still create an innocuous sounding community name, (like fash like to do nowadays), then fill it with anti-semitic garbage, and you'd have to remove it anyway. So the clean-up work is unavoidable even if you do have an approval process.

Also a community approval process would only have : 
- A random username, who the admins probably don't know. Not really helpful.
- A community name, might not be that helpful in telling you what it is.
- Possibly a description or application (which would be a dupe of #209 .

Since admins can already remove (and reinstate) communities at the click of a button, it at least makes the janitorial work not too difficult.

Plus there's also the coding of the community approval process which would not be fun at all for me.

There is currently an issue that I'm dealing with: where if someone creates a community, removing it doesn't actually delete it, but just hides it from everything (meaning ppl can squat on popular community names) . To fix this I'm gonna make sure that admins can both mod, and transfer any community to any user. #238

**Comment by duck57** [comment]
Could the requirement for admin approval when creating new communities be a server-wide setting?  Admins who are more trusting of their communities may have it off while admins who prefer an active role in the day-to-day moderation of their instance can have it on?

**Comment by Nutomic** [comment]
How about a config option which would allow admins to create communities? Then they could manually create communities when requested. This would be much easier to implement, at least in the backend.

**Comment by pluja** [comment]
@Nutomic I second this. I think it would be an awesome feature for some instances where you don't want anyone to create a community. I personally prefer creation requests rather than be checking and deleting communities.

**Comment by Nutomic** [comment]
> How about a config option which would allow admins to create communities? Then they could manually create communities when requested. This would be much easier to implement, at least in the backend.

This has been implemented for a while with option `Only Admins can create Communities`
