### ISSUE TITLE
Unidirectional friend list feature

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy#2400]
Fb has a bidirectional friend list, where you send a friend request and the other person has to accept it. People for the most part don't seem to use lemmy to make internet friends, but i would personally use a bidirectional friend list.

I believe reddit has a unidirection friend list where it essentially adds users to a list and puts a [f] by all their posts so it's easy to see their content + it's easier to find their profile. Ex its a bit difficult to remember if my friend is @potato69420 or @potato42069.

This would streamline lemmy instead of me using browser url history to find friends. I think non redditors, say facebook users, would also like seeing familiar features like this.

### Is your proposal related to a problem?

No

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

Using a notepad file to keep track of users

**Comment by dessalines** [comment]
Lemmy doesn't support user-following yet, but when we eventually do, we'll try to adhere to how mastodon and other apub services do it.

**Comment by Nutomic** [comment]
We are planning to add functionality so that users from other federated platforms like Mastodon can follow Lemmy users. This is relatively easy to implement, and there should be an open issue already.

Another matter is functionality to follow users from within Lemmy. I believe this would require major changes to most parts of the code, and for that reason I consider it completely out of scope. If you want to follow people, use one of the many other fediverse projects which support that.

**Comment by unusualevent** [comment]
@Nutomic what kinds of code work or updates or prep work would be needed to support following users in Lemmy?

Can I make a new issue?

**Comment by Nutomic** [comment]
It would require a complete rewrite of the project. You can use kbin instead.
