### ISSUE TITLE
A feature to auto delete all of our own content after say 2 weeks

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy#2415]
### Is your proposal related to a problem?

Yes

### Describe the solution you'd like

Mastodon has this. With the rise of brigading and stalking, it wont be long before lemmy users start doxxing each other.

Even automatically hiding content after 2 weeks or a configurable amount would help

### Describe alternatives you've considered

Using mastodon instead

### Additional context

No

**Comment by dessalines** [comment]
This would be fairly easy to implement, and would just require another user setting.

**Comment by Nutomic** [comment]
Such a feature makes sense on Mastodon, where you shout things into the void and they disappear in a matter of days. This is not the case on Lemmy, you can have threads remaining on the frontpage for a week or more, especially if you use sort methods like "new comments" or "top month". If such a feature existed, it would create holes in comment threads, making them unreadable. Even a longer timeout wouldnt necessarily help, because some people likely want to read threads months or years later, for example to look up instructions (remember all the times you end up on an old forum thread from a google search).

Another thing is that there is no reason for such a feature to be included in Lemmy, because it can easily be implemented with an API client. That would also reduce the maintenance effort, and probably result in fewer people using the feature.

**Comment by Nutomic** [comment]
> What about anonymizing? A user option that deletes the username from comments and/or posts after a certain amount of time. 2 weeks? 2 months? And for users who want to delete their profile, an option to anonymize all posts as a part of the deletion procedure.

I agree, that sounds like a much better solution. Right now deleting your account also means that all your posts get deleted, anonymizing them instead would be better to prevent valuable content from disappearing. Would you mind to open a new issue for that, and we close this one?

**Comment by Nutomic** [comment]
Thank you!
