### ISSUE TITLE
Custom emotes

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2419]
Allows instance admins to define a list of custom emotes.

Can be typed out in text:

![](https://www.hexbear.net/pictrs/image/z4uYUYA5KU.png)

This text gets rendered as an emote:

![](https://www.hexbear.net/pictrs/image/qmRaZhikDL.png)

When typing, there is an auto-complete pop-up:

![](https://www.hexbear.net/pictrs/image/SPL91QU6PM.png)

There is also an emote picker:

![](https://www.hexbear.net/pictrs/image/5SMHrynoh3.png)

### Notes on implementation

The emote picker's performance is *extremely* poor, whatever our implementation of it sucks.

This already exists in ActivityPub, Mastodon has this feature, and it should ideally be implemented in a way such that it federates with Mastodon.

Mastodon's implementation is somewhat similar with Hexbear's, though their emote picker is significantly more performant. Both support animated emotes.

**Comment by dessalines** [comment]
The federation stuff is the tricky part... if these are community rather than instance-based, then there needs to be some way of sending those DB rows to other instances that have connected to that community. 

If @Nutomic thinks that's not doable, then I'd say we stick to emojis being instance-based, and have users request instance admins rather than community mods to add them.

**Comment by dessalines** [comment]
As far as an emoji picker, I've had terrible luck finding a good pure-js one, so we'd have to do a lot of searching. The last one lemmy-ui used (and I later removed), was bigger than the entire UI itself.

**Comment by Nutomic** [comment]
Emoji federation as done by Mastodon looks pretty simple. Basically it just includes all emojis used in the message in a [tag field](https://docs.joinmastodon.org/spec/activitypub/#extensions) (search for "Custom emojis"). It doesnt seem necessary at all to synchronize the full list of emojis of each instance/community. But we will probably need an `emoji` db table which stores all local and remote emojis.

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "toot": "http://joinmastodon.org/ns#",
      "Emoji": "toot:Emoji"
    }
  ],

  "id": "https://example.com/@alice/hello-world",
  "type": "Note",
  "content": "Hello world :kappa:",
  "tag": [
    {
      "id": "https://example.com/emoji/123",
      "type": "Emoji",
      "name": ":kappa:",
      "icon": {
        "type": "Image",
        "mediaType": "image/png",
        "url": "https://example.com/files/kappa.png"
      }
    }
  ]
}
```

**Comment by makotech222** [comment]
I'm looking to pick this one up after Featured Posts is finished. Porkroll's post pretty much lines up with what I would expect to implement. I would say I'd like to keep emoji's as instance-specific, rather than allowing communities to have their own lists, which seems like overkill and may increase complexity a bit. I am also deficient in the apub stuff, so I'll probably need some more direction around that part. But otherwise, are there any objections to that design?

**Comment by makotech222** [comment]
I'm digging in a bit on the frontend. It looks like the most popular library for a picker is https://github.com/missive/emoji-mart, which is unfortunately a React-dependent library. There doesn't seem to be any native one for Inferno. There seems to be ways to 'host' the component in Inferno, using something like remount library, or maybe inferno-compat. Are either of these options that you guys want to bring into lemmy? Or should I try writing my own emoji picker component entirely in inferno?

**Comment by Nutomic** [comment]
For federation you will have to add the `tag` array shown in my previous comment to [Page](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/protocol/objects/page.rs#L41), [Note](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/protocol/objects/note.rs#L28) and other places where emojis can be used. It should contain a list of all emojis which are used in that item, so that the placeholder text (`:kappa:` in the example) can be replaced with the emoji image by each federated platform.

**Comment by dessalines** [comment]
We used to use an emoji-picker in lemmy-ui, but it was larger than the entire UI itself so I removed it. It might unfortunately be necessary to make an inferno specific one, which you could probably mostly copy-paste from the react one.

Or code one from scratch. All you'd need is a library that has a json list of all the emoji shortnames (I think I found one before), as well as the groupings.

As far as federation for custom emojis, these will have to be picture URLs I think, for them to work across different servers.

**Comment by makotech222** [comment]
> We used to use an emoji-picker in lemmy-ui, but it was larger than the entire UI itself so I removed it. It might unfortunately be necessary to make an inferno specific one, which you could probably mostly copy-paste from the react one.
> 
> Or code one from scratch. All you'd need is a library that has a json list of all the emoji shortnames (I think I found one before), as well as the groupings.
> 
> As far as federation for custom emojis, these will have to be picture URLs I think, for them to work across different servers.

I have a prototype working with the emoji-mart v5, the .js file is only 95kb, though it may be downloading the default emojis separately, ill have to double check that.
