### ISSUE TITLE
Anonymization of content when deleting user

### ISSUE THREAD

**Issue by ColdHotman** [LemmyNet/lemmy#2426]
### Is your proposal related to a problem?

When a user deletes their account, all their content is deleted as well. This leads to a lot of content disappearing, often ruining discussions and whole comment sections where other users have put in valuable time and effort. This also degrades the future experience of browsing older Lemmy posts.

Practice among similar platforms is to leave the content but anonymize the poster.

### Describe the solution you'd like

Rework the account deletion procedure, perhaps offer the user these three options;

- Delete account, leave posts and comments as is
- Delete account, anonymize posts and comments
- Delete account, delete all content

### Describe alternatives you've considered

If I were to leave;
- If I wanted to preserve content and didn't care about anonymization - Just not use the account.
- If I wanted to preserve content but couldn't anonymize - Delete it all.
- If I wanted to delete all content, delete account.

### Additional context

Original discussion
https://github.com/LemmyNet/lemmy/issues/2415

I suspect GDPR requires Lemmy to offer full deletion, not only anonymization.

**Comment by Nutomic** [comment]
In terms of federation we use `Delete/User` activity which calls `delete_user_account()`. There is nothing like an "anonymize" activity, unless we introduce a nonstandard activity, so I would just leave federation as is. Then `delete_user_account()` needs to be changed to update the creator of posts/comments etc, instead of deleting them. 

It might be a bit confusing if one platform treats `Delete/User` as "anonymize", and another actually does deletes, but I dont think its a big problem. We should just change the message for account deletion, and inform users that they need to delete items manually if they want them gone completely.

**Comment by dessalines** [comment]
Maybe "anonymize but don't delete" could be an option. Because some people might want their account content fully deleted, they might have comments years back that divulge personal info, and wouldn't want to have to find every one of those manually. Also there might be privacy / GDPR issues for content deletion.

**Comment by Nutomic** [comment]
If we make an option, then I think it would be better to have anonymization of content as default, so people only choose that when they really want it. That would limit the problem with existing posts and comments disappearing over time.

**Comment by heylix** [comment]
watch out that this doesn't amplify #3165 please @Nutomic

**Comment by RocketDerp** [comment]
I observe that all the instances I've visited have no "terms of service" before signup that explains what Lemmy is about.

I think private direct messages should be purged on account deletion, but I think the very nature of a public posting on a public website is to keep things public.  And in 2023, people are well aware of this issue because of AI chatterbots being trained on "internet data".

A terms of service for a federated Lemmy instance is a pretty tricky thing, because data is shared across national lines to other federated instances. I wouldn't even promise that the account name would not be held, that other federated instances don't keep the profile archived too.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3817
