### ISSUE TITLE
URL to pictrs is fixed on domain

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2427]
### Issue Summary

All inserted pictures use the full domain. This does not allow for a server to move to a new domain. The links should be independent of the domain name or the name inserted at runtime and use hostname from config: 

```
domain specific: ![](http://localhost:1236/pictrs/image/50aa0101-84ff-4a0c-9937-05b5a926bea2.jpeg)
domain agnostic (relative link, actually works already): 
![](/pictrs/image/aceb29c1-aff8-498b-b8f9-6f659b89a1aa.png)
```

Is there a quick-n-dirty hack to disable the full domain creation, where in the code is this?

### Steps to Reproduce

1. Insert pictures
3. Move lemmy to another domain

### Technical details
v 0.6.16

**Comment by Nutomic** [comment]
Relative links will not work over federation, because images are always loaded from the original instance. You can see it [in this link](https://lemmy.ml/post/451013), we are viewing lemmy.ml but the image is loaded from szmer.info. Also, changing the domain will cause many problems with federation.

**Comment by sam365724** [comment]
My use case is a private instance though, maybe for such a setting it makes more sense? I understand thought that this is a big change as urls all spread all over the tables in the database... 

Another use case is if an instance is accessible from multiple domains and/or from a hidden service for example.

**Comment by Nutomic** [comment]
Even so, you might enable federation at some point in the future, and it would be bad if that breaks images.

A solution could be to serve image urls differently via api and federation. So the API would serve relative paths like you suggest, and federation would use absolute urls. Implementing this would probably require a new database table `images`, which contains information about all locally uploaded images (instead of storing image links directly in comment markdown).

**Comment by dessalines** [comment]
Manual DB work is required no matter what if you are migrating domains. 

I don't think we should support relative picture paths, because as nutomic stated, if you ever decide to turn on federation, relative paths aren't going to work.
