### ISSUE TITLE
Automatic mod action based on number of reports

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2505]
If a new user account receives multiple reports within a few hours, that account should automatically be blocked and content hidden. Then an admin has to review and possibly unlock the account. This needs to takr in account that reports from remote instances could also be fake.

Edit, could also be done in case of many downvotes.

**Comment by dessalines** [comment]
Definitely abusable (all you'd have to do is find the content, get a few accounts to make a few downvotes / reports to remove it.

One configurable way to do this, might be to have an optional site setting which can hide / collapse content that has a certain ratio or downvote count. Then the front ends could find different ways of collapsing that, kind of like reddit does with comments with very low ratios.

I'm just wary of using numbers of reports to hide content, because that turns them into super-downvotes, rather than things that mods / admins need to look at.

**Comment by Nutomic** [comment]
I dont think its a good idea to add another api field which clients need to handle, because there are already a lot of things.

To prevent the problem you mention, this should only be done if the reports come from "trusted" users (local account, at least x months old, at least x karma, at least x posts/comments, etc).
