### ISSUE TITLE
Consider switching config to toml format

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2567]
We are currently using hjson, which is a very uncommon file format, and not well supported. I think we should consider switching to toml instead, which is much more well known, and also has better library support such as the [toml](https://crates.io/crates/toml) crate.

**Comment by dessalines** [comment]
I'm def against this, I hate the toml format [when compared to json](https://martin-ueding.de/posts/json-vs-yaml-vs-toml/). I'm convinced the only reason people use toml, is because they don't know about the json+comments variants like hjson or json5.

canop's deser_hjson has been working fine.

**Comment by Nutomic** [comment]
We dont have any nested structures nor lists in the config, so that criticism doesnt seem to apply at all. 

My main problem with json is that its made for machines, not for humans. Something like toml (or maybe another format) seems much friendlier in that regard.

**Comment by dessalines** [comment]
We do have nested structures, the database, setup, email, and pictrs blocks. hjson is made for humans and is much easier to read than toml. Json also shows hierarchy without duplicating key names, unlike toml.

**Comment by hbroer** [comment]
I would say use `yaml`. ^^ It is also used by docker, gitlab and many other projects. I personaly like plain `json` too. Most modern languages support it out of the box. I never used `hjson` or `toml` and both are "semi" good IMO. `hjson` is not compatible to `json` so you always need a lib for that and then you can also just go for `yaml`. And I don't know any project using `toml`. Not sure why the weel is reinvented every few years. :-D

**Comment by dessalines** [comment]
We already have a library for hjson, and its working perfectly.

**Comment by hbroer** [comment]
I only made a suggestion as reply to the initial suggestion. I personaly only stick to yaml on serverside when writing applications in go. I never would use anything else than json in JS/TS projects in frontend or backend (and that is my main scope). I heared of hjson the first time here and I don't see any benefit compared to plain old json. Comments should not be needed in (simple) config files and I like the fact that json is nativly supported all around. I use yaml only on serverside because it is used in many projects and I like the fact that people who use the project don't need to rethink everytime about a new format. What I like when using yaml is the feature to reuse code what is very convenient when writing CI configurations and complex config files in general.

There are too many formats for this simple task. And in worst case, if someone writes a script to automaticaly configure some applications to work together, then they may need a ton of different libs because everyone likes a special format. That's was everyting I want to say. ;-)

**Comment by Nutomic** [comment]
Actually our config works just fine with toml, see https://github.com/LemmyNet/lemmy/pull/2573. For me that seems easier to edit manually than the current hjson format.

Yaml is also very common, but I really dislike that it has significant whitespace. Its easy to get an intendation wrong, and then the file cant be parsed. Also the [doku](https://crates.io/crates/doku) crate only supports json and toml for now.

**Comment by Nutomic** [comment]
Closing the issue then as there are other things to work on.
