### ISSUE TITLE
Allow post creation from Mastodon

### ISSUE THREAD

**Issue by raphaeljolivet** [LemmyNet/lemmy#2590]
This feature request is the counterpart of #2144 for Mastodon (see [my comment there](https://github.com/LemmyNet/lemmy/issues/2144#issuecomment-1307111411))

I really feel that being able to create new topics from remote instances would be a game changer.
Lemmy would de facto become the "groups feature" the Fediverse is missing so much.

Putting **Mastodon** is the game would really help.
My understanding at this point is that mastodon only sends **Notes**, missing a title.

One workaround could be to **consider the first sentence of a Note as title**.
If we want to enforce it more, we could **force an empty line between title and body**, or force a custom syntax (like [title] for instance).

In any case, a federated user sending a bad request (bad type of message, bad format, anything) **should be informed it has failed** and why : maybe with a private message to him ?

**Comment by Nutomic** [comment]
So this would require a special formatting along the lines of:

```
title

link (optional)

body

@community@example.com
```

My question is, how would Mastodon users even know that Lemmy groups support such special messages, and what the format looks like? 

To me this seems like a very awkward hack, which will cause more problems than it solves. If you want to post on Lemmy, why not make an account on Lemmy, Friendica or another compatible platform? Or if you insist to post from Mastodon, then ask the developers to add the missing fields.

**Comment by dessalines** [comment]
A hack would be better than nothing. We could just assume, if they're sending a note to a community:

```
title - first line of masto note

link - none

body - Any extra lines, or none

community: the @community
```

**Comment by raphaeljolivet** [comment]
@Nutomic Lemmy already did a great effort to bring communities to the rest of Fediverse with little friction :
We can already follow, like and reply to topics created on lemmy instances.

Allowing other actors of the fediverse (including Mastodon) to initiate a discussion without to Switch to another instance / account would finalize this effort.

 @dessalines does a fair proposal.
 I would go even further : 
 * **title** : first line
 * **link** : first link found in the note, or none
 * **body** : extra lines

It sound intuitive to me. 
We could enforce any other format,.

For the argument : 
*"how would Mastodon users even know that Lemmy groups support such special messages, and what the format looks like?"* 
We could send a **private error message**, with explanation, in case of errors : 
- A user not part of the community trying to start a topic 
- A user sending a note to a community with bad format (whatever it is)

**Comment by lord-re** [comment]
Instead of formatting toots in a special way it would be better to use CW to be used as the title as its already a title.

For the link just take the first URL found ?

**Comment by dessalines** [comment]
CW? That's content warning

**Comment by lord-re** [comment]
Yes and these are Title which lets you open the message.
Some software even automatically add "RE: " to the CW when you answer to a note.

It's been used like this in gnu.social way before mastodon.

**Comment by ChristopherKing42** [comment]
Here's my suggestion: for each community, mastodon is presented with a top level post summarizing the community. Any replies to that in mastodon is interpreted as equivalent to a post to the community in Lemmy.

**Comment by informapirata** [comment]
> This feature request is the counterpart of #2144 for Mastodon (see [my comment there](https://github.com/LemmyNet/lemmy/issues/2144#issuecomment-1307111411))
> 
> I really feel that being able to create new topics from remote instances would be a game changer. Lemmy would de facto become the "groups feature" the Fediverse is missing so much.
> 
> Putting **Mastodon** is the game would really help. My understanding at this point is that mastodon only sends **Notes**, missing a title.


I apologize if my comment could be considered too OT but I'm not a developer and I express myself as an administrator and user of three instances friendica (poliverso.org), lemmy (feddit.it) and mastodon (poliversity.it).
I am an intensive user of Mastodon, but I strongly believe in the Lemmy + Friendica combination; I also believe that projects so much smaller than Mastodon, such as Friendica and Lemmy, cannot afford to waste their few resources distorting themselves in order to make Mastodon work better. Even if they would never admit it, already today lemmy and friendica developers have to be careful to stay compatible with mastodon...

Mastodon, with its dominant position as a de facto standard, can already afford to do as it pleases. Do you realize that a small change to Mastodon could make its eight million users incompatible with everything else in the fediverse?

However, I believe that one way to bring Lemmy closer to Mastodon without unnecessary trauma is to think of a solution to make the threads of the Friendica groups readable to one's own users.

Not everyone knows that already today with a Lemmy account it is possible to read, follow and correctly interpret the Friendica forum groups, seeing them as if they were Lemmy communities; unfortunately only threads that start with a post with the title/subject attribute are readable.

Since the Friendica forum groups are also fully usable by Mastodon users, with our instance poliverso.org, we have launched an experiment on the Friendica groups/forums in the Italian fediverse (here the post with the announcement https://feddit.it/post /107226 ). In this way, with our Friendica instance we are providing a service not only to the mastodon users of poliversity.it (our instance, dedicated to universities and journalism), but to the entire Italian faith universe: mastodon, pleroma, misskey and obviously friendica. I chose Friendica both because I can manage it easily and because I don't like gup's solution: too "proprietary" and "centralised".

Now, considering that, compared to Friendica, Lemmy formats conversations in a wonderful and much neater way, it would be pretty cool if there was a way for Lemmy to read threads in Friendica forum groups, EVEN WHEN they were opened by a Mastodon user ...

Ideas?

**Comment by Nutomic** [comment]
I agree that its a bad idea to let Mastodon offload the hard work to other projects. They are the ones with the most resources, and still dont manage to fix all their legacy issues. So its definitely better to focus on improving federation between smaller projects.

With regard to Mastodon users posting on Lemmy, thats actually mainly a UX problem, because lemmy-ui requires a title. Its not so hard to make a workaround, in case the `name` property is missing we use the beginning of `content` instead.

For Friendica this will also help, but there is another problem because forums themselves can make posts. In Lemmy only users can make posts, so the data structures dont fit.

**Comment by jonaharagon** [comment]
I have to disagree with the assessment at https://github.com/LemmyNet/lemmy/pull/2651#issuecomment-1382423664 that the link isn't important, I came to this issue trying to find out why I couldn't make link posts from Mastodon.

Lemmy [is](https://join-lemmy.org/) a "link aggregator," how could this not be a priority?

**Comment by Nutomic** [comment]
@jonaharagon You can open a new issue and propose how to solve it. Also include an example Mastodon post, because Im not sure if the link is available in a separate field, or has to be extracted from HTML (which would be quite complicated).
