### ISSUE TITLE
unable to access instance at various times, seems random, getting 404 fetch errors

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy#2612]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

When accessing an instance of Lemmy, sometimes I cannot access it. The only instance I have an account and thereby seen the issue with is Midwest.social.
"404: FetchError: invalid json response body at http://lemmy:8536/api/v3/site "

I've also had a few variations to the error message, but I haven't saved those. They were worded similar to the 404 error though. 

### Steps to Reproduce

1. Access any page at certain times. Some times it works, others it doesn't.

### Technical details

* User, not admin, so don't have this information.

**Comment by JackFromWisconsin** [comment]
![Screenshot_20221213-124411](https://user-images.githubusercontent.com/118757222/207418750-8f28b824-b103-40cf-a32b-540512faec1c.png)
Example of error page on my phone, running Firefox

**Comment by Arsen6331** [comment]
Getting the same problem on Lemmygrad. The first time this happened, it was during a DDoS of Lemmygrad. It then happened months after that, when no DDoS or anything of the sort was going on, and now it's happening again. Using TOR seems to fix it, and dropping my IP and getting a new one also fixes it. I think this may be some form of DDoS protection. If so, it is far too aggressive, since normal user interaction seems to trigger it.

I have contacted the admins of Lemmygrad, and they don't know why this is happening either.

![Screenshot of 404 FetchError message on Lemmygrad](https://user-images.githubusercontent.com/41810442/207480680-d73c1996-2447-41bc-9972-33a87dceca69.png)

**Comment by Nutomic** [comment]
Yes this sounds like rate limit, especially if switching ip fixes the problem. Currently Lemmy sends an empty response if the limit is hit. From 0.17 it will send an actual error message to make it clearer.

[Here can find the different types of rate limits](https://github.com/LemmyNet/lemmy/blob/0.16.7/config/defaults.hjson#L18). Were you doing any of these actions repeatedly before the problem happened?

**Comment by dessalines** [comment]
@Arsen6331 this is probably due to your bot making a ton of requests. I'd suggest using the websocket rather than doing polling.

**Comment by Arsen6331** [comment]
> @Arsen6331 this is probably due to your bot making a ton of requests. I'd suggest using the websocket rather than doing polling.

I've already added support for the WS API to my Go bindings and updated my bot to use them. This happened after that.

**Comment by Arsen6331** [comment]
> Yes this sounds like rate limit, especially if switching ip fixes the problem. Currently Lemmy sends an empty response if the limit is hit. From 0.17 it will send an actual error message to make it clearer.

Yes, that would be good. Also, currently I get HTTP 400 Bad Request when this is happening. According to the HTTP standard,  HTTP 429 Too Many Requests should be sent if a rate limit is hit, ideally (but not necessarily) with a `Retry-After` header to tell the client how long to wait until they can try again. This would allow things like HTTP retry libraries to automatically detect the rate limit and wait the specified amount of time or use exponential backoff if it is not provided, which would let clients more easily handle rate limits.

> [Here can find the different types of rate limits](https://github.com/LemmyNet/lemmy/blob/0.16.7/config/defaults.hjson?rgh-link-date=2022-12-14T12%3A04%3A34Z#L18). Were you doing any of these actions repeatedly before the problem happened?

No. I was just browsing Lemmygrad. However, I did do some troubleshooting. I looked at my router logs, and it seems every time I open the site, it creates two TCP connections to the server (presumably for the WebSocket). I had 14 connections open. Once I closed some Lemmygrad tabs I had open, the error seemed to go away. However, this could also just be the rate limit expiring, because I only tested this once and the problem hasn't happened since.

**Comment by dessalines** [comment]
Then it might have to do with your go websocket library not doing reconnects properly.

**Comment by Arsen6331** [comment]
I thought about that too, so I removed the library I was using for reconnects, and got a new IP again. This happened 4 hours later. After it stopped, it never happened again despite the fact that the bot was and is still running and connected, so the issue seems to be resolved for me. I'm not sure what was causing it. Also, I noticed that when this is happening, if I reload it a few times, I can actually get through and see the homepage, but then if I reload again or try to open a post or anything else, I get the error or it loads forever.

**Comment by JackFromWisconsin** [comment]
@Nutomic 
> [Here can find the different types of rate limits](https://github.com/LemmyNet/lemmy/blob/0.16.7/config/defaults.hjson#L18). Were you doing any of thesetions repeatedly before the problem happened?

Just had it happen again. I made one reply to an ask Lemmy thread, clicked the "communities" tab, and it timed out and gave the same error. I wasn't repeatedly commenting or clicking refresh.

**Comment by Kradyz** [comment]
I have managed to cross-section the problem. It seems to be more of a problem with the nginx rate limiting configuration than a lemmy problem. 

What I understand is happening is that, if you use the [nginx example configuration](https://github.com/LemmyNet/lemmy/blob/28eade6168fcceec13d6d29e985545b47f0b7ed6/docker/prod/nginx.conf), some event such as opening several new tabs might trigger a back-end rate limit block. The front-end not being rate limited will for cause the original tab to try to reconnect continuously, causing the  rate-limit block to persist.

Changing the IP allows the reconnect to work properly and so the problem is temporally fixed.

Here is an image of what my "Network" inspection tab looks like after I use a ctrl + click burst a post to open many new tabs:

![image](https://user-images.githubusercontent.com/81911574/214820210-a576a44d-db56-44ef-b86a-2cc399be02df.png)

The Stack Trace shows that I am trying to reconnect continuously, so the rate block keeps being triggered.

```
1242/e.prototype.tryConnect
[https://mander.xyz/static/js/client.js:2:587486](https://mander.xyz/static/js/client.js)
1242/e.prototype.reconnect/<
[https://mander.xyz/static/js/client.js:2:588203](https://mander.xyz/static/js/client.js)
(Async: setTimeout handler)
```
If I try to access any place, I get the message:
![image](https://user-images.githubusercontent.com/81911574/214820540-91bb7e23-53fd-43f2-b85a-3ee5c10d66c2.png)

And the docker-compose logs -f show:

```
lemmy_1           | 2023-01-26T11:04:11.889445Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:13.252378Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:14.640804Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:16.010240Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:17.382172Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:18.751600Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:20.109489Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:21.471986Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:22.838489Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined
lemmy_1           | 2023-01-26T11:04:24.206402Z  INFO lemmy_websocket::handlers: 155.133.11.39 joined

```


I don't know what the best fix is, but I have managed to fix the problem by including the ratelimit line in nginx's frontend section as well, so the rate limit block works also for the front-end:

```
        # Rate limit
        limit_req zone={{yourdomain}}_ratelimit burst=30 nodelay;
```
By making this change, I will get front-end blocked, and no reconnect requests will be sent. I will get this message instead - which does not persist:

![image](https://user-images.githubusercontent.com/81911574/214822380-c060b60c-68f4-41cf-a895-b7c8dcc980ac.png)


There is probably a better way to configure the rate limits, but I don't know how.

**Comment by Nutomic** [comment]
Seems like lemmy-ui needs to use a delay for retries if a rate limit error is returned.

**Comment by wiki-me** [comment]
> Yes this sounds like rate limit, especially if switching ip fixes the problem. Currently Lemmy sends an empty response if the limit is hit. From 0.17 it will send an actual error message to make it clearer.

I am getting the same error now (and not a message about rate limit)

> 404: FetchError: invalid json response body at http://lemmy:8536/api/v3/site

So it isn't the issue? or the code to report going over the rate limit is not sent?

**Comment by dessalines** [comment]
What error does the lemmy back-end say there?

**Comment by GitOffMyBack** [comment]
It seems that I've been able to reproduce this as well. Someone posted for help at Beehaw here: https://beehaw.org/post/356071

At first I just tried clicking all the links that they provided in the post and they all produced a 404.

Then I put each full lemmy link into the search field and clicked the search button. The spinning button appeared with no results after several minutes. I left the search page then came back, tried again and everything worked like it was supposed to.

**Comment by JackFromWisconsin** [comment]
Still getting this issue, on v0.17.4

Here's the error I got: "  404: FetchError: invalid json response body at http://lemmy:8536/api/v3/comment/list?max_depth=8&sort=Hot&type_=All&parent_id=292018 reason: Unexpected token 'T', "Timeout oc"... is not valid JSON  "

When trying to edit the post on this page: https://midwest.social/comment/292018
I also had typed something in the comment field

**Comment by RocketDerp** [comment]
For the past week, the front page of lemmy.ml has had very fast response with nginx 500 and 404 invalid JSON errors.  I've seen it also on Beehaw, but less frequent.

**Comment by Antik79** [comment]
We have this happening on lemmy.world too - server restart seems to resolve the issue.. But it happened a few times so far

**Comment by Nutomic** [comment]
Does this still happen with latest version? Please post full logs too.

**Comment by dessalines** [comment]
This seems stale, we can re-open if necessary.
