### ISSUE TITLE
Compatibility with Mastodon private messages

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2657]
In the interest of better compatibility it would be good of Lemmy users could exchange private messages with Mastodon and similar platforms. This is currently impossible because we use the [ChatMessage](https://docs.pleroma.social/backend/development/ap_extensions/#chatmessages) type for private messages.

Changing this is complicated, because we route incoming federation activities based on their json structure. This works very well in general, with private messages being the only exception. The problem is that the json structure of a Lemmy comment and a Mastodon private message are identical. The only difference are the presence of `https://www.w3.org/ns/activitystreams#Public` and community id in to/cc. Unfortunately this cant easily be encoded in serde data structures, so a custom deserializer might be the only solution (which would be complicated).

A better solution would be if we could check the [audience property](https://socialhub.activitypub.rocks/t/fep-1b12-group-federation/2724) if that ever gets supported by Mastodon, or a property like `privacy: "Public|Followers|Private"` which would be much easier to parse.

**Comment by RocketDerp** [comment]
> Unfortunately this cant easily be encoded in serde data structures, so a custom deserializer might be the only solution (which would be complicated).

My reply is in the interest of avoiding complexity, by perhaps having less-clean design/code.

> Changing this is complicated, because we route incoming federation activities

If the concern is incoming, I suggest a more dirty of a solution such as rewriting the JSON before parsing. Adding a raw-JSON layer that does sanity checks on length of JSON before parsing (excuse me if this already exists), recognition of some known problematic JSON that gets logged and discarded before parsing, etc.

With all the active developing going on with peer applications outside of Lemmy's control, I think it would be kind of routine to need the ability to implement dirty fixes - because the protocols and apps are all evolving rapidly.

> Mastodon private message are identical. The only difference are the presence of https://www.w3.org/ns/activitystreams#Public and community id in to/cc.

I would suggest doing a simple string search (not even regex) to look for that and then rewrite the JSON with a string replace so that it goes into  serde data structures you want. This structure would allow short-term solutions and not require complex change to a a custom deserializer.  And it gives a code path that can be hacked on when breaking changes come about in some other product's version or even when Lemmy itself starts to run into problems with older versions not having something in the JSON that newer versions evolve into.

**Comment by uis246** [comment]
https://socialhub.activitypub.rocks/t/distinguish-between-posts-and-direct-messages/2283
> property visibility with the value "direct"

**Comment by Nutomic** [comment]
I gave this a try in https://github.com/LemmyNet/lemmy/tree/federate-mastodon-pms. But its really hard to get working now, as it means that comments and private messages get serialized in the exact same format so its tricky to distinguish them. With private message its doable to check that neither `to` nor `cc` contains `public` as recipient. But for comment it requires a check that either `to` or `cc` must contain `public`. That is only possible with complicated workarounds, or once https://github.com/serde-rs/serde/issues/642 gets implemented in serde.
