### ISSUE TITLE
The ability to also disable upvotes

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2669]
### Is your proposal related to a problem?

Disbaling downvotes means people have to really engage with another person's comment. Reddit has this "downvotes if comment is off-topic, not if you disagree" rule on some subs, but it is not followed anywhere. Disabling them on Hex has been *such* at positive move for site-culture.

The same thing goes on for upvotes, but it's the other way round. Whilst less so than downvotes, they can also be used as a way that's toxic. The most obvious example is "ratio"-ing people. 

### Describe the solution you'd like

The ability to disable upvotes. Not sure if it'd only be an option if downvotes were disabled, but that's how I would run an instance personally, with them both disabled.

### Describe alternatives you've considered

n/a

### Additional context

- The algorithms would work exclusively via comments
- The only scenario I feel it'd be sad to lose upvotes would be e.g. if someone makes a joke, there's no way for.people to express it was funny without having to reply, and it'd be weird if someons got like 10 pepple replying "lol" to a comment. Anything small like that it'd be a shame to lose upvotes. But I can't think of a replacement that wouldn't lead to something like ratio-ing people etc.

**Comment by dessalines** [comment]
One way to promote healthy engagement, while still keeping voting and the sorting benefits from that, is to hide vote scores. We already have that as a user setting, but it could also be made into a site-wide setting.

Of course I'm not against merging a site-wide disabling of upvotes if someone wants that... its just doing away with voting entirely would bring back the hell of old-school forums: scrolling through 900 pages of content to find what's actually useful or what people found helpful. Disabling showing the scores gets rid of the negativity from "ratio-ing", while still keeping the sorting.

**Comment by ollien** [comment]
> One way to promote healthy engagement, while still keeping voting and the sorting benefits from that, is to hide vote scores. We already have that as a user setting for mental well-being purposes, but it could also be made into a site-wide setting.

I was looking at as implementing this as a setting on the community level, but one of the interesting things here is that, inherently, to still get the ranking, the votes have to be broadcast to other federated instances. This means that someone sufficiently motivated (i.e. enough to run their own, slightly modified, instance), could simply always show the scores. In other words, ratio-ing is still preserved if the instance you're browsing on decides to "show the score anyway".

Does this matter? Maybe, maybe not. Perhaps the only "fair" way to implement this is to make it so that scores are hidden by default as a "suggestion", but a user can reveal the scores if they so choose.

**Comment by dessalines** [comment]
Closing, but can re-open if someone wants to add this.
