### ISSUE TITLE
Titles are not generated correctly when posting from Mastodon

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy#2686]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

If you have problems installing Lemmy, you should post in [!lemmy_support](https://lemmy.ml/c/lemmy_support).

### Issue Summary

When making a post from Mastodon, titles are not generated correctly. 

### Steps to Reproduce

1. Use Mastodon
2. mention a community (ex. @lemmy@lemmy.ml) and write your post.
3. Look in from Lemmy
4. Posts do not have correct title, nor does the author display a name.

### Technical details

* Link to example post: https://midwest.social/post/410327
* Link from original instance on Mastodon: https://wikis.world/@JackFromWisconsin/109790232073633704

**Comment by JackFromWisconsin** [comment]
Interestingly, this other post handles title generation much better: https://lemmy.ml/post/741382 . Still has some unintentional html tags visible, but closer to what we want.

**Comment by Kradyz** [comment]
> Interestingly, this other post handles title generation much better: https://lemmy.ml/post/741382 . Still has some unintentional html tags visible, but closer to what we want.

That specific post looks like it works only because it hit the character number limit before the text reached the end of the paragraph tag (</p>). 

I think that the lines() call [here](https://github.com/LemmyNet/lemmy/blob/7e3d3839b60b52f5539699e1291c476820c67d43/crates/apub/src/objects/post.rs#L183) is expecting lines to be split by \n instead of having the syntax <p>...</p>. I am not familiar enough with the syntax in rust, but with python I would parse by splitting </p>, and then set name to the first entry from the third character.
So: `name = c.split('<\p>')[0][3:] `

**Comment by Kradyz** [comment]
I can confirm that the following modified syntax in [post.rs](https://github.com/LemmyNet/lemmy/blob/7e3d3839b60b52f5539699e1291c476820c67d43/crates/apub/src/objects/post.rs#L183) will produce a post with the correct title:

```
          .and_then(|c| c.split("</p>").next().map(ToString::to_string))
      })
      .ok_or_else(|| anyhow!("Object must have name or content"))?;
    name.remove(0);
    name.remove(0);
    name.remove(0);
```


Here is an example post:
https://mander.xyz/post/525157

I did not submit a PR because I suspect that there is a better way to slice the string than calling remove(0) three times. Also, this change might break from_apub() function calls while fetching posts from other projects, if it is used.

**Comment by informapirata** [comment]
> Quel post specifico sembra funzionare solo perché ha raggiunto il limite del numero di caratteri prima che il testo raggiungesse la fine del tag di paragrafo (</p>).

Also from Friendica:

https://lemmy.ml/post/741998  NOK

https://lemmy.ml/post/742002  OK

**Comment by mediaformat** [comment]
It would be great to strip the forum name from the title (and others I guess)

https://lemmy.ml/post/787329

This one also includes a content warning. 

Lemmy ignores the CW text but interprets it as NSFW (which I guess is technically correct, but misses the point of mastodon's albeit shoehorned subject/title field)

**Comment by JackFromWisconsin** [comment]
The forum ping can come anywhere, so putting it at the end of a longer post
makes it not visible in the title.

CW should be appended to the beginning of the body Content Warning:[text]),
but this should be a separate issue/suggestion

**Comment by mediaformat** [comment]
@Nutomic just realized the issue is closed. I can create a new issue; does this go in lemmy or lemmy-ui?

**Comment by Nutomic** [comment]
@mediaformat You can open a new issue in this repo.
