### ISSUE TITLE
Upvotes on Lemmy are sent as favorites on Mastodon, causing a notification and loss of privacy

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy#2687]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

If you have problems installing Lemmy, you should post in [!lemmy_support](https://lemmy.ml/c/lemmy_support).

### Issue Summary

When on lemmy and upvoting a post originating on Mastodon, a favorite is sent to Mastodon. This then sents a notification to that mastodon user that their post was "favorited" (actually: upvoted), and reveals the identity of the upvoter.

This is of course not intentional as votes are supposed to be private #2501 .

### Steps to Reproduce

1. Upvote a post originating from Mastodon.
2. Look at the Mastodon notification feed and see "Upvoter favorited your comment!"

**Comment by Nutomic** [comment]
It seems that Mastodon previously ignored federated Lemmy votes because they were marked public, and thus looked different from Mastodon likes. Now that Lemmy votes are private they look exactly identical to Mastodon likes, and are handled in the same way. So this is just a case of different platforms handling the same federated data differently, which is normal.

I dont think this can be fixed unless there is some way to make Mastodon and Lemmy votes look different again. In any case I dont think this is much of a privacy concern, because only the original poster can see the votes. And downvotes arent supported on Mastodon anyway.
