### ISSUE TITLE
Can't edit comment on a deleted post

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#2714]
I want to delete a comment from a deleted post instead of hiding it as the trash icon does. To overwrite its content I need to be able to edit it.

**Comment by informapirata** [comment]
> I want to delete a comment from a deleted post instead of hiding it as the trash icon does. To overwrite its content I need to be able to edit it.

It's not clear to me: did you write the comment you want to delete or edit? And so you don't see it due to the thread opening message being deleted?

If I understand correctly, you should be able to see your comment at the following link:

`https://[instance name]/u/[your username]`

If I don't understand correctly, please tell me

**Comment by JediMaster25** [comment]
I wrote a comment in a post and it was deleted. I found my message in my profile but I couldn't edit it because the message had been deleted.

**Comment by informapirata** [comment]
> ma non ho potuto modificarlo perché il messaggio era stato cancellato.

in this case, if you want to modify that message due to a right to be forgotten vis-à-vis your administrator, I think the best thing is to ask the courtesy of the administrator or moderator who deleted that message to restore it for the time necessary to allow you to change. however, know that a simple user is no longer able to read that message.

And it's not a real bug anyway

**Comment by dessalines** [comment]
We are currently doing [a few checks before allowing comment edits](https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/src/comment/update.rs#L52), like checking to see if the community or post is deleted. I think I could probably remove these. @Nutomic do you agree?

**Comment by Nutomic** [comment]
Yes makes sense.
