### ISSUE TITLE
Inconsitent spelling of remove_data

### ISSUE THREAD

**Issue by HelgeKrueger** [LemmyNet/lemmy#2734]
### Issue Summary

remove_data is spelled removeData in [crates/apub/assets/lemmy/activities/block/undo_block_user.json](https://github.com/LemmyNet/lemmy/blob/bcf5c91f81f54c3a3fda7bdf6b24a077a45413be/crates/apub/assets/lemmy/activities/block/undo_block_user.json) and  [crates/apub/assets/lemmy/activities/block/block_user.json](https://github.com/LemmyNet/lemmy/blob/bcf5c91f81f54c3a3fda7bdf6b24a077a45413be/crates/apub/assets/lemmy/activities/block/block_user.json). 

According to [the documentation](https://join-lemmy.org/docs/en/federation/lemmy_protocol.html#context), probably remove_data is the intended spelling.

**Comment by Nutomic** [comment]
Actually `removeData` is correct, because json keys are always in camelCase. This wasnt noticed before because Lemmy doesnt use the context at all, its only sent for the benefit of other software.

Let me know if there is anything else unclear. I also havent updated the docs in a long time. You should read the [FEP about Group federation](https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-1b12.md) which is more recent and gives a better overview.

**Comment by HelgeKrueger** [comment]
I guess "posting_restricted_to_mods" should be camel cased then, too?

Also "remove_data" is mentioned once in the text of https://join-lemmy.org/docs/en/federation/lemmy_protocol.html#block-user It probably also needs to changed to camel case then.

**Comment by Nutomic** [comment]
Youre right, thanks!

For the docs I probably have to make a complete overhault sooner or later because I havent touched them at all in over a year. But feel free to make a pull request and fix that in lemmy-docs repo.
