### ISSUE TITLE
Lots of looping querying without transactions in apub code, related to language code

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2772]
A lot of the apub code seems to have a ton of recursive querying, that will repeat very often.

Look at this function for instance:

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/objects/instance.rs#L133

It runs `LanguageTag::to_id_multiple`, which seems to do a looping query, rather than an in query. This whole file seems to be looping single fetch queries, rather than single fetch `IN` queries.

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/protocol/objects/mod.rs

That function then inserts a site, which then unfortunately clears and updates site languages, and then the community languages. It should only be doing these things after that `last_refreshed_at`, and it should not be doing any inserts / updates of languages if nothings changed. It should read the site from the DB first, to see if an update is necessary at all. And it shouldn't update languages unless those have changed.

You are then running `SiteLanguage::update`, which also updates the community_languages again, which the insert site just performed. All of this activity should be simplified, wrapped in a transaction, and only performed on changes.

This is just one function, but I imagine there are many more issues related to the language code.

**Comment by Nutomic** [comment]
True this should be optimized. It looks like the problem affects `ApubSite::from_apub` and `ApubCommunity::from_apub`. Other types like post/comment only have a single language value instead of an array, so its simple and straightforward to update. User languages arent federated at all.

`last_refreshed_at` is handled by the activitypub crate, so as long as that function is defined and returns the value, there should be no need to do anything else with it.
