### ISSUE TITLE
Checking for Community Deletion/Removal

### ISSUE THREAD

**Issue by carolynzech** [LemmyNet/lemmy#2858]
What's the policy for when to call `check_community_deleted_or_removed`? I was looking at when `check_community_banned` gets called, and I couldn't figure out why `check_community_deleted_or_removed` was called in some of these places and not others.

The table below shows all the files where `check_community_ban` is called (in `perform`). The file name is bolded if `check_community_deleted_or_removed` is **not** called.

<img width="439" alt="Screenshot 2023-05-12 at 1 01 10 PM" src="https://github.com/LemmyNet/lemmy/assets/71352687/7aa835bd-e07d-4dcc-a18c-449726daac1b">

Thanks!

**Comment by Nutomic** [comment]
This is a very good question. Most likely this is an oversight, its easy to forget a method call when you are trying to hacking a new API, trying to get SQL queries working and so on. Its also easy to miss during reviews. So it would be nice to enforce this through the type system somehow. In the near future we are planning to get rid of the websocket API and use normal HTTP handlers instead of the Perform trait, then maybe we could do these checks via [middleware](https://actix.rs/docs/middleware/).

cc @dessalines

**Comment by carolynzech** [comment]
Thanks, makes sense. I think @dessalines 's idea of calling `check_community_banned` and `check_community_deleted_or_removed` together when you're modifying data makes sense. I also noticed that these functions get called for some mod/admin actions, but not others. For example, the perform trait for `BanFromCommunity` doesn't enforce restrictions on who is getting banned, so I believe it's technically possible for an admin/mod to ban another mod. Since `check_community_banned` isn't called, that banned person can just come back and use their admin/mod permissions to unban themselves. (Probably an edge case, but I could see an admin banning a mod from their community if need be).

**Comment by Nutomic** [comment]
Yes I think it would work to make a single function which checks for both community deletion/removal and ban. Then it might be possible to get rid of the two separate methods. You can also make a pull request for this.
