### ISSUE TITLE
Undetermined language may not exist

### ISSUE THREAD

**Issue by makotech222** [LemmyNet/lemmy#2911]
Hexbear only uses 'English' language as an option, so the several places where lemmy expects there to be a language option of 'Undetermined' in the database may not always be true. This causes foreign key exceptions in the db in a couple places in the codebase.

Example in actor_language.rs:

![image](https://github.com/LemmyNet/lemmy/assets/4389156/9ae06f34-76c8-4ddb-bd18-9119c9fbf7d0)

**Comment by Nutomic** [comment]
The undetermined language is added in db migrations and always exists. If you remove it then there will also be problems with federation, because Mastodon and most other platforms dont have any compatible language tags, so all posts from there will be marked as undetermined. So you need to add the value to your db (with id 0) to fix this.
