### ISSUE TITLE
How to take over a deleted community?

### ISSUE THREAD

**Issue by stephen-hill** [LemmyNet/lemmy#2966]
The community "windowsxp" has been deleted by the original owner:

https://lemmy.ml/c/windowsxp

How do I take over ownership?

**Comment by Nutomic** [comment]
Looks like even admins cant restore it in that case. You can create it under a different name, or use the same name on a different instance.

**Comment by stephen-hill** [comment]
@Nutomic So what happens if a very large community gets deleted by it's ownes? For example https://lemmy.ml/c/technology. Are you saying there is no way to restore it, or let other take control?

**Comment by AidenY69** [comment]
> @Nutomic So what happens if a very large community gets deleted by it's ownes? For example https://lemmy.ml/c/technology. Are you saying there is no way to restore it, or let other take control?

sounds like a big issue

> It is possible to restore communities directly in the database.

There should be a more user intuitive way for admins to go about recovering this. On reddit, it's very common for subreddits to be abandoned or deleted and they have a recovery process

**Comment by dessalines** [comment]
We could allow admins to restore communities on the back and front ends. It'd be a special case, because usually "deletes" are reserved for things you do to your own content, while "remove" is used for what mods / admins do to other peoples items.

**Comment by krestenlaust** [comment]
Shouldn't this be retagged as an enhancement now? Since it's clear that it would be useful to have a feature to restore deleted communities.

**Comment by snowe2010** [comment]
what about a user deleting their community (maybe equivalent to like a users test community) where they don't want the content to be visible anymore. Shouldn't we just allow reuse of the name, rather than a restore of the content? or maybe there's two use cases here. 

1) A rogue mod deletes a whole community, and admins want to restore it. 
2) A mod who created the community just for themselves deletes it and doesn't want the content shown anymore. A different user wants to reuse that community name.

**Comment by AidenY69** [comment]
> * A rogue mod deletes a whole community, and admins want to restore it.

maybe the underlying issue here is who should have the right to delete a community, perhaps it should be by vote of % of the mods? that way test communities only have 1 mod so they can delete the sub, and the normal communities that have rogue mods would still need majority vote to delete

**Comment by JustYourAverageGithubUser** [comment]
As things stand, if a user deletes their account (to my knowledge) the community goes with it. If a community had 1 mod (say it was user created) and hundreds of posts by various people, it seems unfair to delete all those users' posts just because 1 person got sick of their account. It should delete that user and all their posts, but the community should be able to be revived with everyone else's posts intact.
