### ISSUE TITLE
Add "Top Hour" sort

### ISSUE THREAD

**Issue by popcar2** [LemmyNet/lemmy#3049]
- [Y] Did you check to see if this issue already exists?
- [Y] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [N] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [N] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**

Please add a way to sort top posts by one hour. Seems like it would be a relatively easy change and it would improve my experience a lot to be able to see popular *new* posts.

**Comment by JediMaster25** [comment]
I'd prefer top 8 hours.

**Comment by danc4498** [comment]
> I'd prefer top 1, 2, 3, 4, 6, 8, 12 hours, so all factors of 24, and the same for months with factors of 12, so 1, 2, 3, 4, 6. Currently hot is pretty much the same as top hour because posts decay really fast.

Is this sarcasm? You realize top hourly is a sorting in reddit? Also, Hot is currently nothing like top hourly. 

I would like to see the top most upvoted posts from the last hour. Anything longer than an hour does not show up. Unless Hot is buggy right now, it doesn't work even close to this.

**Comment by JediMaster25** [comment]
No, it isn't sarcasm. I agree I shouldn't have said "pretty much the same", it's the closest thing.

**Comment by Profilename1** [comment]
I agree that this would be a useful improvement. The functionality existed on Reddit, and Lemmy doesn't have an equivalent to Reddit's rising sort, which a top of the hour sort would mimic. 3 and 6 hours would also be nice, but maybe not as necessary. The good thing about a top of the X sort is that it's very transparent as to how it works, even to users who aren't tech savvy enough to go poking through the source code to see how the other sorts work.

**Comment by JediMaster25** [comment]
Just don't call it rising please, top hour is clearer.

**Comment by L3v3L** [comment]
I have merged this in, with some luck it should be in the wild on the next release. I know a lot of numbers where thrown around. I made a choice of keeping it to 1hour, 6hour and 12hour. Due to the UI not being ready for so many options (the dropdown would be ridiculous). From what I know, there is someone that started a PR for months but I don't know if and when that would be released. Maybe in the future when people have more time, they can implement the sorting range into the url search query, then you can have whatever value your hearts desire wants.
