### ISSUE TITLE
Add "distinguishment" to submissions

### ISSUE THREAD

**Issue by dollhaus** [LemmyNet/lemmy#3066]
We have the ability to distinguish comments and "speak officially" as moderators with them, but this doesn't yet apply to posts. It would be useful to also have this ability on posts, which would make sticky posts more visible. Take, for example, our sticky post here: https://lemmy.world/post/63645

This post contains more in-depth information than is reasonable to put in the sidebar, but is difficult to make more obvious, despite being pinned. If it were possible to distinguish this post, most themes would also colour the text of the title more prominently in the community feed - ensuring that the post is more likely to be read by newcomers. 

#2002 
#2391

**Comment by Crashdoom** [comment]
> Or mark instance stickies in a different color from community stickies?

I think this is a great idea regardless, as it helps differentiate what is an "admin sticky" / whole-instance sticky vs a community sticky.

But, back on the original issue, I can see where it may be important to distinguish if a sticky is an _official_ post (an announcement by the admin team of the instance / community mods) or simply a post they want to highlight but is not official.

Another way of resolving this might be to support tags or flairs for posts so that could be defined at the community-level, then a flair of "Mod Post", "Admin Announcement", etc. could be used.

**Comment by dessalines** [comment]
We already have both community and local post pinning.
