### ISSUE TITLE
Question: Technical reason for private instance and federation being mutually exclusive?

### ISSUE THREAD

**Issue by Algebro7** [LemmyNet/lemmy#3148]
### Question

I ran into the problem "fixed" by #3074 yesterday and I was curious...why can't private instances federate? Is it a requirement of the federation protocol somehow? And if so, is there a way to work around it?

Use case: I run a single user instance where I don't create any of my own communities but I subscribe to and interact with a variety of communities on other instances. By making my instance non-private, everyone on the Internet can browse to it and see every remote community I've looked at which seems pretty bad for privacy. 

I'm guessing this is a requirement for the federation protocol but I'm wondering if it is actually necessary to disclose the remote communities an instance user has subscribed to. It seems logical that other instances would need to know about the communities on an instance but since these are all remote, I'm not sure why it would need to know about those. Can anyone help me understand this technical aspect of Lemmy?

Thanks!

**Comment by Nutomic** [comment]
Its because Lemmy currently treats all communities and posts as public. So if you had a private instance with federation enabled, the communities could still be accessed over federation. Fixing this would require support for private communities.

**Comment by cooperaj** [comment]
In light of the UK's Online Safety Act (urgh, what a pain) I'd like to propose that this is potentially revisited. 

In order to reduce the risk footprint that I or any other hoster with a UK audience has to document both federation and private instance could work together if the approach was to simply not show any content that wasn't local to the instance when you're not logged in. If you're logged in then you get it all as normal. The legislation only details with what a site surfaces to it's users and gets very muddy when federation becomes involved.
