### ISSUE TITLE
[Bug]: Lemmy returns HTTP Status 200 for HTTP Errors like 404

### ISSUE THREAD

**Issue by Security-Chief-Odo** [LemmyNet/lemmy#3153]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Lemmy web server returns an `HTTP STATUS CODE` of 200, even when the text body specifies `404` or other errors.

Can you please alter it so that lemmy returns the proper, actual `HTTP_STATUS_CODE` to the proxy server, and not report `200` for an error/not found.

HTTP status for a non-existent post ID:
![status_200_404](https://github.com/LemmyNet/lemmy/assets/87156706/49e5d61d-f6ab-4e36-9536-342b905b54b1)

HTTP body response for the non-existent post:
![body_text](https://github.com/LemmyNet/lemmy/assets/87156706/8449fc8f-eaea-4556-9036-03626a3ec2e6)

### Steps to Reproduce

1. In a browser with Developer tools available, go to a non-existent Lemmy URI resource on your instance _(EG: https://beehaw.org/comment/4237112312)_
2. Open developer tools and check the HTTP Status response is a 200 and not the 404 or other status code specified in the HTML body

### Technical Details

Lemmy Logs: Nothing useful
OS: Ubuntu 20.04.6 LTS - Linux 5.4.0-1043
Browser Errors: No; that's the issue. 

### Version

BE 0.17.4

**Comment by David-R-Walker** [comment]
Another example: as I write this, the lemmy.ml (version 18.0) instance is down, returning an "Error!" page with no content for all requests. This should probably be returning an HTTP status code of "500 Internal Server Error" or something more specific, but the HTTP header is still set as "200 OK".

Because of this, various website monitoring tools report the site as up and running with no issues, which is incorrect. If an admin was relying on such a tool to be notified of problems, they would not receive any notification and be none the wiser.

**Comment by EricBAndrews** [comment]
There's also different behavior depending on 2FA status--without 2FA, attempting to load posts using an expired token returns a 400, but using an expired token for an account with 2FA enabled returns a 200 with an empty list of posts.

Ideally there would be unique error codes attached to each failure so that we can (a) serve meaningful and accurate errors to the user and trigger appropriate ux flows (e.g., redirect to re-authentication, notify that the instance is down), but consistent error codes gets 90% of the way there.

**Comment by Nutomic** [comment]
I tested the endpoints `/api/v3/post?{id}` and `/api/v3/comment?{id}`. Both of them return status 404 if the id doesnt exist, both in prod and main branch. However lemmy-ui turns this into an error 500 instead. Please open an issue about this in the lemmy-ui repo if there isnt already. 

@David-R-Walker I cant reproduce this in the latest main branch. If the backend is down, lemmy-ui returns an error page with status 500.

@EricBAndrews Can you open a separate issue with steps to reproduce?
