### ISSUE TITLE
option to mute communities from /all/

### ISSUE THREAD

**Issue by LolsII** [LemmyNet/lemmy#3160]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

/all/ is a very useful tab for exploring the fediverse and finding new communities, and for seeing what the rest of the fediverse is talking about without having my subscriptions overshadowed by the larger communities.

however, its often filled with content from communities that i already know im not interested in. blocking them solves this issue, but bars me from interacting with the community in general which i do not necessarily want- i just dont want to see them on my /all/ page

### Describe the solution you'd like.

an option to bar communities from /all/ without removing the ability to interact with them entirely, either via a complete mute or via a filter on /all/ itself

### Describe alternatives you've considered.

this isnt a very big issue, just a QOL type deal

the block button works alright, and maybe barring posters that arent actually interested in the community topic is good for the health of said community, but i figured id mention it anyway

**Comment by kartikynwa** [comment]
Thinking of ways to do this (muting communities).

- Table structure and API can be identical to that of blocking communities
- Add `hide_muted: Option<bool>` param to PostQuery which defaults to `false` so that posts from muted communities are shown by default
- In post listings for all and local, pass `true` for `hide_muted` so that posts from muted communities are hidden. Can make this a toggle-able option too.
- In CommentQuery I am not sure there is a need to hide comments posted in muted communities

**Comment by kartikynwa** [comment]
Additionally, for PostQuery and CommentQuery, hide_muted should have no effect if community_id or post_id are specified.

**Comment by dessalines** [comment]
Hiding communities from `All`  is already implemented in the back-end, just not in any front end yet.
