### ISSUE TITLE
[Bug]: API does return plain HTML errors

### ISSUE THREAD

**Issue by tbe** [LemmyNet/lemmy#3366]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Currently, if something goes wrong, the API produces non-json errors. It seems like the default error handler is used. 

The error handler should instead respond with a JSON message.

### Steps to Reproduce

1. Trigger an error (Overload, DB down, memory issues, ...)

### Technical Details

-

### Version

0.18.0

**Comment by RocketDerp** [comment]
Simple example, first query returns an empty comment list in JSON format. The second example returns a string "Query deserialize error: unknown variant `Test`, expected one of `All`, `Local`, `Subscribed" that is not wrapped in JSON because "Test" is not a valid "_type" parameter:

```
curl "https://sh.itjust.works/api/v3/comment/list?post_id=372144&limit=300&sort=New&type_=Local"
curl "https://sh.itjust.works/api/v3/comment/list?post_id=372144&limit=300&sort=New&type_=Test"
```

It is also suggested that unique error code value be associated with each JSON error response so that the code path can be quickly identified.

**Comment by RocketDerp** [comment]
From a user-interface side, this is what is happening, the toast messages on the bottom left of the browser window show it can't parse timeouts and doesn't actually show the full message:

![image](https://github.com/LemmyNet/lemmy/assets/113625597/4ed89688-fa68-4133-828c-c34f200f5b2d)

**Comment by Nutomic** [comment]
I tried to fix this but couldnt get it working. It requires setting a default [ErrorHandler](https://docs.rs/actix-web/latest/actix_web/middleware/struct.ErrorHandlers.html).

**Comment by PawanHegde** [comment]
Taking a look at this.
