### ISSUE TITLE
Add report button for posts and comments

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#340]
So that mods can review the reported items and delete them if necessary.

**Comment by dessalines** [comment]
There should be a lot of thinking / discussion into the best way to do mod queues and modmail. I'm of the opinion that the report buttons are just glorified downvotes, and that a simpler way to handle reported items would just be mods alerted to things downvoted past a certain threshold or percentage. My experience modding is having to throw out half the reports you get anyway, as most of them are just false or intended to waste mods time, and also things that don't get reported, that probably should've been. But I'm open to adding a customizable list of reportable offenses too.

But ya, I would say that the order of working on this stuff would pry be messaging, then modmail (IE a quick way to message mods (and a way to mute / stop that chat once its done)), then modqueue.

**Comment by DShiller** [comment]
I would suggest that when a user reports content, it gets hidden from their feed so as to incite users to report. In my experience as a mod, most people don't report and the team has to discover a troll hours later after everyone has.

This could also help prevent frivolous repeated reports; it shouldn't be possible to report the same thing twice.

Otherwise I like the modqueue system on Reddit. Everything gets sent there for review after a report and mods can go through it one item at a time. But yes, many times it's just someone using it to send hate or for something they don't like. If content that was approved by the mods is reported again, the threshold should be higher. It happens that sometimes mods miss something and reapprove when they wouldn't have had they known, but most of the times it's trolls mass reporting something.

Should people banned from a community be able to report content from this community? This is a question to consider.

Also, I should make an issue for this, but seeing new comments is absolutely vital to my moderation. I mean a little +x here:
![image](https://user-images.githubusercontent.com/38543836/87540152-75ff8080-c69f-11ea-9192-6e7709ef8394.png)

Not highlighting which is already done. There could even be an automated system that alerts mods when a post gets a whole lot of new comments. On the subreddit I moderate we get maybe 10-20 comments per post, but sometimes a post gets 200 comments in an hour because it's highly controversial. A system that alerts me when there's ten times the average amount of comments is already half the work done.

**Comment by Nutomic** [comment]
This is implemented in the backend, but still needs to be added to the frontend.

https://github.com/LemmyNet/lemmy-ui/issues/102
