### ISSUE TITLE
Sign a user's posts and comments with a private key that only the user possesses, so that server admins are unable to secretly modify a user's content

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3476]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, as far as I'm aware, (see [this](https://lemmy.world/comment/699637) comment) server admins with direct access to the database of the instance that they are hosting have the power to modify a user's posts, and comments without their consent. This is, of course, a serious security, and censorship issue.

### Describe the solution you'd like.

If a user's posts, and comments were signed with a private key that only the user possesses, then their posts, and comments could be verified to be genuinely theirs, and that they have not been tampered with.

### Describe alternatives you've considered.

This may be a duplicate of #3416.

**Comment by 0xAnansi** [comment]
On top of what @sunaurus mentioned for the ease of use aspect, the fact that the instance owner has full control over the plaintext data stored into the instance would mean that it would be possible to edit the signature to any random key in his possession, or just remove it entirely from the message if it's stored locally.

To implement this and make the instance owner unable to falsify any of the steps, you'd need a third party that would store the signature of each specific message or at the very least the public key of each user, that you'd need to check while reading a comment, to ensure it was not modified, and pretty much reinvent PKI or public key repositories.

Anybody that ever used PGP can acknowledge how painful it is to change your key btw, so if any user loses his key, has a stolen one, or for any reason needs to change it, good luck to him.
Also, for PKI, you just change who you need to trust to ensure integrity of the data, and you'll most likely end up with a cartel similar to the one that ran for decades concerning SSL certificate emissions.

And lastly, you'd need to use a client that is not served by the instance owner, which atm is far from being the norm, because once again, the verification could be just faked anyway by the instance owner.

**Comment by lionirdeadman** [comment]
Another issue that may arise is that editing a user's post might be *good*, here are some moderation examples that I can envision:

- Modifying title to remove editorialized title
- Adding post tags

**Comment by shodanx2** [comment]
This needs to be broken down into smaller steps

For now, user profile page should have an optional  space to publish public keys/certificate and an optional URL text field where those keys can be verified as still valid.

We're talking two plaintext text fields

Next, each comment, post and other types of content that the user can post. need a optional non-UI-intrusive signature field (by non intrusive, I mean, the average user doesn't notice it and doesn't think it's something they HAVE to use to post)

This signature could just be appended at the end of the comment in the database, or kept as a separate text element. 

For now, you leave it to the user to create the signature of their content and to fill in the signature field 

You also leave it to the user to generate his private/public key pair, upload it to his profile and provide an URL for key verification

This alone fulfills this issue's request albeit in a labour intensive way for the user. 

Next step is to automate the process user side. 

As @sunaurus pointed out, the browser's let instance owners code run as root in the virtual machine, so from the user's point of view, nothing on any webserver is trustworthy.

In an ideal world, all this would already be standardized practice and covered by browser open standards before we were facing the "nothing-is-real-AI-apocalypse" staring us in the face right now. 

Since that has not been done, I suggest the automation as follows

A browser add-on for the major browsers for lemmy instances

Keep a private key locally, preferably in a PKCS#11 smartcard, or realistically, a file on their hard drive with permissions set to "please don't read my privates"

When posting to a lemmy instance, the addon captures the posted content and live-updates the cryptographic signature field as the content is edited by the user. The add-on should handle creating of the private/public key pair, storing the private appropriately, and performing the signing of content

**Comment by lionirdeadman** [comment]
If these are text fields on the instance then the instance admin can simply modify them.

Most people will not use such a system unless it is easy to use and I think most people agree that a PGP-like experience would only be usable for nerds.

If we want to build such a system, it needs to be able to share keys like Matrix or Signal offer. Of course, this would require massive amounts of work.

**Comment by shodanx2** [comment]
If the instance owner changes a comment, he can change the signature field but he won't be able to forge a signature that is validated by the user's profile public keys.

He can change the public key on the profile user's page, but that would be obvious, would break the signature on every other content signed by that user too. And the instance owner has no control over the external key verification URL


I agree ordinary users will never , ever use this and on its own is as completely useless as openpgp has always been.

But like I said, this is part of breaking down the problem so that it idoes not become a "massive amounts of work" that will never get done. 

So, for now, one signature string on every piece of user generated content and two string on every user profile, that's all it takes.

Adding 3 text field and 3 strings to the underlying database is not a "massive amounts of work".

**Comment by shodanx2** [comment]
@Nutomic 
Please explain how this is completed ? 
Is the feature documented ? 
Where does the server input his private keys for signing of his posts ?

**Comment by Nutomic** [comment]
It was already explained in previous comments that this wouldnt work.

**Comment by shodanx2** [comment]
@Nutomic, then close a unplanned or wontfix

It should also be disclosed to users that admins and moderators can modify their content without notice and impersonate them

**Comment by dessalines** [comment]
> It should also be disclosed to users that admins and moderators can modify their content without notice and impersonate them

They can add that in the legal section if they like. And adding something like this would be too complicated to work across all browser sessions and app logins, we'd basically have to add matrix-level security, for a platform that is default public.

**Comment by K4LCIFER** [comment]
> we'd basically have to add matrix-level security, for a platform that is default public

I'd argue that the fact that it's public is irrelevant. The main issue is that a user's data can be easily manipulated by admins without anyone being able to confirm if it was actually from that user.

**Comment by Nutomic** [comment]
The same can be said for Reddit, Twitter and other sites. Even if we implemented this feature, only a tiny minority of people would ever use it. We dont have the development resources for that, and need to focus on features that most users will benefit from.

**Comment by shodanx2** [comment]
I mean, if there are not the resources for now, just leave it open, as an aspirational feature.

An audit system isn't something you use every day. 
But it deters tampering just by existing

I think gpg can do all the heavy lifting, maybe https://openpgpjs.org/ ?

It'd be great if the private key stayed on the user's device and maybe they could do the signature and save cycles on the server as well.

Also, this feature would be a jab at reddit since that's exactly the kind of abuse they are known for. 

I think it should be important to beat reddit up at their game using exactly what they are being criticized as leverage to pry users away from them. This would eventually bring more dev resources to Lemmy.

**Comment by dessalines** [comment]
Why can't users just sign their own comments / posts if they like? Then the most an admin could do is delete the comment, because if they tweaked it, you could verify that its incorrect.

You could do all this yourself by the way, instead of asking us to do it for you.
