### ISSUE TITLE
Proposal: rework voting system

### ISSUE THREAD

**Issue by TwilightLurker** [LemmyNet/lemmy#3511]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Full post and comment vote data is available to all admins of all instances federated with the original instance. [Discussion on lemmy.world](https://lemm.ee/post/662447). This is a problem, as there is nothing preventing a potential malicious actor from setting up an instance to build individual user profiles based on this data, straight up publish it, or more.

### Describe the solution you'd like.

The voting system should be reworked.

Example implementation (I am not familiar with the internals of Lemmy or ActivityPub, and am not sure whether this is even possible to implement):
- Server stores a list of all local votes, together with the users (just like it does now). For remote votes, only the total vote counts on each instance are stored (e.g. `instance | up: int | down: int`).
- Server only publishes the numbers of local votes, without user information.

This would solve the privacy issue, and still allow to easily remove votes from malicious instances.

### Describe alternatives you've considered.

Any other similar or distinct implementation would suffice, as long as it accomplishes the main goal.

**Comment by iopq** [comment]
Then nobody can prevent a malicious server inflation vote stats by sending bogus numbers. At least now you can CHECK that the user in question did not vote on a post by asking the user. If it's just "1000 users upvoted this post" you can't possibly ask every user if they did that

**Comment by Mutant** [comment]
As I understand it, there are two scenarios for vote count count abuse:

1. A post is made on a community hosted on a legitimate server. A malicious server sends 1000's of fraudulent upvotes (or downvotes) from its users on that post 
2. A post is made on a community hosted on a malicious server. The malicious server fraudulently creates votes from users on other servers for this post (which I believe is the scenario @iopq is talking about)

Either scenario is currently possible. In the first scenario, there's no way of anyone actually checking, since the users are not real, so sending vote counts makes no difference.

In the second scenario, if a move to vote counts was made, admins could still potentially have access to which local users voted on a post, so could still verify if people were actually upvoting it. The malicious server would be getting told how many votes other servers had made, it would just be lying about the total votes.

In reality, what would actually happen in either scenario (with or without the change to vote counts) is that admins on legitimate servers would notice strange activity and defederate from the malicious server. Perhaps having more information on the list of users who voted would make this decision easier, but on balance I think the privacy improvements of moving to vote counts are worthwhile.

**Comment by Nutomic** [comment]
We dont have any plans to rework the voting system.
