### ISSUE TITLE
Move expensive DB triggers to scheduled jobs.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3528]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The next best performance improvement, can come from going through every table trigger, seeing anything that's more complicated than a simple increment / decrement (especially those that require functions), and moving them to periodic scheduled tasks. 

These are a performance concern because all SQL triggers are synchronous. 

Things like community, site and person aggregates, comment counts, user counts, etc do not need to be immediately live.

Context #3188 

### Steps to Reproduce

See above

### Technical Details

See above

### Version

main

### Lemmy Instance URL

main

**Comment by phiresky** [comment]
I would intuitively say that most of the reason for the slow response is not the triggers but rather the inline acrivity sending #3493. The reason is that the database update lock only single rows and are thus perfectly serializable. Basically your vote only has to wait for other votes on the same exact post/comment, so if the vote count changes by 2 when you press the button it only had to wait for one other vote that each should take less than 10ms to process for the database.

I don't have good numbers though so I might be wrong. You can track these timings by enabling the pg_stat_statements.track='all' option.

**Comment by phiresky** [comment]
My suggestion would be as follows:

1. Replace all expensive triggers with simple ones where possible. There's some triggers (e.g. `person_aggregates_comment_count`) that do aggregating queries where I'm not sure why and it seems like they should be able to do it with a simple inc/decrement instead. O(1) triggers should be fine imo.
2. For all other triggers, if any remain, instead of directly updating they should set a `dirty: boolean` flag on the target row. There should be an index on `WHERE dirty` for those tables, which are then updated in a scheduled task.

**Comment by RocketDerp** [comment]
> 2\. For all other triggers, if any remain, instead of directly updating they should set a `dirty: boolean` flag on the target row. There should be an index on `WHERE dirty` for those tables, which are then updated in a scheduled task.

Comments are going to be huge in major social event situations. It is one massive table for the entire site. Doing updates on such a table can be expensive. An alternate is to focus on the timestamp fields of updated/published - almost all activity on a Reddit-like site is concentrated on recent data. And the need for the freshest comments/post can often be organized based on edit timestamp.

I would also point out that the use of two entire fields for deleted and removed could be consolidated into a flag with multiple meanings. Right now, WHERE clauses have to include conditions for both, when a smallint, optimized enum, or character could hold values such as: a = open, d = deleted, r = removed, e = deleted + removed, f = spam filtered pending analysis. I think there is also opportunity to optimize local flag and replace it with just an instance_id value (and always assume instance_id = 1 is local). There are some other performance issues regarding these triggers too... comments table lacks denormalization of 1) community that owns the comment, 3) instance that either how of the community or originated the comment, 3) user who owns the comment. JOIN is often done by post to find community and owner. Well, ap_id can be parsed, and I have actually found PostgreSQL to be performant doing it - to get the instance of the comment creator (but not home of the community / replication source).

There are also issues lurking with accumulation of data. Moving to a batch processing system might want to consider that some instance operators may only wish to retain 60 days of fresh content vs. having every single history of content for a community for search engines and local-searching. The difference in performance is huge, which is why popular Lemmy servers have been crashing constantly - the amount of data in the tables entirely changes the performance characteristics. [continued...](https://lemmy.ml/post/2466727)

**Comment by dessalines** [comment]
@phiresky nice work, shouldn't be too bad to work from that table to fix the triggers. *Hopefully* 🤞 we already have unit tests to make sure those aggregates are the correct values, but if there aren't, they should be added as part of a PR to fix the triggers.

**Comment by RocketDerp** [comment]
A proposed consolidated trigger that tackles head-on the performance issues of Lemmy API delete of a post, delete of an account, etc: https://github.com/LemmyNet/lemmy/pull/3727

**Comment by phiresky** [comment]
Here's an updated table after 0.18.3. The only remaining expensive trigger is community_aggregates_post_count, which is not expensive on INSERT, but is expensive on restore and delete.

| trigger source     | trigger name                          | trigger target tables | run time                                                                   |
| ------------------ | ------------------------------------- | --------------------- | -------------------------------------------------------------------------- |
| comment            | comment_aggregates_comment            | comment_aggregates    | :heavy_check_mark: constant, no fetches                                    |
| comment            | community_aggregates_comment_count    | community_aggregates  | :heavy_check_mark: fixed in 0.18.3 (#3739)                                 |
| comment            | person_aggregates_comment_count       | person_aggregates     | :heavy_check_mark: fixed in 0.18.3 (#3739)                                 |
| comment            | post_aggregates_comment_count         | post_aggregates       | :heavy_check_mark: constant, fetches relevant post                         |
| comment            | site_aggregates_comment_delete        | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| comment            | site_aggregates_comment_insert        | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| comment_like       | comment_aggregates_score              | comment_aggregates    | :heavy_check_mark: constant, fetches comment                               |
| comment_like       | person_aggregates_comment_score       | person_aggregates     | :heavy_check_mark: constant, fetches comment                               |
| community          | community_aggregates_community        | community_aggregates  | :heavy_check_mark: constant, no fetches                                    |
| community          | site_aggregates_community_delete      | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| community          | site_aggregates_community_insert      | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| community_follower | community_aggregates_subscriber_count | community_aggregates  | :heavy_check_mark: constant, no fetches                                    |
| person             | person_aggregates_person              | person_aggregates     | :heavy_check_mark: constant, no fetches                                    |
| person             | site_aggregates_person_delete         | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| person             | site_aggregates_person_insert         | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| post               | community_aggregates_post_count       | community_aggregates  | :x: O(n): fetches all comments and posts in the community                  |
| post               | person_aggregates_post_count          | person_aggregates     | :heavy_check_mark: fixed in 0.18.3 (#3739) |
| post               | post_aggregates_featured_community    | post_aggregates       | :heavy_check_mark: constant, no fetches                                    |
| post               | post_aggregates_featured_local        | post_aggregates       | :heavy_check_mark: constant, no fetches                                    |
| post               | post_aggregates_post                  | post_aggregates       | :heavy_check_mark: constant, no fetches                                    |
| post               | site_aggregates_post_delete           | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| post               | site_aggregates_post_insert           | site_aggregates       | :heavy_check_mark: fixed in 0.18.3 (#3732)                                 |
| post_like          | person_aggregates_post_score          | person_aggregates     | :heavy_check_mark: constant, fetches post                                  |
| post_like          | post_aggregates_score                 | post_aggregates       | :heavy_check_mark: constant, fetches post                                  |
| site               | site_aggregates_site                  | site_aggregates       | :heavy_check_mark: constant, no fetches                                    |

IMO all triggers on the same table could be merged. That way it should be easier to get rid of those O(n) triggers. I don't think any scheduled tasks are actually necessary.

**Comment by dessalines** [comment]
These are completed now, and also the triggers moved to a startup replaceable schema.
