### ISSUE TITLE
Community category

### ISSUE THREAD

**Issue by knrodriguez** [LemmyNet/lemmy#3564]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When looking for communities by keyword, the results are communities that have the keyword in the community name. For example, when searching for "technology" the results are as shown below:
![Screenshot_20230709_114110_Brave](https://github.com/LemmyNet/lemmy/assets/18505368/ef59ab66-6964-47d8-9b4f-5f0de80d97d5)

But if I search using the keyword "tech", I get this list of communities with some not showing up in the previous search. 
![Screenshot_20230709_115247_Brave](https://github.com/LemmyNet/lemmy/assets/18505368/79200df3-a130-4ce1-a711-8ea01112d075)

This shows that there are communities that are technology related/focused without have the word "technology" in the name.

### Describe the solution you'd like.

It would be lovely when searching to be able to select a category and see all communities that are related to that category. The idea is that upon creation, the community creator can set one or multiple categories that they feel the community is related to. 

### Describe alternatives you've considered.

I tried using community browsers like [Lemmy Explorer](https://lemmyverse.net/communities) and [Lemmy Community-Browser] and while Explorer does better at finding communities that are closely related to the keyword, but some are still off the mark.

**Comment by M4rtineski** [comment]
It's so weird to see you own community in the github issue. I'm talking about the singularity one.

And about the idea, I feel like it's needed because when you search for something specific there's a lot of irrevelant communities that are not even related to what you're looking for.

**Comment by lionirdeadman** [comment]
I'm not sure categories in search really make sense since it'll no doubt be incredibly limited - I think people making their own categories using their subscriptions would make more sense though that is probably pretty expensive.

**Comment by knrodriguez** [comment]
I understand how the initial proposal can feel limiting. By have one list that is user created, there is the potential concerns of user input/error: misspelling the keyword or using various punctuation/capitalization. 

Maybe there can be a high level category be an approved set of names that can be updated at some frequency, and then subcategories, which can be created by community owners and mods?

**Comment by Fmstrat** [comment]
The other advantage this offers is when browsing your feed. Being able to select a category like "technology" would be nice.

Community tagging with a preset list of tags might be better, since a community could belong to more than one, like "technology" and "humor".

To keep things standardized, Wikipedia's top-level content categories could be used: https://en.m.wikipedia.org/wiki/Wikipedia:Contents/Categories

**Comment by dessalines** [comment]
I added this like 4 years ago, but we removed it after it turned out that my hardcoded list of community categories didn't play well with internationalization, and they weren't editable either.

This specific issue is mostly fixed by #5044 

Outside of that, I'd rather leave this to tagging, #2675 , which would be more customizeable and flexible.
