### ISSUE TITLE
different file types

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#3630]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

allow for .mp3 .ogg etc. uploads

### Describe the solution you'd like.

uploading audio files

### Describe alternatives you've considered.

n/a

### Additional context

n/a

**Comment by M4rtineski** [comment]
I can see it being useful in many situations. Starting from uplading music on music sharing sublemmies to including an ai generated text to speech for accessibility. When talking about the accessibility I don't mean the blind people but people that don't have the time to look at the screen because they are busy doing something, people that don't like to read or people that have ADHD which makes it harder to read longer texts. Overall I see it as a very important feature that I would like to get implemented soon.

**Comment by RustoMCSpit** [comment]
if audio is included, 2x and 3x speed options would be great

**Comment by M4rtineski** [comment]
@RustoMCSpit I think that smaller jumps before 2x would be good too, stuuf like 1.25x 1.5x and 0.75x.

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit I think that smaller jumps before 2x would be good too, stuff like 1.25x 1.5x and 0.75x.

or just have a slider where you can hit speed it to whatever

**Comment by M4rtineski** [comment]
@RustoMCSpit Thought the same but they couldn't do that with top sorting options for posts so I assumed that it will be hard to do it in this case too. I'm probably wrong because in this case it's a much smaller scale of the feature. :x

**Comment by RustoMCSpit** [comment]
was thinking, servers should be able to only allow certain file types / sizes. lossless audio can get nuts in size

**Comment by dessalines** [comment]
No, lemmy won't store files, because that would explode server's hosting costs. We do support links, including torrent links, which is the best way to share large media.
