### ISSUE TITLE
Opt-in remote security takedown feature 

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#3638]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

hacking?

### Describe the solution you'd like.

Pitch
Jerboa should have an opt-in feature for servers that lets them be temporarily taken down remotely for their own safety by the Jerboa non-profit in case of an extreme security vulnerability requiring an update

Motivation
This would protect the servers of those who opt-in along with the users on that server. As it is an opt-in, no one will be left annoyed. All users who join the server alongside the owner would be aware of a potential takedown at any moment and would know of its importance and how it is solely for their safety. Servers can freely opt-in or out.

### Describe alternatives you've considered.

sending out a please update notice?

### Additional context

mastodon got lucky that mozilla paid pentesters who reported it and it got patched before it coukd be exploited, lemmy migjt not be so fortjnate

**Comment by Hashfastr** [comment]
I doubt Lemmy is willing to put a backdoor into the code. Even if opt-in, it's still in the code. This is stupid and goes against all security concepts.

**Comment by 0xAnansi** [comment]
In my opinion this should not be part of the software stack for security reasons. A software backdoor is an anti-feature.

If you want a kill switch, you can just have a .sh/.bat/.ps that sends a shutdown command to your server through SSH or something.

**Comment by RustoMCSpit** [comment]
> I doubt Lemmy is willing to put a backdoor into the code. Even if opt-in, it's still in the code. This is stupid and goes against all security concepts.

i mean, the only thing the code can do is take the server offline and when it does everyone will be alerred

**Comment by austinchaet** [comment]
Adding this to Lemmy would just increase the attack surface - one bug in check for opt-in and someone could have a kill-switch for the whole network.

If you wanted this to work (and I'm split on if this is a good idea), 0xAnansi is right that it's better to use existing, far more heavily vetted means.

I like [https://github.com/mrash/fwknop](fwknop) for applications like this.  Properly configured, this is a nice way to give someone a key to shut down a server without letting them inside or advertising the fact that this is even possible.

> SPA requires only a single packet which is encrypted, non-replayable, and authenticated via an HMAC in order to communicate desired access to a service that is hidden behind a firewall in a default-drop filtering stance. The main application of SPA is to use a firewall to drop all attempts to connect to services such as SSH in order to make the exploitation of vulnerabilities (both 0-day and unpatched code) more difficult. Because there are no open ports, any service that is concealed by SPA naturally cannot be scanned for with Nmap.


Using a single authenticated packet to an arbitrary port, you can set it up to run a preset script - anything from changing the firewall rules to allow ssh (normal use case) to running a preset script.  

In this case, we'd want a script to send out an email alert to the admins, run a command to tell Lemmy to shut down, and if you wanted you could even throw up a basic webserver to tell clients what's going on.


The other advantage is that this isn't just opt-in  There's basically no way to tell if a server decided to add it without insider knowledge, and it gives control only to do one specific thing.  Individual admins would be in control of what the button does and who they give it to, and they could even set up the shut-down to rotate keys and reactivate it from their phone if they think it was done maliciously.  

It's been a while since I've used it, but we had it audited about a decade ago and cleared it for use in a life-or-death application. 


Anyways, if you want to look at something like this I can help, it wouldn't (and probably shouldn't) be a part of the Lemmy system itself.

**Comment by RustoMCSpit** [comment]
> 

 'and someone could have a kill-switch for the whole network.'
if it's misused a person could just opt out and it would be temporary misconvenience at best
