### ISSUE TITLE
[Bug?]: Comment with "path": "0"

### ISSUE THREAD

**Issue by leinardi** [LemmyNet/lemmy#3741]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I think this is a bug because I never encountered so far a comment with `"path": "0"` (usually it is `"path": "0.<some comment ids>`").

The comment in question is the `2042764`: https://lemmy.ml/api/v3/comment/list?type_=All&sort=Hot&max_depth=8&post_id=2507287

So far I just assumed that all the comment's paths start with `0.`, is this a wrong assumption? If yes, in which case can a comment have `"path": "0"`?

### Steps to Reproduce

1. https://lemmy.ml/api/v3/comment/list?type_=All&sort=Hot&max_depth=8&post_id=2507287

### Technical Details

This is messing also with Jerboa comment indentation:
![image](https://github.com/LemmyNet/lemmy/assets/273338/efac759a-3d34-4486-b9c6-dab99570ab70)

### Version

BE: 0.18.2

### Lemmy Instance URL

lemmy.ml

**Comment by RocketDerp** [comment]
Pretty weird. https://lemmy.ml/comment/2042764

I queried my own instance database and found only one like this, a different comment from lemmy.world. I also suspect if someone replies to the path will be over-written. No idea how it got set this way in the first place, maybe a reply was made and reply deleted or some similar interaction?

**Comment by RocketDerp** [comment]
So I've been examining the path content in production database... and this SQL query yields some interesting results:

```
SELECT id, child_count, published
FROM comment_aggregates
WHERE child_count > 200
ORDER BY published DESC
LIMIT 1200
```

I'm finding comments that have a child_count in the hundreds, but the post the comment on only has a dozen comments on it.  It's pretty rare in Lemmy where code resorts to raw SQL, but I think there might be a runaway UPDATE that is hitting on comments outside the context... the discover of 0. in the wild is pretty suspect.  https://github.com/LemmyNet/lemmy/blob/66ac8100d98d721136205ed0de2a1d7abb1e0d1d/crates/db_schema/src/impls/comment.rs#L108

**Comment by Nutomic** [comment]
There are many such comments on lemmy.ml so its a real problem:
```
# select published,ap_id from comment where path = '0';a
published          |                                ap_id
----------------------------+---------------------------------------------------------------------
2023-09-13 01:27:30.763465 | https://lemmy.world/comment/3381305
2023-09-13 01:24:33        | https://kbin.social/m/asklemmy@lemmy.ml/t/449990/-/comment/2311752
2023-09-13 01:28:08.412503 | https://lemmy.world/comment/3381314
2023-09-13 01:27:38.410618 | https://lemmy.world/comment/3381308
2023-09-13 01:26:31.212679 | https://lemmy.ml/comment/3759291
2023-09-13 01:25:04.067039 | https://mander.xyz/comment/3120030
2023-09-13 01:28:36.419702 | https://lemmy.nz/comment/2407476
2023-06-12 00:12:19.588546 | https://lemmy.world/comment/77418
2023-06-12 00:33:45.381428 | https://sh.itjust.works/comment/66325
2023-09-13 01:27:31.430649 | https://lemmy.ml/comment/3759315
```

My guess is that this happens because `path` is not written in the comment insert query, but in a separate update query afterwards. If the db connection fails during that update, the comment stays with the default path which is `0`. Maybe the solution is to calculate the path in a db trigger and not in Rust. Somehow lemmy-ui is still able to insert such comments at the right point in the tree, not sure how.

https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/impls/comment.rs#L84

**Comment by Nutomic** [comment]
This same bug is also causing random CI failures, eg [here](https://woodpecker.join-lemmy.org/repos/129/pipeline/4410/21#L350) (the previous one in line 347 is expected as part of the test). Im not familiar with the way comment paths work, but a path of `0` should probably never exist, right?

I think we either need to wrap these [three separate queries for comment create](https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/impls/comment.rs#L63C1-L118) in a transaction, or otherwise rewrite it to use db triggers like the comment mentions.

cc @dessalines @phiresky @dullbananas

**Comment by dessalines** [comment]
I'll see if I can do this in a transaction.
