### ISSUE TITLE
Allow posts to have both an image and a different link

### ISSUE THREAD

**Issue by YousufSSyed** [LemmyNet/lemmy#3747]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

No.

### Describe the solution you'd like.

Lemmy has boxes for both an image and a link for the post. If I try to put in a link different from the photo, it will fetch a photo from the link instead. I'd like both so that I can make a post relating to both the image and the link I post.

### Describe alternatives you've considered.

Putting the link in the post body, but I'd prefer to have the link right on the post.

**Comment by lionirdeadman** [comment]
The issue, at the very least with my understanding is that there is no connection between a post and the image uploaded other than the link field. So, we would need another column in the database to handle this usecase, I believe. And this new database column would need to become the source of the thumbnail rather than the link.

That said, I'm not a Lemmy developer so it's possible I'm wrong.

**Comment by Nutomic** [comment]
You can put one of them in the post body.
