### ISSUE TITLE
Subscribe/follow individual users

### ISSUE THREAD

**Issue by jm355** [LemmyNet/lemmy#3792]
I think being able to subscribe to or follow a user the same way you can subscribe to a community would be a huge improvement. Primarily this would let people follow other lemmy users, but following users from other services like mastodon would be cool too

**Comment by slrgt** [comment]
i would love this. the fediverse is so powerful because of compatibility with other services so this would help a ton

**Comment by Nutomic** [comment]
You can follow Lemmy users from platforms like Mastodon or Kbin. No need to reimplement that functionality in Lemmy.

**Comment by tgxn** [comment]
I agree it would be nice to have a third feed filter option for "followed users" - I want to follow the content they post on Lemmy.

**Comment by jeremiah-miller** [comment]
https://github.com/LemmyNet/lemmy/issues/3906#issuecomment-1715985525 I don't understand what @informapirata is saying here. How would not being able to follow users keep the db contained? Is there a reason the load would be more than it would be if you followed a community?

**Comment by informapirata** [comment]
> [#3906 (comment)](https://github.com/LemmyNet/lemmy/issues/3906#issuecomment-1715985525) I don't understand what @informapirata is saying here. How would not being able to follow users keep the db contained? Is there a reason the load would be more than it would be if you followed a community?

following only communities means that you are not forced to carry within your instance database the contacts of an indiscriminate number of users, their images and videos, their threads and the contents of all the users they follow and reshare.
This is the reason why a mastodon instance with around twenty hyper-connected users takes up more disk space and more resources than a Lemmy instance with 500 users following around thirty communities each

**Comment by jeremiah-miller** [comment]
Wouldn't the db only need to contain a list of communities followed and users followed, and let the client dynamically load user and community posts? (Partially trying to make a point, mainly just don't know what's going on behind the scenes). Also, isn't pleroma much lighter than mastodon? Maybe lemmy could do it the way pleroma does it?

**Comment by jeremiah-miller** [comment]
Another option: every user could essentially have a unique auto-generated "community" of all their posts that other people could subscribe to but not post to. The only problem would be you might get duplicate posts if you follow person X and community Y, and person X posts to community Y, you'd get a duplicate in your feed. That seems like it should be solveable though, or just the cost of doing business following users

**Comment by informapirata** [comment]
> Wouldn't the db only need to contain a list of communities followed and users followed, and let the client dynamically load user and community posts? (Partially trying to make a point, mainly just don't know what's going on behind the scenes). Also, isn't pleroma much lighter than mastodon? Maybe lemmy could do it the way pleroma does it?

There is no need to confuse two very distinct levels: on the one hand there is the software architecture that underlies the management, on the other there is the actual operation which mainly concerns the number of users present within the platform and how connected these users are to other instances of the Fediverse.
The lightness of a software like Pleroma is irrelevant when within it there are many users connected with many different instances of the fediverse.
I'll just give you some examples.
The Lemmy instance that I administer (feddit.it) has 1500 users of which almost 200 active users in the last month and takes up fewer resources and less disk space than the other mastodon user that I administer (poliversity.it) which has less than 150 users of which only about forty are active. The third instance that I administer, based on Friendica (poliverso.org), finally occupies more than double the disk space and has double the computing power with only 474 total users of which 111 are active in the last month (and is perpetually in trouble ).

**Comment by jeremiah-miller** [comment]
hmm, what makes a user count as "active"? Is there a way to compare their server impact more directly, such as how often they post and what kind of content they post? I guess in my mind I'm imagining the 40 mastodon users could be doing more resource heavy things than the 200 lemmy users.

Also, if pleroma can do the same things as mastodon with less resources per equivalent user, surely that would imply that lemmy could do one thing mastodon does (follow users) with less resources per equivalent user as well? This is also based on my shaky guess that most lemmy users will primarily follow communities, and only follow a handful of users whose posts they really like

**Comment by informapirata** [comment]
> hmm, what makes a user count as "active"? Is there a way to compare their server impact more directly, such as how often they post and what kind of content they post? I guess in my mind I'm imagining the 40 mastodon users could be doing more resource heavy things than the 200 lemmy users.

For the software on which ActivityPub projects are based, the active user is the one who logged in in the last month. it tends to be a user who statistically publishes more content and follows more users

> Also, if pleroma can do the same things as mastodon with less resources per equivalent user, surely that would imply that lemmy could do one thing mastodon does (follow users) with less resources per equivalent user as well? This is also based on my shaky guess that most lemmy users will primarily follow communities, and only follow a handful of users whose posts they really like

The user who uses Lemmy is a user who only wants to follow communities and not users. Historically he is a user who comes from the experience of Reddit and that of forums.

The user who uses the Lemmy communities to follow a topic, comment on threads or open a new thread can also do so very well from Friendica or (a little less well, but still well) from Mastodon, Pleroma and some week also at Misskey.

Those who also want to follow users but like that type of interface can use Kbin, but for this very reason Kbin requires resources which, as users grow, grow disproportionately compared to Lemmy.

The question to ask is therefore whether it is worth distorting an excellent and fluid product like Lemmy, to satisfy a public that 90% of them already use Mastodon and who would never abandon it if not for a more powerful product, like Friendica, or for one that is more aesthetically appealing, like Misskey.

And the answer is clearly "no"

**Comment by mitexleo** [comment]
+1

**Comment by BettyJJ** [comment]
I see many issues closed as "completed" but are not completed at all. Maybe the devs need a new tag "won't fix".

**Comment by dilroopg** [comment]
I follow users on reddit, so do many others, its useful, like any other platform some power user most more content worth looking at then others and you find them over time

**Comment by slrgt** [comment]
this is especially useful as more services start federating like Pixelfed, etc. PieFed allows following users and it would be great for Lemmy to also have this feature. it being available on other platforms doesn't make it not needed on this platform that we prefer to use.

Please reopen the issue @dessalines @Nutomic

**Comment by dessalines** [comment]
I'll re-open if someone wants to work on this, and I'll assign it to them. It would be a monumental amount of work tho, as lemmy is not set up for following users.

**Comment by informapirata** [comment]
There is really no need to reopen this issue!

> this is especially useful as more services start federating like Pixelfed, etc.

Federation has nothing to do with it! Lemmy is already federated beautifully with the rest of the Fediverse, but it is important to remember that Lemmy **is not a social network network**!

**LEMMY
IS
NOT
A
SOCIAL
NETWORK!**

Lemmy is a **link aggregator**, a **"forum" platform**, a **thread manager**. It has some social features, just like Reddit or Discourse have social features, but it is not a social network.

Social networks are used to create networks **between users**. Thread managers are used to allow users to follow only the content that interests them.

Following another user is useless if you are interested in thematic content (communities are nothing more than a way to simulate Reddit's "subreddits" or Forum "categories"). Do you want to follow other users? **Use a social network software**. Mastodon sucks and you can't follow topics? You're right, but you can use Friendica which allows you to manage Activitypub groups to an acceptable level and is a real social network.

But Lemmy is for those who want to follow "categories" (=community) and "topics" (=thread)

Finally, remember that the Fediverse social networks, i.e. the Fediverse software that allows you to follow other users, are subject to system overloads. All it takes is for a user to start following all the profiles in the world and his instance would receive so many inputs that it would collapse! The fact that on Lemmy you can only follow communities is the greatest guarantee of stability and resilience (and it is the greatest fortune for administrators who are not forced to buy bigger disks and more powerful CPUs!).

Although there are aspects [regarding the visibility of posts on Mastodon](https://github.com/LemmyNet/lemmy/issues/5300) that could be solved in a way if only the pride of @dessalines and @Nutomic were not the size of a continental plate...

> PieFed allows following users and it would be great for Lemmy to also have this feature

No. Piefed does not allow following users. If you see a "follow" button in the Piefed window, that is just a little button that makes it easier for **social network** users (Mastodon, Pleroma, etc) to follow a Piefed user.

![Image](https://github.com/user-attachments/assets/a34e8d3b-be82-44bc-8a92-f9f815fac582)

The only "link aggregator" that allows you to follow other users is Kbin/Mbin. A totally unfortunate choice!

I am sure that, if the very good developer who created it had avoided inserting this feature, the Kbin instance would not have collapsed on itself due to the DB going crazy in front of all the connections it had to manage and its developer would not have entered burnout as then happened.

**Comment by jm355** [comment]
When you open a users profile in lemmy, you can see all their posts and comments. Maybe lemmy could automatically generate a read-only community that's a list of all of the posts of a user, and a read-only community that's all their comments. Then, if you want to "follow" a lemmy user, you're really just subscribing to the "community" that only has all that users posts

In other words, the request is to aggregate the links that one user has posted across communities

**Comment by teohhanhui** [comment]
> Following another user is useless if you are interested in thematic content (communities are nothing more than a way to simulate Reddit's "subreddits" or Forum "categories").

Why is it so surprising that some people want to follow a community that consists of a single user? It works perfectly fine for Reddit.

**Comment by informapirata** [comment]
> Why is it so surprising that some people want to follow a community that consists of a single user? It works perfectly fine for Reddit.

They follow the community because that user uses it as if it were their own blog. **There is no contradiction.**
And anyway - how beautiful is the fediverse! - those who are subject to fetishism towards a user can always subscribe to his RSS feed!

**Comment by jm355** [comment]
Hmmm if there's an rss feed, maybe there could be an option to follow an rss feed as a community? Or perhaps that's a feature request for lemmy clients? It would be much nicer if it was integrated though

**Comment by SpiderUnderUrBed** [comment]
@Nutomic If someone were to work on a PR to implement this feature, would you consider adding it? Curious.

**Comment by dessalines** [comment]
That's RSS feeds for users, which we already have.

**Comment by slrgt** [comment]
Ok i guess other than basic possibility its gonns be technically possible in Lemmy but theyre wont be actual ui ux for basic user or person who is working class to understand.

Some software projects have certain abilities only available to tech/linux class that understands how to do things technically

PieFed seems committed to end users who are more noobs like me who use tech but mainly as tool for working on art or learning online. Lemmy userbase is highly technical and much more advanced than they realize.

Personally mostly trying to keep up with the highly technical people on lemmy usually but piefed seems to be easier for us elderly folk and not so good at tech folks

**Comment by Nutomic** [comment]
Following users will not be possible with Lemmy, because it is focused on the specific use case of communities (or forums). Lemmy is good for noobs, you dont need to be a nerd to use it. If you want to follow users there are many other platforms for that purpose, eg Mbin, Mastodon, etc.

**Comment by vaartis** [comment]
> And how do you plan to implement it? Lemmy doesnt support any posts outside a community, or comments outside a post. So most content from Mastodon couldnt be inserted in the database at all, or it would require a major rewrite of the core logic.

Why not create a per-user community analogous to what reddit has automatically? They could be filtered out from the normal list of communities, since they will all be automatically created and marked as "community of this user".

It could be their own blog they post to, and (if lemmy supports Announce activities) it could Announce the posts they make in other communities.

Then for any user outside of lemmy, such a community could be created automatically as well, and their posts placed there.

**Comment by Nutomic** [comment]
So you already found the solution, create a community with the same name. No need to do that by default for such a niche feature.
