### ISSUE TITLE
Add the ability to view an edit history for posts

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3803]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, you are only able to see when a post was edited, but not what was actually changed. This poses an issue for potential abuse -- a user could post, or comment something, gather a lot of engagement, and input, and then subsequently edit their post to completely change its original meaning, or nullify all existing comments. This has potential to severely diminish the trust in sensitive discussions, and devalues content on the whole.

### Describe the solution you'd like.

I propose that Lemmy should sync an edit history showing what changes between edits, and when. Then, it would of course be up to UI developers to visualize this data in some way. 

### Describe alternatives you've considered.

None.

### Additional context

This issue somewhat already exists in #580, but I don't think that suggestion was fully fleshed out. I should also say that the user will still have the ability to delete their post. If they delete the post, everything is deleted, and thus would be unviewable. But if the user keeps their post up, the edits should always be viewable. This may also require a change to the ActivityPub protocol, but I am not sure of that.

**Comment by veloxy** [comment]
How often is that a problem that it needs this kind of solution? What if someone accidentally posts credentials of something, they'd be forced to delete the whole comment/post. 

If anything, display an asterisk/exclamation mark or something on the comment with a tooltip that says the post/comment has changed since the comment was made. 
Not sure how everything works behind the scenes but there could be a hash for the contents of the post/comment, when a comment is made it could store the hash of the comment that was responded to. When editing the comment the hash would be recalculated, when hash of the response isn't the same as the comment/post it responded to, it could display the asterisk/exclamation mark.

**Comment by K4LCIFER** [comment]
> How often is that a problem that it needs this kind of solution?

From my experience, constantly, and consistently.

> What if someone accidentally posts credentials of something, they'd be forced to delete the whole comment/post.

Someone's poorly thought out input of data should not dictate the direction of UX.

> If anything, display an asterisk/exclamation mark or something on the comment with a tooltip that says the post/comment has changed since the comment was made.

This already exists in the Lemmy UI; however, as is evident by the existance of this post, simply indicating that a post has changed is borderline useless.

**Comment by Nutomic** [comment]
That means we would have to store all this extra data, and return it through the API in some way. Lots of complexity for negligible benefit. Not worth it.

**Comment by K4LCIFER** [comment]
> Lots of complexity for negligible benefit

Hm, this is a rather opinionated, rather than factual, statement. I think the benefit would actually be quite substantial.
