### ISSUE TITLE
Question: Should Crossposting be handled differently?

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#3827]
### Question

Currently, crossposting works in a way that I find unintuitive.

 If you make a post in a community that has the same URL as a post in another community, it will be marked as a crosspost regardless of whether the user clicked the crosspost button. This can be seen [here](https://lemmygrad.ml/post/1162492).

Likewise, if you crosspost a post that doesn't have a URL, it will not be marked as a crosspost. Compare this [lemmygrad post](https://lemmygrad.ml/post/1161815) that I crossposted [from lemmy.ml](https://lemmy.ml/post/2671212).

Is this an intentional decision on the maintainers' part, or is this a bug? If it is a deliberate decision, should it be changed anyway?

**Comment by dessalines** [comment]
The post URL is the "link" that connects cross-posts, not the lemmy ids. There's probably different ways to link posts besides their URL, but I'm not sure what that'd be.

The bonus of that is that news articles, images, everything can be properly connected, regardless of place or time.

The negative is that text-posts without URLs don't appear as cross-posts.

**Comment by maegul** [comment]
From a user's perspective:

* The automatic cross-post connection based on URL is a cool and nice feature (I would have requested it if I hadn't worked out that it happens automatically)
* The lack of a connection for a manual cross-post is both unintuitive and probably rather desirable.
    * For example, I've seen suggestions/requests on a few occasions to the effect of people wanting to view the aggregate of all comments to all cross-posts of the same or original post.  However feasible such a feature would be (I imagine it'd entirely for the UI/front end to manage, and feasibly so), it speaks to the users' desire to be able to engage with the multiple cross-posts and their various comments, mostly I imagine to consume as varied/interesting/diverse a feed as possible.
    * Beyond that, and thinking about lemmy as more than a link-aggregator, but, naturally capable of supporting more generic social media activity such as a blogosphere type ecosystem or even something encroaching on that of other fediverse platforms somewhat, surfacing the connections to manual cross-posts probably provides a good deal of value there too.

**Comment by Nutomic** [comment]
Crossposts dont really exist in the Lemmy backend. All it does is, when retrieving a post with `GET /api/v3/post`, perform a search for posts with the same url and include them in the result. So its not related to the crosspost button in the ui at all, and there is no way to represent text-only crossposts. For enhancements in this area open a new issue or check existing ones.

**Comment by shodanx2** [comment]
I think a "crosspost" here should be whenever you post a single thing to two or more communities

When the Lemmy ecosystem becomes decentralized, I think there should be no discernable "canon" community for any topic, but rather they would exist at a small scale on every server.

It of course becomes unrealistic to make a post to each and every server with its dozens of users and without crossposting functionality, each post would just be its own tiny echo chamber, this isn't useful, this does not bring people together.

The current lack of this feature acts as pressure against decentralization.

This leads to a situation like the following.

Consider the /c/books community(ies), they are ...
Despite 513 current active lemmy instances, only the following

Books@lemmy.ml - 12.3K subscribers
Books@lemmy.world - 6.02K subscribers
Books@lemmygrad.ml - 460 subscribers
Books@sh.itjust.works - 217 subscribers

Despite "books" being an universal topic of discussion, less than 1% of server offer a discussion space about them.

Worse, you can see by subscriber count that the user distribution skews toward "one big instance"

I propose that one of the many dynamic that amplify this "rush toward centralization" is the lack of a functioning cross post system.

Suppose you are going to post something.
For each community that you want to post to, will require as much effort as the single post, and that's assuming you don't read the rules, which of course, nobody does, ever.

So the incentive becomes "just post once" and Eff the rest.
And if you only post to one place, then where ? Of course bigger number better so again Eff the rest.

"Cross posting" should be as follows

1. The same regardless whether you are posting an image, a video, text, a zip file or an audio file (I know that last one is pushing it, Big Tech does not support these farcical "audio files" since 2013)
2. Cross posting entails no more than, checking more than one communities out of a list, This means changing the Listbox to a Combo-checklist box (the text field is a search filter function)
3. When accessed this "cross post" creates a single virtual discussion space, each root comment exists on its own server but crucially is READABLE on every other community of the crosspost, with no "master community" being the central host of the post, a true decentralized, distributed post which is merely re-assembled in the client.
4. Moderation only occurs on per server basis. 
 Example 
Books@lemmy.ml mods can, delete the cross post from their server
Books@lemmy.ml mods can, delete comments on their own servers (root thread and any child comment)
Books@lemmy.ml mods can, hide comments from other servers, but only for users on their own server, they cannot delete comments on another server

If the default view of a crosspost is not a default gathering of multiple instances, then I do not see any possibility that the "centralizing urge" of lemmy will ever really go away.

This is all very similar to the "multireddit" functionality, which, if exists on a per-user basis, will not affect community centralization and therefore reproduce all of Reddit fatal flaws, with the only exception of avoiding another "/u/spez", and only in the most extreme of cases and only theoretically.

**Comment by SleeplessOne1917** [comment]
I really like @shodanx2's idea.

> Suppose you are going to post something.
For each community that you want to post to, will require as much effort as the single post, and that's assuming you don't read the rules, which of course, nobody does, ever.
>
> So the incentive becomes "just post once" and Eff the rest.
> And if you only post to one place, then where ? Of course bigger number better so again Eff the rest.

I have definitely found myself in this situation before. I also think the 4-point suggestion is a really good idea to alleviate this path of least resistance issue that leads to over-centralization.

Since I've been on Lemmy for a lot longer than I was when I made the issue (I had only been using it for about a year and a half at that point) I have some more thoughts on it now than I did then. I think Lemmy crossposts as they are now aren't really crossposts per se (neither in the Reddit sense nor in the Fediverse friendly sense proposed by @shodanx2). Reiterating what I said in the original issue:

> If you make a post in a community that has the same URL as a post in another community, it will be marked as a crosspost regardless of whether the user clicked the crosspost button. 
> 
> Likewise, if you crosspost a post that doesn't have a URL, it will not be marked as a crosspost.

I think the term "crosspost" is misleading for this feature. "Crosspost" makes me think that the posts will be connected with eachother in some way regardless of whether they include a URL field or not, provided the user has chosen to crosspost.  The way it's currently handled by Lemmy, the only indication there is that something without a URL field is crossposted is [a "crossposted from" line and block quotes for the original post that get added to the create post textarea in the UI](https://github.com/LemmyNet/lemmy-ui/blob/a3a7d90c2b8e507f5e683c7d34aac374e4dabe6f/src/shared/components/post/post-listing.tsx#L962), and a user could remove this if they wanted to. I do think this functionality is still good to have since it can also help fight against a tendency towards centralization, and it can and should exist alongside a crosspost functionality like the one that was suggested, but I think a different name should be chosen to more clearly communicate what the feature actually is.

Maybe something like "other discussions for this link" would be better? TBH I'm having trouble coming up with good verbiage for this and I encourage others' input on this. I do think the feature should otherwise be kept as-is (except for clearer communication as to what it is) while existing alongside a crosspost feature.

Thoughts?
@dessalines @Nutomic @matc-pub @dullbananas @phiresky @MV-GH @flamingos-cant

**Comment by dessalines** [comment]
> Cross posting entails no more than, checking more than one communities out of a list, This means changing the Listbox to a Combo-checklist box (the text field is a search filter function)

That is entirely possible for any lemmy front end to build. IE in the create post screen, when you search for a community, allow the possibility to post to multiple ones at once.

> When accessed this "cross post" creates a single virtual discussion space, each root comment exists on its own server but crucially is READABLE on every other community of the crosspost, with no "master community" being the central host of the post, a true decentralized, distributed post which is merely re-assembled in the client.

Also a front end consideration. piefed does this by default by combining all the comments from cross-posts onto a single page (loading comments from others at the bottom). Whether we should do this in lemmy-ui is still up in the air, but any lemmy app could already do this.


> Maybe something like "other discussions for this link" would be better?

We do show the cross-posts at the top in lemmy-ui, and already [serve the cross-post links in GetPost](https://join-lemmy.org/api/main#tag/Post/operation/GetPost).

We use the post URL to link posts, and I don't see any other suggestion to that here.

**Comment by flamingos-cant** [comment]
I've personally always felt like a crosspost should work more like what's called a quote post on the microblog side of things, where the original post is embedded in the crosspost. The way crossposts work for text posts [is rather unintuitive](https://feddit.uk/post/33973619/19158460), but I'm not sure if it would even be worth the effort of actually implementing crossposts like this.

I'm also not sure how I feel about shodanx's idea. People defiantly just post the most popular comm where a post fits with little consideration to smaller comms, but I'm not sure how we'd implement this. We'd either have to let users create a several posts in different comms at once, which could be very spammy. Or we'd have to completely rework Lemmy to allow post to exist in different comms at the same time, which would be *a lot* of work.

> Moderation only occurs on per server basis.
> Example
> Books​@lemmy.mlmods can, delete the cross post from their server
> Books​@lemmy.ml mods can, delete comments on their own servers (root thread and any child comment)
> Books​@lemmy.ml mods can, hide comments from other servers, but only for users on their own server, they cannot delete comments on another server

If a post exists in comm A and comm B, what would happen if a problematic comment is made and only removed in comm A? This suggest that only users directly on comm A's instance won't see that comment. This seems to counter to the very idea of community moderators, they're there to cultivate a space and protect users.

**Comment by shodanx2** [comment]
For your consideration

Here is a typical crosspost as used in the wild

https://lemmy.ml/post/34897898

<img width="1448" height="256" alt="Image" src="https://github.com/user-attachments/assets/7898eec2-642f-4dd8-9302-28a923f3fe29" />

Which us all of these links

https://lemmy.ml/post/34897898
https://lemmy.ml/post/34905364
https://lemmy.ml/post/34897847
https://lemmy.ml/post/34897846
https://lemmy.ml/post/34897899
https://lemmy.ml/post/34897844
https://lemmy.ml/post/34897897
https://lemmy.ml/post/34864745

From what I understand, this isn't a case where someone posted something to one place and then crossposted it somewhere else, but instead multiple persons posted the same link to the same place and the system somehow detected the same link being discussed in multiple places and gathered multiple links to these places here.

In this current version, I think one thing that could be useful would be to put the number of comments in the other discussions 

It would look like this 

news@lemmy.world (35) technology@lemmy.world (3) technology@hexbear.net (6) technology@beehaw.org (4) technology@lemmy.zip(0) technology@lemmygrad.ml (1) hackernews@lemmy.bestiver.se(0)

Now really the thing we REALLY REALLY need is a view of all the comments from all of these different places in one single virtual location.

If you root comment post in the virtual location, then the comment thread existed on the server hosting the "crosspost itself" but if you reply to another root comment, then that reply is stored on the foreign server.

Just that would already be something of a game changer.

The it would make sense to enable posters to cross post to a large pre-selected list of same-name communities on various servers without having to think about those 20 user-servers but also not leaving them out.

And finally, it would make sense to make the "virtual view" the default view of most users.

In this case, when some moderator inevitably decides to user their position of power to strangle a story, they will only be able to strangle it on their servers, but every other server will see it.

And if you can hang out and post on a 20 user server and still reach the whole fediverse, then it will finally make sense for everyone to stay in their own little instance and the "big instance" with "the big community" will naturally die of the ignominious death that it deserves. 

Concentration of power in the hands of moderators and lemmy instance owners is a threat to the fediverse and the sooner they are gone the better.

I hope we can have a fediverse where the biggest lemmy instance is 100 users and I can spool up and I give away hundreds of instances to 5-person friend groups. A fediverse where defederation is an absurd idea and a moving target, where nobody controls the flow of information, like email but for one-to-many communication.  

However, we are going to need better spam tool, user reputation evaluation, automatic user history screening, tunable client-side algorithmic feeds.   Instead of being the current, strangled stream of information that is such a small trickle that chronological timeline still make sense and even gets stale (and by that I mean, my lemmy home page has two day old posts on the first page)

**Comment by dullbananas** [comment]
> In this current version, I think one thing that could be useful would be to put the number of comments in the other discussions
> 
> It would look like this
> 
> [news@lemmy.world](mailto:news@lemmy.world) (35) [technology@lemmy.world](mailto:technology@lemmy.world) (3) [technology@hexbear.net](mailto:technology@hexbear.net) (6) [technology@beehaw.org](mailto:technology@beehaw.org) (4) [technology@lemmy.zip](mailto:technology@lemmy.zip)(0) [technology@lemmygrad.ml](mailto:technology@lemmygrad.ml) (1) [hackernews@lemmy.bestiver.se](mailto:hackernews@lemmy.bestiver.se)(0)

Definitely a good idea. Also maybe it should show each post's top comment.

> Now really the thing we REALLY REALLY need is a view of all the comments from all of these different places in one single virtual location.

This should at least be done automatically when browsing a multi-community.

**Comment by shodanx2** [comment]
This thread is being continued in 

https://github.com/LemmyNet/lemmy-ui/issues/3415
