### ISSUE TITLE
[Feature Request] Setting to auto-collapse bot comments

### ISSUE THREAD

**Issue by BrianAllred** [LemmyNet/lemmy#3838]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

As Lemmy has gained popularity, it's gained the attention of a number of developers who have written useful bots. However, sometimes bots can clutter the comments, especially long-winded ones like `AutoTL;DR`.

### Describe the solution you'd like.

A setting to auto-collapse bot comments so that they don't clutter the comments section when first opened.

This sounds like a UI issue (and it is), but making it a backend setting would allow third-party clients to read and respect the setting, as well.

### Describe alternatives you've considered.

Muting or blocking the bot account would work, but that would mean *never* seeing the bot's comments, instead of only seeing them when you want to.

**Comment by chaorace** [comment]
Such a feature would also be a great tool for dealing with spoiler content in seasonal content discussion communities. As an example, /r/anime provides a special area reserved for spoiler talk in episode discussion threads ([example](https://old.reddit.com/r/anime/comments/1726ifa/saihate_no_paladin_tetsusabi_no_yama_no_ou_the/)) -- a major quality of life feature which is only possible because the comment thread demarcating this special area is automatically collapsed by default:

![A screenshot of an /r/anime discussion thread depicting their "Source Material Corner". It's a top-level comment where the child comments are hidden by default. The content of the top-level comment itself is still visible by default and it reads as follows: "Source Material Corner: Reply to this comment for any source-related discussion, future spoilers (including future characters, events and general hype about future content), comparison of the anime adaptation to the original, or just general talk about the source material. You are still required to tag all spoilers. Discussions about the source outside of this comment tree will be removed, and replying with spoilers outside of the source corner will lead to bans. The spoiler syntax is: [reddit spoiler syntax omitted]. All untagged spoilers and hints in this thread will receive immediate 8-day bans (minimum).](https://github.com/LemmyNet/lemmy/assets/6462592/128ddf70-ca0b-42c6-9d6a-434db26fe77b)

This is admittedly a slightly different thing from this issue's core request for a comment style which autocollapses *both* the comment content *and* any child comments (*the above pictured feature only hides the child comments while keeping the comment body visible*). Ideally it would be nice if *both* types of autocollapsing comments were implemented as available comment options, though simply being able to autocollapse a comment *at all* would be a **huge** step in the right direction!

**Comment by dessalines** [comment]
Spoiler content is already handled : https://join-lemmy.org/docs/users/02-media.html?highlight=spoil#text
