### ISSUE TITLE
[Bug]: ERR_INVALID_RESPONSE on comment link

### ISSUE THREAD

**Issue by davetapley** [LemmyNet/lemmy#3848]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

https://lemmy.world/comment/1914636 loads fine if you navigate there from another page (https://lemmy.world/post/2425479), but gives `ERR_INVALID_RESPONSE` if you load it in a new window.

### Steps to Reproduce

1. Go to https://lemmy.world/comment/1914636

### Technical Details

N/A

### Version

BE 0.18.3

### Lemmy Instance URL

lemmy.world

**Comment by RocketDerp** [comment]
this is happening only on lemmy.world and no other Lemmy instance that I have tested. The owner/operators seem to have put some front-end (Cloudflare, firewall, nginx - take your pick) that blacks if there is no same-site referrer. It's been that way for me since 1 week ago, and I think it is their response to some ongoing attacks against the site hitting a performance problem on loading of comments.

I've been asking to find out which exact comments cause the performance troubles so we can try to reproduce it and optimize Lemmy's PostgreSQL logic - but no luck yet.

**Comment by Nutomic** [comment]
Cant reproduce
