### ISSUE TITLE
Question: How to move all local posts to a new installation of Lemmy?

### ISSUE THREAD

**Issue by therealmaxmoon** [LemmyNet/lemmy#3901]
### Question

I have [the reinstall problem](https://github.com/LemmyNet/lemmy/issues/3898), which could be solved if I reinstall Lemmy again, **BUT** with a new subdomain.

But because I already have some dozens posts on my instance, I would like to know if there's a way to backup them and restore them on the new installation (with the new subdomain) or if they are connected to the old subdomain and that I have to rewrite/recreate most of them?

**Comment by irdc** [comment]
Lemmy content (posts and comments, but also things like up-/downvotes) is uniquely identified by an URL, which is made up of the instance's domain name, a content type and an unique identifier, often a number that's incremented for each item. Eg. https://lemmy.ml/post/3021118 references post number 3021118 on domain lemmy.ml. This is how all other instances that have taken content from you uniquely identify that specific piece of content.

So, as you can see, moving content to a new subdomain isn't easy: the problem is not your instance, but *all other* instances that suddenly can no longer find the origin instance responsible for a piece of content.

My advice: don't do it, just start afresh and see this as part of the learning process.

**Comment by therealmaxmoon** [comment]
@irdc Thank you

I am gonna close this issue, because a solution is not possible and I switch to another forum software, because Lemmy caused a lot more issues than that.
