### ISSUE TITLE
[Bug]: Excessive storage use

### ISSUE THREAD

**Issue by vitriolix** [LemmyNet/lemmy#3956]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When I check Chrome's storage usage for all sites, Lemmy.ml is by far the number one user of storage space (850mb!).  Lemmy should not be taking up this much space in the users browser storage

### Steps to Reproduce

1. use Chrome to browse a lemmy instance (such as lemmy.ml) a lot
2. check Chrome's web site storage and see high usage by that lemmy instance

### Technical Details

observed on Mac OS 13.4.1 and Chrome 116.0.5845.179

### Version

0.18.4

### Lemmy Instance URL

lemmy.ml

**Comment by vitriolix** [comment]
Here is my storage usage

<img width="647" alt="Screenshot 2023-09-08 at 12 45 42 PM" src="https://github.com/LemmyNet/lemmy/assets/7844/b0cff54d-70a0-4ffa-9c6e-cb038de082aa">

**Comment by Trombach** [comment]
I've had a quick look with the chrome dev tools and the storage usage at least on my end is almost exclusively from the cache
![image](https://github.com/LemmyNet/lemmy/assets/19306765/ff1289fe-a77f-49b2-9060-172f2a019064)
This isn't really a bug, since it's just using the default behaviour of the browser (I believe a single origin can use up to 60% of the available disk space by default), however, I'm not saying that some things could be optimised for smaller storage usage.

In any way, I'm fairly certain this is not a backend issue and only concerns lemmy-ui.
