### ISSUE TITLE
[Bug]: post removals not being properly federated

### ISSUE THREAD

**Issue by Antik79** [LemmyNet/lemmy#3980]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

A user from lemmy.ml posted into a lemmy.world community.  After the thread was removed from the lemmy.world community the thread stayed visible on lemmy.ml

Thread on Lemmy.ml
https://lemmy.ml/post/5128305

Community on Lemmy World. 
https://lemmy.world/c/sciencefiction

Community on Lemmy.ml
https://lemmy.ml/c/sciencefiction@lemmy.world

### Steps to Reproduce

1. UserA from InstanceA posts in CommunityB of InstanceB
2. Admin from InstanceB bans UserA and removes his post from CommunityB
3. The thread stays up on InstanceA

### Technical Details

No logs available

### Version

BE 0.18.4

### Lemmy Instance URL

lemmy.world

**Comment by morcantium** [comment]
### Confirmation of Problem

Confirming this issue also exists for lemmy.dbzer0.com, but it is intermittent. For example, all of the six example posts below were made on a community hosted by lemmy.dbzer0.com. Four of these posts were removed by a lemmy.dbzer0.com admin. However those removals are not observed to be federating consistently to other instances - I have included specific examples below. 

In two of the included examples, the posts were removed by another instance admin (from the origin server of the user who created the post). We would not expect those post removals to federate to lemmy.dbzer0.com and elsewhere, however those removals did in fact (mostly) federate to other instances that we checked.

### Expected behavior

1. If a mod/admin from the host instance removes a post from one of their communities it **should federate to all subscribed instances**. But the data shows federation of that mod action is broken, and is only happening inconsistently.
2. If a mod/admin from a subscribed instance removes a post from a community hosted on another instance, the removal **should not federate**. But the examples show that that mod action does (mostly) federate, at least in the case where the post was made by a user from their instance.

### Examples

```
https://lemmy.dbzer0.com/post/4580443 posted by [lemmy.blahaj.zone/pewgar_seemsimandroid](http://lemmy.blahaj.zone/pewgar_seemsimandroid) 1 day ago
"anyone have angry birds earth day for android"
Mod: Unruffled ([lemmy.dbzer0.com/u/Flatworm7591](http://lemmy.dbzer0.com/u/Flatworm7591))
Mod action: Removed Post
Time: 18 hours ago
Status of post:
[lemmy.dbzer0.com](http://lemmy.dbzer0.com/): removed
[hexbear.net](http://hexbear.net/): removed
[szmer.info](http://szmer.info/): NOT removed
[feddit.de](http://feddit.de/): NOT removed
[lemmy.blahaj.zone](http://lemmy.blahaj.zone/): NOT removed
[lemmy.basedcount.com](http://lemmy.basedcount.com/): NOT removed

https://lemmy.dbzer0.com/post/4500845 posted by [feddit.de/Pantoffel](http://feddit.de/Pantoffel) 2 days ago
"Looking for the wheel of time audiobook series in German [Das Rad der Zeit]"
Mod: Unruffled ([lemmy.dbzer0.com/u/Flatworm7591](http://lemmy.dbzer0.com/u/Flatworm7591))
Mod action: Removed Post
Time: 17 hours ago
Status of post:
[lemmy.dbzer0.com](http://lemmy.dbzer0.com/): removed
[hexbear.net](http://hexbear.net/): removed
[szmer.info](http://szmer.info/): NOT removed
[feddit.de](http://feddit.de/): NOT removed
[lemmy.blahaj.zone](http://lemmy.blahaj.zone/): NOT removed
[lemmy.basedcount.com](http://lemmy.basedcount.com/): NOT removed

https://lemmy.dbzer0.com/post/4525786 posted by [szmer.info/Waseemmayo](http://szmer.info/Waseemmayo) 2 days ago
"Navigating the Enchanting World of Dolphin Encounters with Ocean Adventures Punta Cana"
Mod: Unruffled ([lemmy.dbzer0.com/u/Flatworm7591](http://lemmy.dbzer0.com/u/Flatworm7591))
Mod action: Removed Post
Time: 2 days ago
Status of post:
[lemmy.dbzer0.com](http://lemmy.dbzer0.com/): removed
[hexbear.net](http://hexbear.net/): removed
[szmer.info](http://szmer.info/): removed
[feddit.de](http://feddit.de/): removed
[lemmy.blahaj.zone](http://lemmy.blahaj.zone/): removed
[lemmy.basedcount.com](http://lemmy.basedcount.com/): removed

https://lemmy.dbzer0.com/post/4045566 posted by [lemmy.nz/bwcgem](http://lemmy.nz/bwcgem) 8 days ago
"びぐわいとぺにす"
Mod: [lemmy.nz](http://lemmy.nz/) (mod from [lemmy.nz](http://lemmy.nz/) removed post and banned user)
Mod action: Removed Post 
Time: 8 days ago
Status of post:
[lemmy.dbzer0.com](http://lemmy.dbzer0.com/): removed
[hexbear.net](http://hexbear.net/): removed
[szmer.info](http://szmer.info/): removed
[feddit.de](http://feddit.de/): removed
[lemmy.blahaj.zone](http://lemmy.blahaj.zone/): removed
[lemmy.basedcount.com](http://lemmy.basedcount.com/): NOT removed

https://lemmy.dbzer0.com/post/3938809 posted by [hexbear.net/blakeus12](http://hexbear.net/blakeus12) 10 days ago
"How would someone, hypothetically, pirate Baldur's Gate 3 without being able to torrent?"
Mod: Unruffled ([lemmy.dbzer0.com/u/Flatworm7591](http://lemmy.dbzer0.com/u/Flatworm7591))
Mod action: Removed Post
Time: 10 days ago
Status of post:
[lemmy.dbzer0.com](http://lemmy.dbzer0.com/): removed
[hexbear.net](http://hexbear.net/): NOT removed
[szmer.info](http://szmer.info/): NOT removed
[feddit.de](http://feddit.de/): removed
[lemmy.blahaj.zone](http://lemmy.blahaj.zone/): removed
[lemmy.basedcount.com](http://lemmy.basedcount.com/): NOT removed

https://lemmy.dbzer0.com/post/3862797 posted by [lemmy.nz/pissdrinker](http://lemmy.nz/pissdrinker) 11 days ago
"Biology doesn't care about your feelings"
Mod: [lemmy.nz](http://lemmy.nz/) (mod from [lemmy.nz](http://lemmy.nz/) removed post and banned user)
Mod action: Removed Post 
Time: 11 days ago
Status of post:
[lemmy.dbzer0.com](http://lemmy.dbzer0.com/): removed
[hexbear.net](http://hexbear.net/): removed
[szmer.info](http://szmer.info/): removed
[feddit.de](http://feddit.de/): removed
[lemmy.blahaj.zone](http://lemmy.blahaj.zone/): removed
[lemmy.basedcount.com](http://lemmy.basedcount.com/): NOT removed
```

**Comment by IzzyData** [comment]
This is actually not a bug. The implications of what you are suggesting is giving other instances the authority to affect other instances that they should not have authority over.  Having moderator or administrator permissions on instance A does not imply moderator or administrator permissions on instance B. This would be a severe security flaw.

**Comment by Antik79** [comment]
This is confirmed to be a bug by Dessalines. I posted this here on his
request.


Op vr 22 sep. 2023 22:02 schreef IzzyData ***@***.***>:

**Comment by unruffled3118** [comment]
IzzyData: To clarify, if I moderate a community _hosted on my instance_, and I remove a post from that community on my instance, then that removal should be federated out to all other instances that federate with my community. That is how I, and many other admins, expect lemmy to behave (see [https://matrix.to/#/#lemmy-support-general:discuss.online](https://matrix.to/#/#lemmy-support-general:discuss.online)) for a recent discussion on this topic. Otherwise we would need admins on every federated instance to deal with the exact same report independently which is totally unworkable.

If you are talking about the second example I gave where a remote admin removed a post and the removal federated to my instance, I totally agree that is **not** how it should be working, however that is what we observed to happen. There is no removal mod action recorded in our modlog, only in the modlog of the remote instance, even though the community is hosted on my instance.

**Comment by poVoq** [comment]
Same problem here. Getting a lot of reports from remote users for posts that I long moderated on our instance, and it really paints a bad picture of our communities as unmoderated when viewing them remotely.

My guess is that this mainly happens when a site admin that is not the same time also community moderator of that specific community takes a moderation action specific to that community?

**Comment by Nutomic** [comment]
Removals are definitely supposed to federate when they are made on the instance where the community is hosted.  

> My guess is that this mainly happens when a site admin that is not the same time also community moderator of that specific community takes a moderation action specific to that community?

Good thinking, it looks like you are right. Im currently trying to fix it.

**Comment by poVoq** [comment]
Great, will there be a minor bugfix release for it?

I think this is rather important as especially when a community is not well moderated the site admins need to intervene.
