### ISSUE TITLE
[Bug]: Docker tag :latest points to nightly builds

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#3996]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Various instance admins recently ran into problems after they accidentally upgraded to the `:latest` Docker tag. This shouldnt be a problem as latest is supposed to point to the most recent release version. But in fact it points to nightly builds from the development branch. This is not at all intended. 

Our Docker images are built and pushed by the [woodpecker docker plugin](https://woodpecker-ci.org/plugins/Docker%20Buildx). From my understanding of the documentation, our [nightly build task](https://github.com/LemmyNet/lemmy/blob/main/.woodpecker.yml#L249-L260) should not push to the `:latest` tag. There is also an [issue](https://codeberg.org/woodpecker-plugins/docker-buildx/issues/53) indicating that the `:latest` tag is being pushed to incorrectly. So this seems like a bug. It would be very helpful if someone who is familiar with Go could look through the [source code](https://codeberg.org/woodpecker-plugins/docker-buildx) to find out how this can be resolved, so that `:latest` tag only gets pushed for releases.

The same problem is also happening for lemmy-ui.

**Comment by Nothing4You** [comment]
just looking at https://hub.docker.com/r/dessalines/lemmy/tags i don't think this is from the nightly task, as currently the latest tag is from 2 days ago while dev is only 20 hours old.
also, dev has amd64 and arm64 builds, while latest only has an amd64 build.
they also have different digests, which wouldn't be the case if they were from the same build run.

**Comment by Nothing4You** [comment]
[latest](https://hub.docker.com/layers/dessalines/lemmy/latest/images/sha256-d218f51276145e83a6bd0695090c7842d269fc6d80fe0911b6fbe14233acd4a3?context=explore) is built from a different Dockerfile than [dev](https://hub.docker.com/layers/dessalines/lemmy/dev/images/sha256-8198597d0abc0793d2b2f36fc1352f4d95ba4c121092e5c1360739d37b631131?context=explore), as they have different image layers.

**Comment by Nothing4You** [comment]
is it possible that this is (probably unintentionally) being pushed manually?

**Comment by Nothing4You** [comment]
`latest` is the same image that was pushed as `[0.18.5-rc.2](https://hub.docker.com/layers/dessalines/lemmy/0.18.5-rc.2/images/sha256-d218f51276145e83a6bd0695090c7842d269fc6d80fe0911b6fbe14233acd4a3?context=explore)`, so whatever was used to push that is likely also where the latest tag comes from.

**Comment by Nothing4You** [comment]
oh well, i misread the issue you linked.

https://codeberg.org/woodpecker-plugins/docker-buildx/issues/49 is the issue asking to add an option to not add the `latest` tag when using `auto_tag`.

this behavior is indeed by design.

the other issue, https://codeberg.org/woodpecker-plugins/docker-buildx/issues/53, is precisely about the workaround i was suggesting above not working, as the `latest` tag would still be tagged when you specify a different `default_tag` and it also can't be worked around by specifying `default_suffix`.

**Comment by Nutomic** [comment]
Hmm then we should push to `:latest` only for stable releases, not release candidates. But that seems complicated to configure.

Or we get rid of `auto_tag: true` so it doesnt push to `:latest` at all. And also wont create `0.18` tag for `0.18.5` release. What do you think @LemmyNet?

**Comment by Nothing4You** [comment]
it might be an option to have conditional logic in the workflow to change behavior depending on the tag.

for example, you could enable `auto_tag: true` if the git tag matches `^[0-9]+\.[0-9]+\.[0-9]+$` only and otherwise use the git tag as tag.
this should allow stable releases to still benefit from automatic tags while any tags that don't match the expected format would only be tagged with the same tag used in git.

when using this approach it should be kept in mind that you'd never want to tag a release like 0.18.5 after a newer minor version, such as 0.19.0 was tagged, as otherwise the latest tag would be downgraded from 0.19.0 to 0.18.5 at that point.

**Comment by Trombach** [comment]
@Nothing4You I've looked into the woodpecker docs and it seems that the `ref` filter only supports doublestar matching and not full regular expressions. The filter would probably have to be built using `evaluate` and `CI_COMMIT_TAG`. However, I'm not even sure that `evaluate` supports regex either

Another option would be to use Github actions for deploying the latest build to docker. You can use an `event: release` trigger such that the workflow only deploys when a release is published instead of on every tagging event. I understand it might not be desirable to have your CI use 2 different platforms, but I just wanted to mention this possibility.

There are still some other considerations here, i.e. it should be ensured that when a minor version gets applied to the previous major release after a new major release is out (for example `18.6` gets released after `19.1`) that it doesn't get pushed to the latest docker tag.

**Comment by Nothing4You** [comment]
`evaluate` does support regex.
https://woodpecker-ci.org/docs/usage/pipeline-syntax#evaluate refers to https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md, which contains the following example: `foo matches "^[A-Z].*"`

something like this would probably work:

```yaml
  publish_release_docker_latest:
    # [...]
    when:
      evaluate: 'CI_PIPELINE_EVENT == "tag" && CI_COMMIT_TAG matches "^[0-9]+\.[0-9]+\.[0-9]+$"'

  publish_release_docker_unstable:
    # [...]
    when:
      evaluate: 'CI_PIPELINE_EVENT == "tag" && not (CI_COMMIT_TAG matches "^[0-9]+\.[0-9]+\.[0-9]+$")'
```

or one could try to fit it in the same job by setting `auto_tag` and conditionally `tag` based on some expression.

if logic to avoid tagging latest for a lower version is to be added, this might make the process quite a bit more complex, as then you'd probably need to run a dedicated script to fetch versions from docker hub and compare version strings.
i can't currently think of a good solution for this other than building a script that queries the docker registry api, tries to determine the latest release and then comparing versions between git tag and discovered existing docker tag.

**Comment by Nothing4You** [comment]
thoughts on the approach above? should i draft a PR for that?
do you think it's reasonable to expect maintainers to not tag older minor versions for the time being?

**Comment by KaKi87** [comment]
Hi,
Is there no `latest` tag at all anymore ?
Thanks

**Comment by Nutomic** [comment]
No, we dont have a good way to create new `latest` tags only for final releases and not for alpha/beta versions. Besides with latest there is a risk that admins accidentally upgrade to a new major version which requires extra migration steps. Better to specify the version explicitly.

**Comment by KaKi87** [comment]
Well, if all I do is opening https://hub.docker.com/r/dessalines/lemmy/tags to get the new version number then editing `docker-compose.yml` then running `docker compose down` then `docker compose up -d` then it's the same as if there was a `latest` tag, except for the extra steps, that I might end up creating an automation script for.

Anyways, I understand this position isn't gonna change so I'm gonna drop the conversation and I'll just edit this message if I end up making that script.

Thanks anyway

**Comment by dessalines** [comment]
A good number of lemmy upgrades require extra instructions, and we've had too many people completely break their installs by using `latest`.

**Comment by KaKi87** [comment]
Then I guess [Lemmy as a blog](https://github.com/LemmyNet/lemmy-docs/blob/0ae7fa494e402357244ecfc4b10760be62c91775/src/users/06-other-features.md#lemmy-as-a-blog) is a bad idea after all. Hassle-free upgrades is a necessity for blog authors.

**Comment by Nutomic** [comment]
@KaKi87 Lemmy upgrades are very much hassle-free using [ansible](https://github.com/LemmyNet/lemmy-ansible). `git pull` latest changes from the repo, run the `ansible-playbook` and you're done. Or do it manually by simply changing the version in `docker-compose.yml`.

**Comment by KaKi87** [comment]
> Or do it manually by simply changing the version in `docker-compose.yml`.

That's precisely the thing : having a `latest` tag could save users from doing this manual change.
