### ISSUE TITLE
[Bug]: Rename "Block" to "Mute"

### ISSUE THREAD

**Issue by Pxtl** [LemmyNet/lemmy#4041]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Based on conventions of similar platforms, blocked users are expected to be unable to interact with the blocking user's content.

Instead, the blocked user is simply *invisible* to the blocking user.

In similar platforms, that is called a "mute".  Either lemmy should update its terminology so that the action is renamed "mute", or "block" should be enhanced to prevent replies, etc. from the blocked user.

### Steps to Reproduce

1. Block a user
2. That user can still reply to your posts, you simply don't see the replies
3. No 3.

### Technical Details

None.

### Version

UI: 0.18.4 BE: 0.18.5

### Lemmy Instance URL

lemmy.ca

**Comment by dessalines** [comment]
This would only be necessary if we added the other kind of block (a two-way block), which I've argued against in the past, because it affects what content *other* people see, rather than just your own. 

IE a two-way block does something explicit for someone else, that they did not choose to do themselves.

**Comment by DraconicNEO** [comment]
> This would only be necessary if we added the other kind of block (a two-way block), which I've argued against in the past, because it affects what content _other_ people see, rather than just your own.
> 
> IE a two-way block does something explicit for someone else, that they did not choose to do themselves.

I don't really think keeping it named block is a good idea since it gives an idea of what it does, i.e. they would suggest it for situations better suited for a two way block, like a user or bot spamming links/self promo under their posts or comments, or a person harassing them and calling harassment towards them (keeping in mind that there are admins who are slow to action or just don't action (two larger instances I know are notorious for this).

I do agree that content shouldn't be hidden from others without their consent but I do think a Two way one should be in there for safety, just not in the form of hiding content from others, just preventing interaction, since malicious users might not be actioned on/by certain instances and being able to "Restrict" them (block their interractions but not prevent them from seeing things) is important against those types of users and bots. That's something for a different issue though.

**Comment by dessalines** [comment]
If someone really wants to do the work to go through all the tables and API to rename them to mute, I wouldn't be opposed, but at the same time, no one has a monopoly on these terms, and "blocking a person" seems to make sense to most people already.

I'll re-open if someone wants to do this.

**Comment by MaximilianKohler** [comment]
Hmm, I might be able to do it if it's as simple as searching the code and replacing "block" with "mute".

I agree that "block" is misleading, and it should be changed to "mute" or "ignore". Related: https://github.com/LemmyNet/lemmy/issues/1832

**Comment by dessalines** [comment]
All our api terminology, tables, pretty much everything. If any app or client wants to change that language though, they can.

**Comment by DraconicNEO** [comment]
> Hmm, I might be able to do it if it's as simple as searching the code and replacing "block" with "mute".
> 
> I agree that "block" is misleading, and it should be changed to "mute" or "ignore". Related: #1832
> 
> Wouldn't this be a lemmy-ui issue though?

Probably would want to leave alone the parts related to defederation, since blocking an instance by an admin is a block and not a mute.

**Comment by MaximilianKohler** [comment]
What if I just change it in lemmy-ui https://github.com/LemmyNet/lemmy-ui in a few places:

* User page, `Block User`
* Community page `Block community`
* User settings page `Blocks`, `Block user`, `Blocked users`, `Block community`, `Blocked communities`, `Block instance`, `Blocked instances`.

I'll change them all to `Mute`.

**Comment by DraconicNEO** [comment]
> What if I just change it in lemmy-ui https://github.com/LemmyNet/lemmy-ui in a few places:
> 
>     * User page, `Block User`
> 
>     * Community page `Block community`
> 
>     * User settings page `Blocks`, `Block user`, `Blocked users`, `Block community`, `Blocked communities`, `Block instance`, `Blocked instances`.
> 
> 
> I'll change them all to `Mute`.

That would work. I guess the API doesn't need a name change, mainly because it'll never really be seen by people. The UI is where these changes matter most.

**Comment by MaximilianKohler** [comment]
I was about to get started on it and I can't find the phrases in the code at all:

* https://github.com/search?q=repo%3ALemmyNet%2Flemmy-ui+%22Block+User%22&type=code
* https://github.com/search?q=repo%3ALemmyNet%2Flemmy-ui+%22Block+community%22&type=code

**Comment by Nutomic** [comment]
@MaximilianKohler Translations are here: https://github.com/LemmyNet/lemmy-translations/blob/main/translations/en.json

**Comment by MaximilianKohler** [comment]
> If someone really wants to do the work to go through all the tables and API to rename them to mute, I wouldn't be opposed, but at the same time, no one has a monopoly on these terms, and "blocking a person" seems to make sense to most people already.
> 
> I'll re-open if someone wants to do this.

What changed? I did it and it was rejected.

>You can do this on your own lemmy app, but I'm opposed to it for lemmy-ui, and everywhere else. Block is the term we've used, and if we ever need to account for different types of blocks, I don't want them to get confused.

I don't see how this makes sense. If anything, you would **want** to rename the current function to mute in order to remove confusion and keep it distinct if you decide to implement other types of blocks.

It's been suggested in other issues as well https://github.com/LemmyNet/lemmy/issues/1832.

**Comment by dessalines** [comment]
Read my comment on that PR.

**Comment by MaximilianKohler** [comment]
I quoted your comment above, so I clearly read it.
