### ISSUE TITLE
Reduce size of `sent_activity` table

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#4113]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

This table currently takes 22 GB on lemmy.ml. Similarly to `received_activity` described in https://github.com/LemmyNet/lemmy/issues/4110, entries are automatically cleared after three months. With 0.19 it will likely get even bigger as it stores a lot of extra data.

It serves two purposes:
- It serves as a queue for outgoing activities which havent been delivered yet. For this purpose it would be fine to delete rows right after the activity was successfully delivered or permanently failed.
- Used for the `/activities/` endpoint which serves JSON data of sent activities. Lemmy doesnt use this at all and would work just fine without it. However the endpoint can be useful for debugging, and it may be used by other Fediverse platforms (unknown).

So to reduce the size we can simply reduce the cleanup interval. Something like one week might be totally fine. We could go even further and delete activities as soon as they are successfully delivered. If someone complains about `/activities` endpoint being broken, we have some information how it is used.

cc @phiresky @dessalines

**Comment by phiresky** [comment]
With the persistent queue, this time limit also defines how long a federated instance can be down to not lose any instances. e.g. if it is set to prune to a day, then an instance that's down for less than a day will fully receive all activity from this instance. If the time limit is less than the down time, the activity is lost. 

 Deleting "as soon as they are delivered" is a bit more complicated because you would have to take the minimum of the last_successful_id column of the federation_queue_state table. This would work, but you'd still need a time limit to make it not baloon if any one instance is not successfully accepting federation events any more.

So i think for this purpose, just using a limit of a day or a week should be fine.
