### ISSUE TITLE
More democratic moderation

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#417]
I'm just gonna dump the chat log here. 

```
nutomic
It would be cool if Lemmy could have some democratic means for determining the mods for a community
On reddit, the mods can't be removed, so they can just squat a subreddit and the users can't do anything except go elsewhere (or beg the admins)
It would be cool if Lemmy had some kind of voting system so that the users could pick the moderators
dessalines have you thought about this stuff before?
protodrew
^^
pingveno
nutomic: Sounds tricky. Someone could do ballot box stuffing very easily.
nutomic
I never said it would be easy, I said it would be cool :)
alex
What if users could "follow" the mods they choose? Meaning they would only see the effects of the mods they "follow"
David
Sounds like a good feature to experiment with on a fork, since you'd probably want it at a server level anyway
alex
If a mod goes rogue users can unfollow him and his actions would have no effect on their feeds
David
alex
What if users could "follow" the mods they choose? Meaning they would only see the effects of the mods they "follow"
Ok that would be hard to implement 😄
nutomic
Yep, selectively applying mod decisions makes it like a hundred times more complicated than simple mod elections
alex
Yeah, I guess it is a hard problem to solve. But it is one more step towards more decentralization.
nutomic
Its not real decentralisation, because the server admin still controls everything
Unless we can distribute communities between servers somehow
Actually it might be possible
pingveno
Gotta go with blockchain. :P
Dessalines
nutomic
dessalines have you thought about this stuff before?
A little... I haven't read any actually good proposals of a way to do democratic moderation tho... mainly because its nearly impossible to protect open communities from brigades.

You could potentially do some analysis of points and participation to find out who the "real" users are, and only let them vote, but that also has lots of problems. Its unfortunate because plenty of subs turn to shit when the highest mods go missing.

I'm sure yall have better ideas than i do on this.

nutomic
Yeah we should write this up in an issue
Stackoverflow has something like this, though it has its problems
David
That's what admins are for IMO (when mods go missing). Or in a federated system, migrating to a new community hub is likely easier
nutomic
As an admin, I would be happy if I didn't have to take care of moderation myself
David
I think being responsible for meta-moderation is a reasonable thing to ask of an admin
pingveno
Wikipedia has multiple levels of elevated privilege.
One of those is bureaucrat, who among other things can give and remove the privileges of regular moderators.
Or whatever the regular elevated user privilege is, I forget.
https://en.wikipedia.org/wiki/Wikipedia:Bureaucrats

Wikipedia:Bureaucrats - Wikipedia
Wikipedia:Bureaucrats From Wikipedia, the free encyclopedia Jump to navigation Jump to search "WP:BUR" redirects here. For the "Wikipedia is not a bureaucracy" policy, see
There are over a thousand administrators in Wikipedia, but under twenty bureaucrats.
```

**Comment by kaiyou** [comment]
Here is a summary of my (distant) take on the matter, based mostly on discussions I had about Prismo at the time.

First we need to state that moderation is instance-based: you can moderate what you control, and in the Fediverse you only control your instance. Next we have to distinguish between a « community » and a « tag », which are both topic-like concepts; the exact choice of words does not matter, but I'll suggest some definitions.

A « community » as defined in Lemmy is a thread bound to an instance, exposed over the federation, and that people across the federation can subscribe to or post to. Because it is bound to an instance, most things that revolve around it are specific to that instance and ultimately under the control of that instance admin. Because it is bound to an instance, like moderation, you can have per-community moderation.

A « tag », as is already used by most Fediverse objects and implementations, can hold the same general semantic as a community, except it federates in a very different manner. A tag is not bound to an instance. Because moderation is bound to an instance and tags are not, moderation or any kind of control cannot happen federation-wide based on a tag. You cannot delete or ban a tag globally, nor can you ban a user from that tag globally. You can merely take these actions at the instance level, and have each instance make its own decisions (and have different views on the same federated data).

Which model is best is not easily answered and depends on what you are trying to accomplish. If you want distributed control based on where people are hosted and no central management, then tags are great option. If you wish reddit-like community, that the creator can keep control over, then communities are the way to go. Currently Lemmy uses communities, i.e. has a topic-like structure bound to an instance, which makes it different from just sharing a link to Mastodon, and I like that, but that is my personal opinion.

---

For the sake of thoroughness, there exists another way for distributing control while also distributing the topic-like structure. That way is call eventual-consistency based on consensus algorithms that are permission-aware. It is basically the way that Matrix chose, having its « rooms » be places where people talk, not being bound to any instance, while still having per-room moderation capabilities. This requires a state-resolution algorithm that all servers shall implement, so that each server can know at any time who has what privileges on which room, and base its decision based on that state. This is hard and expansive. Hard because the resolution algorithm is complex, and any mistake will result in split-brain situations, or attacks being able to gain privileges federation-wide by exploiting vulnerabilities. Expansive because state resolution requires everyone has the same data, so everyone knows all relevant data about a tag/room/community; this is non-trivial in the fediverse, as instances only see what they subscribed to.

All this hard and expansive problem could be moved to a different protocol, even one made especially for that purpose. One of the obvious choices would be a structured blockchain like Ethereum. But that still brings a lot of complexity.

Finally, why do I think that complexity is not worth the shot? Matrix is about solving complex instant communication issues in a distributed manner, the rules are about completeness, ordering, etc. The Fediverse is not about this whole deal, it is about being able to publish structured messages to subscribers, about doing it at low cost so people can host many instances, which in turns encourages free speech, privacy and safety. The Fediverse relies on simplicity. If we go complex, we will fail.

**Comment by kaiyou** [comment]
All of this said, nothing prevents from implementing per-instance rules where community moderators are designated in any other manner than just being the creator of that community.

**Comment by Cazadorro** [comment]
### Background 

Recently there was a Reddit post [here](https://old.reddit.com/r/linux/comments/guklhr/we_are_the_devs_behind_lemmy_an_open_source/) which invited conversation [here to this thread](https://old.reddit.com/r/linux/comments/guklhr/we_are_the_devs_behind_lemmy_an_open_source/fsj77bn/): 

This seems fairly old and not much transparent conversation has gone on so I'm not holding my breath we'll get any decent discussion here (or even that this is the right place), but I'd figure I'd bite, here's the thread context from reddit. 

>It is a huge problem for sure. There was that post last month even that showed that all reddit's main subs are moderated by about 10 super-moderators.
>
>I've basically replicated reddits moderation system, where the creator controls the community, curates the content, and appoints moderators to help in a hierarchy by added_time, and instance admins have ultimate control over all. In a sense this is mitigated by federation: lemmy is very light on resources, and everyone can just move to another better-moderated instance. But the main reason for replicating it, is the proposals for democratic moderation are very new and not-too-well worked out. Specifically, if there is an election of mods, how do you prevent a vote brigade? Or if its a community voting to remove a comment, what prevents a brigade on all community actions?
>
>We have a thread for discussion around more democratic moderation here. I'm not opposed to it of course, it just needs to be something well worked out.

From what you've said above, I'll summarize how I understood it.  

* Cabal moderators, astroturfing, abuse of power and general cyncism are issues under the current autocratic moderator system reddit has. 
* Democratic system was suggested. 
* Stack overflow was mentioned, but apparently dismissed with a vague "there are some problems with moderation" about it, with out explanation. 
* IIUC instead of moderators being in full control of what you view, everything stays, but you pick and choose which moderators you want to use as your "filter".  Current iterators of this idea are rejected due to how complicated it would be for the user (and possible implementation concerns?). 

### Additional Issues with Reddit Moderation

Before I continue discussion for possible alternatives to Reddit style moderation, I want to get into additional issues, besides the moderators themselves, of the current "Reddit System". 

Moderation on reddit is not scalable.  Subs become so large that eventually moderation has to grow, and even when the sub owner isn't a bad actor, it is hard to judge character in the quick amount of time it takes for some subs to jump from 10k to 100k subscribers.  These moderators often have so much crap pile in at one time, they can't deal with it at once, or don't get a sense of progress and become demotivated even if they did do enough to keep the sub running.   Because very few people have ultimate say in who becomes a moderator when in a sub, even the decision making process can become a bottleneck.  

I also don't believe Lemmy "being light" will do anything at all to fix this problem, sub reddits being easy to create on reddit doesn't fix the issues with authoritarian moderation either.  Among other issues, often a sub is so large, that most who visit don't even know what is going on (keeping the "bad" sub alive, keeping new users out of an alternative, with the old sub being far more visible).  Often a sub is subtly changed so that no such discussion about the horrible-ness of a moderation team can even be discussed anywhere near visibly towards that sub.  This brings us to another problem. 

Only subs that actually care have meta chats where one can actually talk about issues.  Many subs don't even have this.  Meta chats serve as a way to lower moderator resources and keep crap out of the main sub, while giving a clear outlet for users to talk about issues about a specific sub.   Meta "subs" aren't necessarily the best solution, but they are better than the rug pushing that currently happens on reddit, and help regardless of what type of moderation system you have (as long as they are *mandatory*).  

These are some issues related to reddit moderation I didn't see mentioned at all in previous discussion.  Now I'll talk about my actual opinions on solutions:

### Solutions

First I don't think filter moderation could ever work, for the same reasons as previously mentioned, but maybe the idea just isn't fleshed out enough.  I think no matter what you are going to get this weird cognitive overhead by trying to navigate "trust worthy" moderators, a complication the average user just isn't going to care about dealing with. 

Democratic moderation I think is a viable method of moderation, and I also think that this style of moderation already has a template that has solved most of the issues.  

I believe stack exchange works as a good blue print for democratic moderation.  Before I say anything else, I want to state the largest problems with stack exchange have basically nothing to do with moderator elections, and I want to make sure people don't try to conflate the recent drama with "The moderation system is failing".  They have nothing to do with each other.  

Brigading was previously mentioned as an issue with democratic moderation.  But this just doesn't happen on stack exchange.  I'll get into some of the reasons why this doesn't happens but also where there's some differences between SE and Lemmy that need to be addressed as well. 

* On stack exchange, you can view content, but can't do things like upvote, downvote, comment etc.. immediately with out first contributing.  On SE, that is either answering or asking a question.  On a site like Lemmy, this may be submitting well received posts, and posting well received comments.  

* Upvotes downvotes are used to give reputation.  They can also be used to *remove* reputation.    If Lemmy can limit upvotes/downvotes enough then maybe reputation would be purely based on this, but I could also see it being preferable if a post was merely gained "enough positive attention" or "high enough positive to negative ratio" that it counted as "one reputation unit" per community/instance, or might only be restricted to thread posts, or maybe have other restrictions or methods like time spent on sub, post limits at lower reputations like reddit already has.  This may also be something that should be configurable by the community owner.   

* Reputation is used as a way to mark "how well this person might do at curation activities" This democratizes the moderation before a moderator is even elected.  SE also has methods to ban you from performing these actions if you aren't doing it properly, either through auto bans when others don't agree, or with moderators explicitly banning you for a set period of time.  So the system is even self fixing if any bad actors manage to filter in.  This reduces moderator burden as well with actions like removing posts, handling flags, or fixing posts (editing other people's content, even with edit history may or may not be something Lemmy wants, I don't have an opinion on this).  During the recent exodus of moderators, exchange sites with out actual moderators were able to still survive using reputation level curation for months  before getting new mods IIRC.   This wouldn't happen on Reddit. 

* With out an even higher threshold of reputation from even upvoting/downvoting or basic privileges you can't even vote in moderator elections.   These thresholds effectively stop brigading unless you are actually a part of the community. They also stop brigading in ways that aren't related to moderation, like the lower level barriers on contribution. 

Using "contribution barriers" shifts the problem from brigading in democratic elections, which *has* been fixed on other platforms, to determining what should count as a unit of "reputation", of which I've laid out a lot of ideas, and I suspect they will need to be configurable per community by their respective owners.   Contribution barriers solve brigading completely because, if they have enough contribution to vote then they [aren't brigading by definition](https://xkcd.com/810/). 

Some notes about this system are:

* If you use reputation as a barrier, it can't be acquired super fast with out actually contributing.  A barrier must be placed basically along the act of giving reputation itself necisarily to stop the lowest common denominator from destroying a sub.   

* Elections are automated, on SE they take place once a year (different times per site though) with configurable numbers of mods elected.  Its a multi stage process where each person gives their pitch, there are multiple rounds of voting, and people have the opportunity to ask questions about the candidates.  This might also be another reason to have coupled "meta" communities, so that these processes do not fill the main sub. 

### Conclusion

Reddit style moderation (autocratic moderation) has more issues than previously discussed, including lack of transparency, coupled locations to list meta grievances or questions, and moderation scaling. In addition using "create another community" as a way to get around "bad" moderation won't work, because it doesn't work on reddit.  

I believe Democratic Moderation is a viable option to use instead of autocratic moderation.  Brigading isn't an issue if you've got a barrier to entry that makes some one not a brigader by meeting that threshold. Stack exchange shows such barriers are possible and and realistic for stable large long term communities.  These barriers also provide other benefits and gaurds against brigading that already happens on places like Reddit by limiting post frequency, what can be posted, and ability to upvote or downvote items.  These parameters should probably be able to be tuned by sub owners.  Additionally moderation may be democratized, not just via elections, but through users with higher engagement as well to loosen demands on moderator teams.  Finally there are many avenues for which these "barriers" which I've described as "reputation" can take, such as thread creation, post reception, time spent, and potentially even moderation activities themselves.

**Comment by wiki-me** [comment]
If anybody is interested, there was a [discussion](https://lemmy.ml/post/64315) on lemmy about it (but i don't want to overload this issue with information, feel free to delete this comment if you think it is irrelevant).
