### ISSUE TITLE
[Bug]: Scaled feed shows old posts and posts with zero votes

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#4178]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

![Screenshot from 2023-11-20 09-46-31](https://github.com/LemmyNet/lemmy/assets/126260333/56550559-9ce2-4b99-a6c4-216df923976c)

There are newer posts after those, but still many of them have zero votes.

### Steps to Reproduce

1. Select Scaled feed and reload page
2.
3.

### Technical Details

Firefox

### Version

BE: 0.19.0-rc.5

### Lemmy Instance URL

voyager.lemmy.ml

**Comment by Nutomic** [comment]
cc @dessalines @phiresky

**Comment by Die4Ever** [comment]
I was thinking an easy way to test this would be to look at a single community and switch to scaled sort, but lots of communities on Voyager are filled with 0 point posts, even browsing Top All Time

https://voyager.lemmy.ml/c/technology@beehaw.org?dataType=Post&sort=TopAll

**Comment by phiresky** [comment]
To debug it would be good to know what exactly the community.active_users_month and hot_rank and scaled_rank for one of those posts is.

**Comment by phiresky** [comment]
For posts older than a weeks hot_rank should be 0 due to `AND hours_diff < 168`. With a hot_rank of 0, scaled_rank should also be zero (regardless of users_active_month).

With both ranks zero, the posts in the screenshot should (a) sorted below all posts from the past week and (b) sorted chronologically.

So this could be because the scheduled update task for the rank doesn't run for some reason or something in the formula is incorrect. Hard to say without DB access

**Comment by phiresky** [comment]
This seems to be related to the default scaled_rank when a new post is inserted . If you look at the post IDs you can see that they are just now being freshly inserted into the database, potentially due to a vote happening without voyager knowing about it and it thus fetching the post. So their scaled rank is `0.1728 / log2(active_monthly_users)` until hot_rank updates to the correct values 15 minutes later (afaik).

Here's an example, one post that was created just now, and one that was created three months ago but inserted into the DB later

```
lemmy=# select * from post_aggregates where post_id in (13588, 13594);
-[ RECORD 1 ]-------------+------------------------------
post_id                   | 13588
comments                  | 0
score                     | 0
upvotes                   | 0
downvotes                 | 0
published                 | 2023-11-21 14:40:30.023686+00
newest_comment_time_necro | 2023-11-21 14:40:30.023686+00
newest_comment_time       | 2023-11-21 14:40:30.023686+00
featured_community        | f
featured_local            | f
hot_rank                  | 0.1728
hot_rank_active           | 0.1728
community_id              | 84
creator_id                | 6665
controversy_rank          | 0
instance_id               | 2
scaled_rank               | 0.3621
-[ RECORD 2 ]-------------+------------------------------
post_id                   | 13594
comments                  | 0
score                     | 0
upvotes                   | 0
downvotes                 | 0
published                 | 2023-08-25 01:09:15.521085+00
newest_comment_time_necro | 2023-08-25 01:09:15.521085+00
newest_comment_time       | 2023-08-25 01:09:15.521085+00
featured_community        | f
featured_local            | f
hot_rank                  | 0.1728
hot_rank_active           | 0.1728
community_id              | 2
creator_id                | 1409
controversy_rank          | 0
instance_id               | 2
scaled_rank               | 0.3621
```

**Comment by phiresky** [comment]
Probably the "default score" should be updated. Right now it is `Default for score = 1, active users = 1, and now, is (0.1728 / log(2 + 1)) = 0.3621`

Which means that a new post with 0 votes in a community with 0 subscribers will be ranked higher than any other post.

**Comment by Nutomic** [comment]
If it happens on voyager then the same problem will also happen on smaller or newly created prod instances. Wouldnt it be possible to adjust the default ranks so this doesnt happen?

**Comment by phiresky** [comment]
I think there is an issue there that also affects prod though - since posts with 0 votes from a community with 0 subscribers are ranked much higher they can easily dominate posts with > 0 votes from a community with > 0 subscribers (making the scaled feed easy to spam. See this screenshot - a recent post with 100 upvotes is below tons of posts with 0 upvotes:

![image](https://github.com/LemmyNet/lemmy/assets/2303841/aade48a4-db20-41d3-91cf-83ab83c3bc75)

Of course _kind of_ the intended way for scaled sort but maybe there should be some lower bound? e.g. smth. dumb like hard coding at least 2 votes, or hard coding at least 5 subscribers of a community?

**Comment by dessalines** [comment]
The current algo has no tweaking / scaling built in, [treating a vote the same way it treats an active user.](https://github.com/LemmyNet/lemmy/blob/main/migrations/2023-08-23-182533_scaled_rank/up.sql#L42)

I have a comment there about how we can tweak it, but I really think we should wait to see it in practice, on a popular server, before we start messing with it prematurely.

As far as lower bounds, I'm not sure... the point is to boost less active communities, so communities with 1 active user should be boosted above ones with 5 active users, and more.

**Comment by phiresky** [comment]
Sure, makes sense. But maybe we can adjust the default to be lower? This scaled_rank default of 0.38 is kind of the maximum it will ever be because when the rank starts going down a ton even when getting votes (as you can see in the above picture) because voted posts will also be in larger communities.

This is compared to the hot_rank default where a post immediately rises over the default value of 0.17 if a post gets a few votes.

**Comment by dessalines** [comment]
I spose the main issue is published being `now()` being used to set the default, not just for scaled_rank, but hot_rank also. A higher score means the numerator will still be higher.

But changing that default calculation away from `now()` could have some other weird results, like new posts not showing up above others until after 15 minutes.

`(hot_rank (score, published) / log(2 + users_active_month));`

**Comment by phiresky** [comment]
It's not *just* the issue of default published being now() but also of users_active_month being 0 or 1. That is another factor making any new unvoted post appear at the top of scaled. Both those factors cause scaled_rank to go lower after the first update, with only score going against it. This makes the issue more relevant than for hot_rank, where the score easily goes above the initial value, making an inaccurate default value less visible.

It also means that you'd probably almost never expect any posts to go above that initial value, which means those new posts will stick out more like a sore thumb (as opposed to hot_rank, where there's always popular posts with higher than initial score. 

I'm not sure of an ideal solution. My suggestion would be to just `ALTER TABLE post_aggregates ADD COLUMN scaled_rank float NOT NULL DEFAULT 0`. Posts will take a bit to show up but they will use an accurate value for score, time, community size when they do.

**Comment by dessalines** [comment]
It can't be exactly, zero, because the scheduled tasks ignore any rows that are zero (and the function sets any one > 168 hours old to zero), so that it doesn't scan the entire table every time.

Maybe as a better solution, we should maybe make those rank columns nullable and remove the default altogether, and have the scheduled tasks also run where that column is null. Then they would be ranked below anything else, until they get picked up by the hot_rank_update.

**Comment by Die4Ever** [comment]
I think null has unfortunate side effects like the posts either don't appear until the task runs, or they appear at the end even below old downvoted posts, until they suddenly jump way ahead when the first update task runs.

I think just reduce the default value to some middle-of-the-road value. The default value for hot sorting seems to work ok and it's a well tested approach in the real world, so the simplest thing would be to reduce the default scaled value down and keep all the logic the same. Looking at the list above I'd say something like 0.04

But that's just my 2 cents.
