### ISSUE TITLE
Protesting the removal of user scores from the API (Re: 3393)

### ISSUE THREAD

**Issue by asimons04** [LemmyNet/lemmy#4215]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?
User score aggregates were removed from the API in 0.19.0 in PR 4089.  The justification was that it was psychologically harmful.   

I am officially protesting this removal and asking for it to be reconsidered.

### Describe the solution you'd like.
Re-enable it at the API level and continue hiding it in Lemmy-UI if that is your personal stance on the matter.  Or, make it an option admins/users can disable at the instance/user level (there's already an option to hide scores, so maybe expand on that?). 

Other UIs _do_ utilize scores, and it is a useful metric for moderation.  

e.g.  If I load a user's profile to determine an appropriate mod action, and I see it is a 2 day old account with a combined comment/post score in the deep negative, I really only need to review a couple of submissions to confirm it is a troll account.  Not only does that save me precious time, it is also good for _my_ psychological health to not read through all that garbage.  

e.g. #2:  If someone posts a particularly toxic comment but their score to post/comment count ratio is high, I'm more likely to read through their history and conclude they're having a bad day or something.  Without the score, I _will not_ read through and likely just ban them and move on.  

### Describe alternatives you've considered.
Compile it back in for myself and anyone else who wants it, I guess?  😔

### Additional context
Considering how easy it is to spin up troll accounts or amass multiple troll accounts across multiple instances, removing a useful metric for identifying them at a glance is, IMO, completely irresponsible. 

If you don't want people to "game" it or don't like the idea of user scores, then make it optional and disable it on _your_ instance, but don't rip it out and impose _your_ preferences on instance admins and/or UI developers who want to utilize it.  

If it didn't already exist, that would be one thing.  But the fact is that a useful feature is being removed for fairly dubious reasons.  If a low score is the most psychologically harmful thing people see on Lemmy, then they should count themselves lucky considering some of the horrendous things admins/mods have to deal with.

**Comment by DraconicNEO** [comment]
I can see why you would be frustrated with it, however the problem is that if we have this metric easily available to users and bots the same problem of karma requirements and Karma shaming that happens on Reddit will end up happening on Lemmy.

The problem with Karma requirements is that it punishes people for having unpopular ideas, it weaponizes downvoting against users and it directly encourages vote manipulation and vote farming, which obviously has a negative effect.

Also unlike Reddit score restrictions aren't going to actually limit malicious users, who can simply spin up accounts on other instances across the lemmyverse and upvote their own content multiple times to get the required amount of score.

It also works in the inverse, where the malicious user sets up other accounts and downvotes an innocent user to kick them out of a community.

It is for that reason that I agree with them that this feature shouldn't be readily available and abusable by every single instance out there.
