### ISSUE TITLE
[Bug]: Mods/admins can mark comments other than their own as distinguished

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4216]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

While working on [this UI PR](https://github.com/LemmyNet/lemmy-ui/pull/2258), I noticed that the API allows mods and admins who aren't their own.

### Steps to Reproduce

1. Make API request to distinguish someone else's comment using the JWT for an admin or moderator account.
2. Receive successful response

### Technical Details

N/A

### Version

0.19.0-rc.11

### Lemmy Instance URL

local

**Comment by asimons04** [comment]
I use that, so I'm going to say "not a bug".

Distinguished is just a flag.  Lemmy-UI treats it as "speak as mod" (which is redundant since mods already have badges), but the API is just a boolean flag to distinguish it.

In Tesseract, it's used by mods/admins to distinguish _any_ comment and sticky it at the top.  Think a particularly insightful comment that clarifies a clickbait article.

**Comment by asimons04** [comment]
:-1:

**Comment by asimons04** [comment]
Why is this in issue? Mods/admins _should_ be able to distinguish any comment.  Just because Lemmy-UI treats it differently?

**Comment by aeharding** [comment]
@asimons04 to your own point, in Voyager distinguishing a comment of a normal user would make them appear as a moderator, which isn't ideal.

Sticking a comment from a user at the top (without distinguishing) feels like it could be a new feature :)

**Comment by asimons04** [comment]
Then they should make a new flag for speak as moderator. Distinguishing comments, from anyone who the mod/admin thinks said something insightful, is a very useful feature.

Treating the distinguished flag as "Speak as moderator" seems redundant since mods can already be badged based on their mod status flag.

Ultimately, I no longer care.  This is the final straw for me, and I've decided to stop development of Tesseract since everything I do to improve the Lemmy experience is being undone piece by piece by the latest changes to the API.

**Comment by aeharding** [comment]
> Treating the distinguished flag as "Speak as moderator" seems redundant since mods can already be badged based on their mod status flag.

I agree in lemmy-ui it is strange how moderators are always tagged as moderators, regardless of distinguished status. In Voyager and Reddit for example, the distinguished flag is so that mods can participate in a conversion without being labelled as a mod, and then mods can distinguish their own comments for specific mod duties.

> Ultimately, I no longer care. This is the final straw for me, and I've decided to stop development of Tesseract since everything I do to improve the Lemmy experience is being undone piece by piece by the latest changes to the API.

:( That is unfortunate, I saw Tesseract a few days ago and its a great client! You should be very proud of why you built! 💙

**Comment by asimons04** [comment]
>:( That is unfortunate, I saw Tesseract a few days ago and its a great client! You should be very proud of what you built! 💙

Thanks, and back atcha with Voyager!  I am proud of it, but I can't stand to watch it die a death of 1000 cuts by all the API changes that seem to force Lemmy-UI's way or the highway.

**Comment by dessalines** [comment]
Distinguish was meant to mean "speak as moderator", not "sticky this comment to the top". What you're talking about is something different, like `pin` or `sticky` , and would need to be added separately.
