### ISSUE TITLE
Blocking communities and users

### ISSUE THREAD

**Issue by Granitosaurus** [LemmyNet/lemmy#426]
It would be nice if you could block communities from appearing in the "all" section. I'd like to discover some new communities to follow but there's a bit of spam coming from `test` community which I understand the purpose of but I don't really want to see it.

**Comment by methylprednisolone** [comment]
yup, I guess most people discover interesting communities there, but any posts you make are very soon drowned by spam-ish posts from c/test

**Comment by dessalines** [comment]
1 thing I can do in the short term is decrease the posting limits. Right now you can do 6 posts every 10 minutes, I'll lower it to 6 posts an hour.

**Comment by dessalines** [comment]
It'll pry be a while before I get to this, because its a big undertaking.

**Comment by Nutomic** [comment]
So this is for blocking from the user perspective, or from the admin perspective? Cause both of them are important.

**Comment by dessalines** [comment]
I guess admins just banning a community (which blocks it from being seen on the front pages and new things being added to it) would already be an "admin block"

For a user blocking a community it would take adding another table similar to `community_follower` or `community_user_ban`, IE `community_block`, with the schema `id, community_id,user_id, published`.

For a user blocking another user, same but two user_ids.

Both would affect every view we have, since if you block a user, you don't want to see their posts, comments, communities, etc. And if you block a community, you don't want to see its posts.

UI concerns would be where and how to block both.

**Comment by heylix** [comment]
Cross-posted from #1629 since it got closed as duplicate, but I think I outlined a possible user blocking feature in a pretty detailed way over there:

### Is your proposal related to a problem?

Some users don't go well with others. It's hard to deescalate and not interact with people if you see their comments and reactions everywhere. Some can cope better with provocations than others. It would be nice if you could help the "others" by providing technical features to support ignoring users on the site.

### Describe the solution you'd like

I once saw a forum based on vBulletin where you could add users to your ignore list. This had the following effects:

- you didn't get notifications when they commented on one of your posts
- you didn't get notifications for messages
- every post or private message they wrote was hidden.
  - the comment/message text was replaced with *User heylix is on your ignore list.* with two buttons next to it:
    - show anyway – which showed the text of the post/message until you reloaded the page
    - go to your ignore list – which enabled you to remove them from your ignore list.
      - this button added an URL parameter to the ignore list page which highlighted their username so you could find it if you ignored many users
- if you went to your "recent posts" list, comments by those users weren't listed.
- if you looked at the forum view, topics with no new posts other than those by ignored users were considered "read".
  - this meant that the link which was usually bold when new comments were made, wasn't bold
  - it also meant that the small indicator who made the last comment didn't include ignored users.

### Describe alternatives you've considered

There could be a feature to completely hide all interactions with the user, not even showing the user name itself. This removes context in many situations where the hidden comment has answers which reference it.

You could also leave the burden of ignoring people on the users being bothered by others. This wastes their time because they accidentally read the comments from people they want to ignore and it may enable emotional reactions.

Reporting users to the mods or admins for them to ban them only creates more drama. You could additionally report them, though, if they're violating the rules of the instance/community.

### Additional context

#### Relevant posts on the main Lemmy instance:

- [What do you think about recent events on c/worldnews? Should we try to prevent such behaviors?](https://lemmy.ml/post/68017)
- [@soferman@lemmy.ml banned on !worldnews@lemmy.ml for hostile behaviour](https://lemmy.ml/post/68605)

#### Relevant literature:

- [Trolling in Online Discussions: From Provocation to Community-building](https://www.researchgate.net/publication/269652088_Trolling_in_Online_Discussions_From_Provocation_to_Community-building). Hopkinson, Chris. (2013). Brno Studies in English. 39. 5-25. 10.5817/BSE2013-1-1.<br /><blockquote>Trolls’ opening moves […] can be seen as dropping ‘bait’ into the water and waiting for the in-group members to ‘bite’. […] If this strategy is successful, a ‘flame war’ may ensue […]</blockquote>
- [How to Stop Caring About Trolls and Get On With Your Life](https://lifehacker.com/how-to-stop-caring-about-trolls-and-get-on-with-your-li-5854053). Gordon, Whitson (2014). Lifehacker.com.<br /><blockquote>While I highly recommend avoiding the trolls at all costs, if you accidentally get yourself lured into a discussion, you can either try avoiding, or attempt to fizzle out the argument yourself.</blockquote>
- [Ignore feature - an open discussion](https://www.dndbeyond.com/forums/d-d-beyond-general/general-discussion/110296-ignore-feature-an-open-discussion). UrthTheThoughtless (2021). D&D Beyond forums.<br /><blockquote>To me, the ignore feature needs to be available as a tool for users to protect themselves from abuse.</blockquote>

---

I'd like to add that the "hidden post" feature is already in the user interface as the small minus on the side of the comment which folds in the comment chain. Comments by ignored users may be "folded in", but I'd really like to read the answers to said users, so there could be a difference to folding the complete comment chain to folding single comments by blocked users. I didn't really read the code so I don't know how hard or easy this would be to implement.

**Comment by Houkime** [comment]
While there seems to be community blocking support code added in closing commits, and I can ignore separate users, I do not see any interface for hiding communities at personal level. At least at UI: 0.16.5 BE: 0.16.4 (fapsi.be)
Where is it exactly?

**Comment by Houkime** [comment]
nevermind, there is an open issue in ui https://github.com/LemmyNet/lemmy-ui/issues/396

**Comment by Nutomic** [comment]
@Houkime You can block both users and communities in the "block" tab under /settings.
