### ISSUE TITLE
Include the admins of the reported user's instance in who gets reports

### ISSUE THREAD

**Issue by Ategon** [LemmyNet/lemmy#4286]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently its difficult to moderate users on your own instance interacting on other instances and you need to be in contact with other admins for them to report site bannable behaviour going on in other instances

### Describe the solution you'd like.

In addition to sending reports to the admins of the instance the community is on and the admins of the user that reported, it should be sent to the admins of the user that ended up getting reported as they are the ones managing that person

### Describe alternatives you've considered.

escalating system where it can be escalated to the admins of the user that got reported. Could end up having bad actors get away for a much larger period of time and would be more complicated to both implement and use (and would rely on other people being active and then when they send for the other admin team to be active leading to two points of failure to catch people quick)

Not sending it would mean the old system of admins talking to each other manually which is extremely slow and inefficient

### Additional context

4 sets of people would get the report
- admins of the user that posted (new)
- admins of the user that reported
- admins of the instance the community is in
- mods of the community

**Comment by DraconicNEO** [comment]
I think this is a very important thing to have. Many malicious users get away with bad behavior for long amounts of time that they otherwise wouldn't due to reports not being sent to their home Server. 

I think it might be a good idea to include what Mastodon does in this situation where they have the option to forward reports to other associated servers in the report form, for example if a user from sh.itjust.works is causing trouble in a thread on lemmy.ml and other users from lemmy.world and lemm.ee have participated, when reporting that user's comments the form would give the option to forward their report to the servers of the other participants in addition to the home Server of that user. This makes sense because their activity is copied to all of those servers. 

However I do believe that that should be optional the way that it is on Mastodon where you explicitly choose to forward reports or not since there are situations where you only want to share the report with the instance that you are on.
