### ISSUE TITLE
Keep mirrors in sync with commits on the github repo

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4407]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

During the AMA, some people brought up hosting the code somewhere other than github. While waiting for forgejo to implement federation, it would be good to make sure the existing mirrors on gitea and codeberg are kept in sync with what is on github. The codeberg mirror is 4 months out of date, and the gitea mirror is 3 years out of date.

### Describe the solution you'd like.

Push code to mirror repos during CI after merging a PR.

### Describe alternatives you've considered.

Updating the mirrors manually occasionally.

**Comment by dessalines** [comment]
I forgot why I removed these from `origin` earlier (probably because they had downtime), but I've put them both back in my github repo now, IE:

`git remote set-url origin --push --add https://git.join-lemmy.org/LemmyNet/lemmy`

Both repos are updated.

Codeberg has pull mirroring disabled, so we wouldn't be able to update it based on the github PRs. But my local repo pushes to all 3 now.
