### ISSUE TITLE
[Bug]: Users can't enable 2FA

### ISSUE THREAD

**Issue by corgana** [LemmyNet/lemmy#4518]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When clicking "Enable Two-Factor authentication" users get a GUI error: `couldnt_generate_totp`

Also `POST /api/v3/user/totp/generate HTTP/1.1` is returning a 400 error.

![Screenshot from 2024-03-07 19-38-13](https://github.com/LemmyNet/lemmy/assets/16600225/b144e4fe-8097-4425-b735-6c149a0a9a43)

### Steps to Reproduce

1. Open user settings
2. Click "Enable Two-Factor authentication" button

### Technical Details

Tested on Chrome/Firefox/Edge Linux/Windows/MacOS

### Version

BE 0.19.3

### Lemmy Instance URL

https://startrek.website

**Comment by Nutomic** [comment]
Can you ask your instance admin to grep the server logs for this message, and look for any additional info?

**Comment by corgana** [comment]
I believe we found the cause, here's the relevant bit:

`CouldntGenerateTotp: Issuer can't contain a colon. "Star Trek: Website" contains a colon`

We tested by removing the colon from the name, and it works. So for the time being we'll stay colon-less, like Star Trek Into Darkness.

[totp-log.txt](https://github.com/LemmyNet/lemmy/files/14540548/totp-log.txt)

**Comment by dessalines** [comment]
This is probably an issue for [totp-rs](https://github.com/constantoine/totp-rs) then, since all we're doing is passing your site name as the issuer to their function. Would be good to open up an issue there, but colons are protected chars in urls and filesystems, so I usually just use `-` wherever I would use a colon.

**Comment by dessalines** [comment]
@constantoine certainly, is there a list of protected characters for the totp url format besides `:` ?

**Comment by Nutomic** [comment]
That sounds like we should really use the domain as `issuer`.

**Comment by constantoine** [comment]
Since everything else can be url-encoded, it's okay. Any valid character per the URL RFC is accepted. Colon is actually the only one than is unaccepted because it's used as cutoff. There could be ways to be smart about this, but the Google papers just went the "issue can't contain colon" route to avoid making parsing more complex than it needs to be

It doesn't necessarily have to be the domain name, but it will certainly simplify things, on top of making sure 2 websites can't have colliding issuers
