### ISSUE TITLE
Use a single RSA keypair for all users and communities

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#4530]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Lemmy currently creates and stores a separate RSA keypair for each user and each community. These keys are used to sign activities which are sent between instances. Now Soapbox had the idea to [get rid of all these separate keys](https://socialhub.activitypub.rocks/t/how-i-saved-gigabytes-by-deleting-all-rsa-keys/3983), and only use a single keypair for the entire instance.

This makes a lot of sense because all these keys take a lot of space, and are really not necessary. Like Soapbox, we could simply use the same keypair for every user and every community.

**Comment by Nutomic** [comment]
We already have a keypair for the instance actor which is stored in `site` table. So we can use that same keypair for all users and communities.

**Comment by phiresky** [comment]
This _might_ be feasible, but I'd definitely be a lot more cautious about this than you or the OP in the socialhub, who seems to be writing from the perspective of someone building a new software that doesn't yet have (m)any users.

Firstly, doing this for existing users isn't really feasible at all from what I see because neither lemmy nor probably most other AP software has any mechanism for updating the privkey of users. So if you do this, you instantly lose federation with all other (non-updated) instances as they start rejecting all messages from your users and you start rejecting all of theirs.

Secondly, as the OP mentions in only a tiny side-sentence, this **completely breaks Client-To-Server activitypub** - which in the extreme case would be instance-less and in a milder sense would be clients having more control over themselves than relying 100% on instances. Lemmy isn't really made for this anyways currently, but this would kind of completely discard the idea that people are individual actors with individual control. As an example one thing I was thinking about recently is account migration:

If a user has actual control over their keypair, then verifyable account migration is possible even when the old instance is completely dead. A user can sign a "account migrated" message with their private key that they exported from their old account, and federate that migration message to all other instances so they can update their profile to point to the new one. Or, more conveniently, the key can be part of the "export" function and they can upload their "export" package that lemmy already has to the new instance , and the new instance can federate out the migration message from their old keys.

Another thing that IMO is something how lemmy should ideally work: A user should be able to manage their own private key, and when they interact with lemmy-ui or an app, they would themselves sign their own activity and let the instance federate it. **It is possible to structure lemmy in a way where instance owners have no actual power to manipulate user actions**.


Maybe an alternative is to start using ED25519, which has key sizes of around 10% storage than RSA keypairs with same or better security.

**Comment by Nutomic** [comment]
> Firstly, doing this for existing users isn't really feasible at all from what I see because neither lemmy nor probably most other AP software has any mechanism for updating the privkey of users. So if you do this, you instantly lose federation with all other (non-updated) instances as they start rejecting all messages from your users and you start rejecting all of theirs.

When receiving an activity and the signature check fails, we could simply refetch the actor profile with the new pubkey.

> Secondly, as the OP mentions in only a tiny side-sentence, this completely breaks Client-To-Server activitypub - which in the extreme case would be instance-less and in a milder sense would be clients having more control over themselves than relying 100% on instances. Lemmy isn't really made for this anyways currently, but this would kind of completely discard the idea that people are individual actors with individual control. As an example one thing I was thinking about recently is account migration:

Lemmy doesnt support client-to-server apub at all, and there isnt even a feature request for this. So it doesnt make sense to use so many resources for something that isnt supported. It would be possible to add a feature later for individual users to upload their own keypair, while most users would still rely on the single instance keypair.

> Maybe an alternative is to start using ED25519, which has key sizes of around 10% storage than RSA keypairs with same or better security.

Worth investigating in a separate issue if this compliant with the protocol and compatible with other platforms.

**Comment by Nutomic** [comment]
This is similar to https://github.com/LemmyNet/lemmy/pull/5049 and would be difficult to implement for the same reason. Namely the ActorType needs to return the private/public key but cannot make a separate db query. So it would either require very complicated changes in Lemmy, or ugly changes to the library api. Anyway the storage used for keypairs is very minor compared to all the post markdown, so Im gonna close this.
