### ISSUE TITLE
Stop storing settings specific to a UI

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4799]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently, the database stores settings that only relate to specific UI clients. I'll go into more detail in the next section. I see this as an issue because it presents a red herring for client developers and, if they want to to have an option for a setting that isn't supported on the server, need to store info in their UI anyway.

### Describe the solution you'd like.

While the divide between options that affect a UI and ones that don't is somewhat blurry, I have a rule of thumb that can help us identify what doesn't need to be stored in the server DB: is the setting controlling ***what*** is displayed, or ***how*** it's displayed. Going through some of the settings in both camps.

**What**
- blur nsfw
- show avatars
- default sort type
- default listing type

**How**
- theme (default and per user)
- infinite scroll
- post listing mode (default and per user)
- enable keyboard animation

Definitely need to hash these out more. Would also be good to get input from other Lemmy client developers on if this would be helpful to them.

### Describe alternatives you've considered.

Living with how things are.

**Comment by dullbananas** [comment]
After OAuth is added (#1368), a new table `client_data` should be added with columns `local_user_id`, `client_id`, and `data` so custom settings can be stored

**Comment by SleeplessOne1917** [comment]
I don't think the clients OAuth is referring to are the kind of client I'm talking about. From what I understand, OAuth allows services like GitHub, Google, Amazon etc. handle the username and password while Lemmy doesn't need to store this information. This seems completely unrelated to the issue.

**Comment by dullbananas** [comment]
The issue I linked to is about how Lemmy clients get access to a Lemmy account. The part that's relevant here is the client ID, which would allow the data stored by Lemmy clients to be securely separated.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/3584 has some previous discussion about this.

**Comment by dessalines** [comment]
IMO the lines are so blurry, that we shouldn't even try to make rules around what UI-type settings apps should store themselves, vs what the lemmy back-end can store on their behalf. 

Rather than try to come up with complicated rules and tests for which things the back-end shouldn't store, I think we should be extremely flexible w/ regards to settings, and add any fields requested of us, even if the back-end doesn't directly need them. 

Even a setting like `font_size` for example could even be universalized across apps and web-UIs, if the unit is density/scale independent pixels. Then no matter what web-UI or app you use, your experience would be uniform.

I know its annoying to do DB migrations for each setting addition, but optional settings additions are non-breaking changes, and I can handle adding these easily on request.

I'm also a little hesitant to ever say "the lemmy back-end should **not** store this setting", because then apps will start differentiating themselves as having specific "killer features", because we refused to support that setting. A lot of apps already do this of course, but we shouldn't be the blocker forcing them to intentionally have unique settings that lemmy won't support.
