### ISSUE TITLE
Blocked Score Feature

### ISSUE THREAD

**Issue by BlackTopHat0** [LemmyNet/lemmy#5040]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

No problem.

### Describe the solution you'd like.

I would like to see a block score on users and communities so that I can exercise greater caution. I will act differently between a user/community blocked by 10 people versus a user/community blocked by 100,000 people.

### Describe alternatives you've considered.

None. I want the blocked score feature.

**Comment by Nutomic** [comment]
Information about blocks is not meant to be public.

**Comment by DraconicNEO** [comment]
The way blocking works on Lemmy there would be no merit in that since people block others on lemmy as part of feed curation. 

However if a stronger version of blocks for harassment was introduced (i.e. #4205) this could make sense, not for public users though, probably would be better for admins and mods to be the only ones that see that, and probably only local ones at that, otherwise it could be abused as a harassment vector. Also could be abused to harm the person's reputation if trolls decided to make many accounts and all block the person.
