### ISSUE TITLE
Allow users to optionally display their upvotes and downvotes

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#518]
I think it'd be a good idea to give users the option to display what posts and comments they voted on and in what direction. Any thoughts?

**Comment by dessalines** [comment]
I don't see this being useful. If you want to remember posts or comments there's already a save feature. Showing your votes as activity in your user page would clutter up things a lot.

**Comment by StaticallyTypedRice** [comment]
In response to cluttering, it would be in a different tab in the userpage.

**Comment by AndreVallestero** [comment]
@StaticallyTypedRice That would still clutter the "Overview" tab with upvotes and downvotes which would make it harder to look through other user activity.

I'm not sure if this is any better from a UI and UX standpoint, but  would give the user more fine control if a filtering system was used instead of a tab select system.
![image](https://user-images.githubusercontent.com/39736205/74752699-16f72600-523d-11ea-9e0a-dc668e96020d.png)

**Comment by StaticallyTypedRice** [comment]
> @StaticallyTypedRice That would still clutter the "Overview" tab with upvotes and downvotes which would make it harder to look through other user activity.
> 
> I'm not sure if this is any better from a UI and UX standpoint, but would give the user more fine control if a filtering system was used instead of a tab select system.
> ![image](https://user-images.githubusercontent.com/39736205/74752699-16f72600-523d-11ea-9e0a-dc668e96020d.png)

I meant put the upvotes and downvotes on different tabs from any of the posted content. That's how Reddit does it.
