### ISSUE TITLE
Question: Why wasn't the issue #5234 commit included in version 0.19.8? 

### ISSUE THREAD

**Issue by giorgi3092** [LemmyNet/lemmy#5262]
### Question

https://github.com/LemmyNet/lemmy/issues/5234

This issue was committed two weeks ago and now I upgraded my instance and it seems that issue was not integrated into this release. Newly registered user still does not have all the languages loaded that are configured in /admin. I am curious how does this work, don't all commits make it to the release?

**Comment by Nutomic** [comment]
The main branch now has a lot of breaking changes, so complicated to backport some changes. In this case there was a major rewrite of the same file from adding SSO support (https://github.com/LemmyNet/lemmy/pull/4881). For the release I only backported changes which resulted in no or minor conflicts. Otherwise a wrongly backported change could cause bugs on its own, and its not worth the risk. If you really want this change on your instance, you can compile Lemmy from source.

**Comment by dessalines** [comment]
Yep, this will have to wait for the next release.
