### ISSUE TITLE
Hide or delete all posts/comments from user when they are banned

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#557]
Banning a user doesnt remove their posts or comments, so it seems that mods have to do this manually. Would be very helpful if this could be done automatically (maybe via a checkbox to make it optional).

**Comment by dessalines** [comment]
There are also two types of bans, a community ban, and a site-wide ban.

I think I'd like this button to be on their user page, so that you can also undo it easily. But this would only work for site-wide comments... I'm not sure how to best handle removing / unremoving all comments for a user for a specific community you moderate, in the UI.

**Comment by dessalines** [comment]
I added this as an option on their ban form when you're banning them. And by default, an unban restores all their comments.
