### ISSUE TITLE
Handle timezones

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#594]
We need to handle full datetimes including timezones. This is necessary for federation because there will be communication between instances in different timezones.

**Comment by dessalines** [comment]
Everything is in UTC / naivedatetime, and the front ends convert from UTC to the system / browsers local timezone.

**Comment by phiresky** [comment]
there's a federation issue now where kbin posts are two hours in the future due to time zone interpretation issues. how sure are we that it's not an issue on 

> Everything is in UTC / naivedatetime

To be clean, everything should definitely still be `timestamptz` in the database and `chrono::DateTime<Utc>` in rust, not timestamp and naive date time.
