### ISSUE TITLE
Add Email Verification

### ISSUE THREAD

**Issue by Toxu-ru** [LemmyNet/lemmy#720]
Add the ability for the administration of individual instances to enable e-mail verification at its discretion.  

The amount of spam on popular resources is often disastrous. Captcha and email verification can make targeted spam attacks much more difficult.

**Comment by TheCreeper** [comment]
Regarding Captcha, would a "proof of work" be a viable alternative instead of asking the user to complete a puzzle?

https://scottpeterjohnson.github.io/hashwall/dist/

**Comment by Toxu-ru** [comment]
I agree about the Captcha. There are many doubts and questions about its use.

https://github.com/LemmyNet/lemmy/issues/638

**Comment by ptman** [comment]
[hcaptcha](https://www.hcaptcha.com/)? (instead of recaptcha)

**Comment by Nutomic** [comment]
@ptman I dont like to use something that depends on an external server.

**Comment by ptman** [comment]
I must be optional. But in order to fight spam, which has great volume, and sometimes profit motive, a single instance admin or open source project developer doesn't necessarily have enough capacity to deal with it well. I believe cloudflare moved from recaptcha to hcaptcha after having evaluated several options.

Ideally, there would be a federated open source captcha usable for any and all services, but until then something else will have to be used.

**Comment by dessalines** [comment]
I'd want it to be something self-hostable, ideally a dockerized thing.

**Comment by ptman** [comment]
Some ideas: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/46548 and https://github.com/vector-im/riot-web/issues/3606

**Comment by dessalines** [comment]
We've added captcha instead.
