### ISSUE TITLE
Suggestions: translations, and share with... button, 

### ISSUE THREAD

**Issue by mitcoes** [LemmyNet/lemmy#728]
-Translations 
tools https://opensource.com/article/17/6/open-source-localization-tools
Choose some to automatic translate and other to fine tune translations with users

Also a translate with .. Google / Deepl / etc words, sentences and pages 

And select languages you know, + translate posts in other languages to ...

- Share with ... 
Mastodon / Friendica / /Pixelfed / GNU social / Diaspora 
and also with Twitter / WA /Signal / Telegram "button"

-

**Comment by dessalines** [comment]
I'm not sure about embedding a translator into lemmy itself... I think this is something that is better handled by browser plugins.

`Share with` buttons always seemed hacky to me, because there's a never ending list of services that have to be added. I'd only consider adding it if it was hidden beyond a share to menu.
