### ISSUE TITLE
Support user following (twitter-type feed)

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#752]
This would allow users to not just follow communities, but also to follow other users, ala twitter / mastodon. User posts / comments would then show up in your front page feed.

This would also complete the connection to mastodon and the rest of the fediverse, which is based on user-follows.

**Comment by kixiQu** [comment]
Maybe something to consider: Facebook has both user posts visible to "friends" (let's say followers of that user), and posts into communities. Lemmy could have the equivalent of the first, posting outside of a community, such that only people who followed you would see it. It's a product design choice, of course, but I can see it smoothing adoption for people who have friends on the wider Fediverse.

**Comment by je-vv** [comment]
Does this user following feature, contemplates as well being able to post not to any community, but to oneself, like posting to u/<my_username>?  This would be pretty useful to keep staff valuable for oneself, and that some followers might find interesting, but not any specific community...

**Comment by dessalines** [comment]
Yes, user-following includes community-less posting / commenting. I'm not sure if we'll follow the reddit term of having these toots/tweets be "self-posts" to your user page, but lemmy will include them.

**Comment by je-vv** [comment]
One more thing, would the front page, when selecting the "subscribed" filter, I'm guessing the followed users post will be part of it, as well as subscribed communities...

**Comment by dessalines** [comment]
Yeah, your front page would include followed users posts like a timeline along with the community posts.

**Comment by lboklin** [comment]
Will user posts be sorted just as normal posts? i.e. 
* chronologically if sorting is set to _new_, 
* by recent replies if sorting is set to_activity_, and 
* by favourites and other interactions if set to _hot_

On that last point regarding various interactions: how will those be translated? 
* Would boosts be represented as a link post to the original? I'd ideally like to see them be a sort of repost but with upvotes and such shared between all of them (so that they're properly sorted in _hot_, for example), and merged if there is more than one in your feed
* I assume favourites/likes would translate into upvotes
* [Tangential] Will Lemmy support reactions or the like? Pleroma has those, IIRC?

One of the things I miss on mastodon is the ability to sort by "hot" or "top". It's too easy to miss out on big news and hot topics if you skip over even just a few hours of your feed as it becomes unmanageably noisy sometimes. Another thing is Lemmy's threaded conversations, which is not handled very well anywhere else. So I'm actually hoping Lemmy can eventually replace mastodon for me.

**Comment by dessalines** [comment]
Sorry, just seeing this now.

> Will user posts be sorted just as normal posts? i.e.

The sorting should be able to work just like post sorting, every toot has a score and a published time, and a most recent comment time, that's enough to do hot rank, active, and all the others.

> Would boosts be represented as a link post to the original?

I've never considered boosts tbh. I spose they could be like a user posting a link to someone elses toot on their own user page, and if you've subbed to that user, you'll see that "boost" on your front page as well.

> I assume favourites/likes would translate into upvotes

Yep. Lemmy has downvotes too, which I imagine the other services would disregarde.

> Will Lemmy support reactions or the like? Pleroma has those, IIRC?

I do really want to add reactions, I use them on every platform, but we have other priorities at the moment.

**Comment by Nutomic** [comment]
We can also just ignore boosts, at least in the beginning. User following and federation with Mastodon would already be complicated enough.
