### ISSUE TITLE
Add support IPFS

### ISSUE THREAD

**Issue by KonoromiHimaries** [LemmyNet/lemmy#803]
```
https://github.com/rs-ipfs/rust-ipfs#readme
```

related https://github.com/LemmyNet/lemmy/issues/210#issuecomment-522281417

**Comment by kolgza** [comment]
I've wondered about this before. [In fact, I've made a post about this](https://dev.lemmy.ml/post/34024). However, in the end, I didn't quite think that IPFS was ready. Regardless, I do like the idea of having images and other media being served with IPFS.

What I find more interesting, however, is [IPWB](https://github.com/oduwsdl/ipwb). Lemmy allows users to archive links with archive.is, but what if something like this was used instead?

These are just my musings however. I have a difficult time wrapping my head around all of the experimental things people are doing with IPFS in order to make it more than just distributed file hosting—[Textile](https://docs.textile.io/), [Pubsub](https://blog.ipfs.io/25-pubsub/), etc.

**Comment by dessalines** [comment]
This is more relevant for our image host, pict-rs, than it is for Lemmy.

**Comment by NatoBoram** [comment]
IPFS is not only for storage, it's mainly about delivering the content. Lemmy would need to know if the user has an IPFS node somewhere and then change the URL of IPFS-hosted images to something like `localhost:8080/ipfs/<image-hash>` so that end-users that use IPFS can fetch it via IPFS and seed it

**Comment by KonoromiHimaries** [comment]
See
```
https://github.com/plebbit/whitepaper/discussions/2
```
