### ISSUE TITLE
Swap out pictshare for pict-rs

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#806]
Use [pict-rs](https://git.asonix.dog/asonix/pict-rs/) instead.

**Comment by InstanceOfMichael** [comment]
Does pictrs support S3 compatible APIs? [pictshare](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/CONFIG.md) does. I couldn't find any reason for this change, otherwise this is a regression.

**Comment by dessalines** [comment]
Pictshare had a faulty docker setup, was written in php and was full of memory leaks, to the point that it would eat up all available ram on our server.

pict-rs is a lean image server written from scratch in rust, by a dev who also works on lemmy.

We're not interested in compatibility with amazon storage, everything in lemmy is self-hosted.

**Comment by InstanceOfMichael** [comment]
"S3 compatible" means it can use a large range of providers such as GCP, B2, digital ocean, wasabi, etc. which a lot of potential server admins would prefer, especially for long-term accumulation of images.

**Comment by gellenburg** [comment]
Sorry for bumping this but I just came across this looking for info on S3 storage in Lemmy before opening up a separate issue/ feature request. :-)

> We're not interested in compatibility with amazon storage, everything in lemmy is self-hosted.

I'd just like to add that having S3 compatible storage is a *must* in 2022. Mastodon, Pleroma, Pixelfed, and I even believe PeerTube allow media to be stored on an off-site S3 compatible storage provider. I use Linode Object Storage. But Hetzner has their own S3 compatible Block Storage. OVH. Vultr too.

Having this support saves costs on hosting (block storage is usually MUCH cheaper than increasing the local storage on a VPS. Otherwise then you need to constantly increase the disk storage on your VPS.

If you're not going to support external storage there needs to be a way then to prevent *any* media then from being stored on Lemmy and force users to upload their media another way.

**Comment by Nutomic** [comment]
Image storage is completely handled by pict-rs. It looks like there is already support for object storage, you should give it a try.

https://git.asonix.dog/asonix/pict-rs/
