### ISSUE TITLE
Redirect links from Youtube to Invidious, and from Twitter to Nitter

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#821]
This might be a nice optional feature to have at some point. Basically a user setting where you can rewrite the domain for any links clicked. In the UI it could be a table like this:

|  enabled | domain to replace  | new domain |
|---|---|---|
|  true |  youtube.com | invidio.us  |
|  false | twitter.com  | nitter.net  |  

So in this case, this user would get any links to `youtube.com` into `invidio.us` links. Whether in post links, comments or private messages. Of course we would have to avoid overloading any single instance.

**Comment by dessalines** [comment]
Some overlap with #768 , and maybe clearURLs if it ever gets made into a library, might have these.

It might also be nice to have a rust library for these, but I wouldn't want to maintain it, because there are so many trackers to keep track of (heh). 

It'd be nice if it was a cross-language thing like regex so that it could easily be exported to any language / project.

**Comment by Nutomic** [comment]
This issue here would be really basic, just a user configurable list of domains that get replaced. You dont need any regex or library for that. 

#768 also wouldnt be that complicated, you just remove all query parameters that start with `utm_`.

**Comment by dessalines** [comment]
Nice, looks like the clearUrls data is in json and regex: https://gitlab.com/KevinRoebert/ClearUrls/-/blob/master/data/data.json

**Comment by dessalines** [comment]
Reopening this, as now bots are imperfectly doing this with comments.

**Comment by kartikynwa** [comment]
There is this service called farside.link which was created because of the ephemeral nature of these instances. Putting this out in the unlikely scenario it is found helpful.

**Comment by dessalines** [comment]
Yeah that's actually extremely helpful, especially since it can use the original links.

@Nutomic what do you think? Maybe a server setting with some description? And then do you think this re-writing work should be done on the front end, or back end?

**Comment by Nutomic** [comment]
I agree that we should store original links in the database and convert when rendering. However a server setting wouldn't be enough because every instance would have some users who want to use these redirects and others who don't. A user setting would also not be sufficient, because someone might want to use twitter via nitter, but access youtube directly. Or use mobile apps like newpipe which need the original youtube link.

So I think the best solution is to do this conversion in the frontend, and show both links for the user to choose when browsing.

**Comment by JediMaster25** [comment]
I find this really annoying. I already have libredirect configure to redirect me to my favorite instances why would you want to redirect me to one I don't like?

**Comment by testman42** [comment]
few suggestions:
1. Rename issue to "Implement privacy redirect for relevant links"
2. Consider planning this functionality as something that users can opt-in to.
3. Think about how to make new Lemmy instance installation also prompt admin to install [Farside](https://farside.link/) instance as well.
4. Borrow instance-list-refreshing and other logic from [LibRedirect](https://libredirect.github.io/) in order to allow admins to easily configure the redirecting functionality on their Lemmy instances.

Also Farside is basically just one developer. They could use help, so encouraging Lemmy community to go help would probably benefit everyone.

**Comment by 8ullyMaguire** [comment]
This solution is too specific and a more generalized solution should be implemented, allowing system admins to redirect links from any domain to others without forcing all instances to do this. This would provide more flexibility and customization options.

**Comment by dessalines** [comment]
Considering how many of these external service routers have died over time, I think we should let front-ends, and web browser plugins handle link-rewriting, and not do any link-rewriting in the backend.

**Comment by StellarTabi** [comment]
I definitely like this table idea, assuming that

- enabled is a checkbox
- the user can arbitrarily add any domain with any replacement domain.
    - Example: my alternative front-end might not be on the public internet, but I'd like to click a link to it instead of copying a URL and manually replacing the domain in the URL bar with an IP address+port.
- wildcards maybe also IDK
- I suppose this could be done client-side only, but IDK if lemmy's backend supports storing arbitrary settings for the front-end so I could put the settings in on desktop and enjoy them on my phone.

| enabled | domain to replace | new domain          |
|---------|-------------------|---------------------|
| true    | youtube.com       | localhost:20080          |
| false   | twitter.com       | nitter.net          |
| true    | reddit.com        | localhost:33100 |
