### ISSUE TITLE
Split frontend and backend images

### ISSUE THREAD

**Issue by alltheseteeth** [LemmyNet/lemmy#913]
### Is your proposal related to a problem?

There is one immediate problem that this could help with: Currently, frontend developers have to run local copies of everything in order to work on the frontend. Running the UI with yarn and the backend with cargo allows rapid iteration on the frontend, but requires upfront setup on the local system to work. With the current Docker development workflow, any changes to the frontend require an entire rebuild of the backend as well. Vice versa for backend devs as well.

From all accounts, though, it seems like this is a situation where the frontend will iterate much faster than the backend, so being able to split that seems useful.

### Describe the solution you'd like

Ideally, we are able to split the Rust backend and the Typescript frontend into their own Docker instances. On a technical level, this should be relatively easy to accomplish - there are only a few places that reference

Rust currently serves the frontend pages, and any new subpath that is added has to also be added in the backend code. If Typescript were simply self-hosted in something like a node container, or even a static nginx container/bucket storage, then you could potentially drop in your own frontend that you want, and would allow a level of customization far beyond simply themes, and could exist alongside the default interface.

Others have started custom UI projects, such as [lemmy-lite](https://github.com/IronOxidizer/lemmy-lite), and potential future mobile apps. These would simply be talking to the Rust backend anyways, using API calls.

Freeing the frontend from the requirement of being tied to the backend would allow common shared development on the backend, and teams could use the default frontend as a jumping off point for their own UI.

There is, of course, the potential in the future of something happening along the lines of one frontend just becomes overwhelmingly popular, but it conflicts with software methodologies of the core team. If it's split, people then much like Linux distros, will find the flavor that works for them, but maybe the splintering also creates fractured communities. Hopefully, though, as long as under the hood all the instances can talk to one another and federate, this should be a non-issue.

### Describe alternatives you've considered

You could simply run a Lemmy instance as-is with the current frontend, and then develop a completely separate frontend that talks to it. That works, but you have to write a custom frontend to be able to talk to that Lemmy backend, and at that point, it should be its own container/bucket. If the current frontend were its own container, it would be much easier for users to simply spin that out and tweak it to their hearts desire easily.

### Additional context

I'm one of the devops involved with the Chapo Lemmy project. We have cloned the repo and have started making extensive tweaks to the frontend, to the point where it almost doesn't make sense to merge EVERYthing upstream, though many of our changes would absolutely benefit upstream and should be included. We also have made tweaks to the backend, but having to rebuild them together can be strange sometimes, and frontend people having to make changes in Rust to work on their things feels odd.

**Comment by dessalines** [comment]
> Running the UI with yarn and the backend with cargo allows rapid iteration on the frontend, but requires upfront setup on the local system to work. .... With the current Docker development workflow, any changes to the frontend require an entire rebuild of the backend as well. Vice versa for backend devs as well. 

When developing the front end, I just run the docker back-end (and just let the service run in the background), and use `yarn start` @ :4444 to do front end UI additions.  You should **never have to rebuild the back-end** when developing the UI, unless of course you are making API changes.

> Rust currently serves the frontend pages, and any new subpath that is added has to also be added in the backend code. [...] Freeing the frontend from the requirement of being tied to the backend would allow common shared development on the backend, and teams could use the default frontend as a jumping off point for their own UI.

The only references to the lemmy UI in the back-end code, is in `routes/index.rs`, which redirects a few top-level requests to the front end `index.html` (we could also do this in nginx, but it seems more portable to do this in rust, and of course it can always be overridden by nginx). These are entirely optional, and overridable by nginx. Also, if you use the same routes as the current front end, you can also use a customizeable front end dir (shown in `defaults.hjson`), in your `lemmy.hjson`:
```
  # The location of the frontend
  front_end_dir: "../ui/dist"
```

> If Typescript were simply self-hosted in something like a node container, or even a static nginx container/bucket storage, then you could potentially drop in your own frontend that you want, and would allow a level of customization far beyond simply themes, and could exist alongside the default interface.

While I don't plan to split off the UI, its really easy to do for *any* project developing an alternative lemmy UI, that doesn't want to use the existing one, and override those routes. Some suggestions for possibilities on how to do this:

- Create a new front end project / repository. Add any changes you want to it, just like lemmy-lite.
- The back end routes are always available at `/api/v1/...` and `/ws`, these don't change. Make sure your new front end service talks to those ports.
- Create an nginx file that routes exactly how you want it to. For example, the top level `mydomain.com` connects to your front end, and the `/ws` and `/api/v1` routes talk to the lemmy back-end. Check out how [lemmy-lite](https://github.com/IronOxidizer/lemmy-lite/blob/master/lemmy-lite.conf) does this.
- For easy deploy / setup, create a docker compose file that lists:
  - The lemmy back-end (prod docker version), its postgres, iframely, pict-rs, your front end, and possibly an nginx (if you want to do routing in docker)
  - The same nginx file with your front-end routed as above.

> You could simply run a Lemmy instance as-is with the current frontend, and then develop a completely separate frontend that talks to it. That works, but you have to write a custom frontend to be able to talk to that Lemmy backend, and at that point, it should be its own container/bucket.

This is preferrred, lemmy might have dozens of alternative front ends eventually, and its much better to handle these through nginx routing, exactly the way you want, and really only have the back-end routes `ws` and `api/v1` routed.

> We also have made tweaks to the backend, but having to rebuild them together can be strange sometimes, and frontend people having to make changes in Rust to work on their things feels odd.

I spose I really don't understand the problem. Use feature-branches correctly, don't merge them to master until they're complete. It sounds like you're having back-end and front-end development all on the master branch, and running into tons of conflicts / breaks because its wide-open. 

Have front end dev work in its own feature branch where the back-end won't change, and you'll never have to worry about breaks. Or even better, have work done in feature branches, that are tested before they're merged to master.

Having the current lemmy UI be a part of the docker build costs maybe 30 seconds of a build, and is easy to override / ignore with nginx... we could even do this instead of hard-coding those routes in `index.html`.

**Comment by alltheseteeth** [comment]
We're doing all of the things you mentioned as far as working in feature branches and having devs use the `yarn run` to get access to the :4444 local dev instance. We're not running into conflicts/breaks/rebuilds, that's very rare - we ironed out the development pipeline kinks pretty early. We have multiple test environments for multiple branches.

I'm merely trying to piece together a path of least resistance for getting a dev environment going, and having everything possible in Docker. It sounds like the answer is "no, make your own UI" - which, that's fine I suppose.

I'm just thinking in the future (admittedly, probably cart before the horse here) as far as potentialities such as someone wanting to disable the default frontend entirely, and how they'd either just have to not forward the routes and host their own, or make a custom image, but then the default frontend is still available and someone could potentially get access to it? Definitely a very edge case, but regardless, it just feels sort of convoluted.

Maybe I'm simply thinking of this like a traditional web infrastructure, where the backend and frontend are cleanly split and can be iterated on independently - building into a single image isn't inherently bad, it just feels a bit weird to me on the backend side.

Again, that's sort of why I put this as 'feature-request' instead of 'issue'. As the complexity of the project grows, it feels like it might happen organically, but I wanted to put my concern out there.

**Comment by Nutomic** [comment]
We did this.
