### ISSUE TITLE
Diesel feature "64-column-tables" slows down compilation / Remove views

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#920]
I created a new, empty Rust project that depends on nothing but diesel, to determine clearly which features are slowing down our compilation. The result is pretty clear, enabling the "64-column-tables" feature makes the diesel compilation take 95s, compared to 21s without that feature. Other features dont affect the compile time of diesel at all (but slightly affect the overall project compile time).

|  diesel features | project compilation time | diesel compilation time |
|---|---|---|
| ["postgres"] | 31s  |  21s |
|  ["postgres","64-column-tables"] |  1m 44s | 1m 35s  |
|  ["postgres","chrono","r2d2","64-column-tables","serde_json"] |  1m 46s |  1m 35s |
| ["postgres","chrono","r2d2","serde_json"] | 32s | 21s |

[Here is the project I used to test this, so you can easily try for yourself](https://yerbamate.dev/nutomic/diesel-bench).

I know I tested this exact feature before, and concluded that it didnt affect the compile time. But back then I must have had sccache enabled, which makes compilation benchmarks completely useless.

Edit: I tested this on a Ryzen 5 2600. I estimate that removing this feature would reduce Lemmy clean build compile time from currently 3m 40s to 2m 20s. [Also, here is an explicit mention in the diesel source that "enabling 64 column tables or larger will substantially increase the compile time of Diesel."](https://github.com/diesel-rs/diesel/blob/e287e3b9893cf49aac9ade2755294a01fd78db24/diesel/src/macros/mod.rs#L129).

Edit 2: Here is a visualization to show how much Diesel slows down our compilation. The long bar is Diesel, and Lemmy itself cant start compiling until that is finished.
![Screenshot_20200710_233357](https://user-images.githubusercontent.com/1044450/87204886-94f3c080-c2f5-11ea-9aff-47df2d44129a.png)

Edit 3: Now that the 64-column-tables feature is removed, this is what the graph looks like (there were also many other changes since then).
![Screenshot_20210119_181821](https://user-images.githubusercontent.com/1044450/105069879-7166bb00-5a7a-11eb-8877-b1e85a6d15b5.jpg)

**Comment by dessalines** [comment]
I commented this in the chat, but the only way I can think of to remove that feature, is to move the current SQL view queries, to diesel. This is possible, but less than ideal, as now it would require many of our pretty complicated views (lots of joins, unions, etc) to be re-created in diesel. 

I've always preferred doing SQL views, both because it makes all the processing easily shown in SQL, and it doesn't end up tying you to the ORM as much.

**Comment by Nutomic** [comment]
I tried another approach to speed up the compilation, by removing the `chrono` and `serde_json` features from diesel. Without those, it should start the diesel compilation earlier, and in parallel with other dependencies (right now its only building diesel and nothing else for like 70s).

Long story short, without those features Diesel compilation starts at the 50 second mark (compared to 60 seconds before). That means the overall compilation time would decrease from ~3m 40s to ~3m 30s. So not worth the effort to rewrite all of that. Reducing the number of table columns still seems like the only option for significant compilation time improvements.

**Comment by dessalines** [comment]
Its very possible to basically get rid of many of the views, and do the joins in diesel. Also @masterstur suggested that our current views and fast views also have too many columns, that they should really only be used to view the *aggregate data*, things like counts and whatnot, and just join back to the original tables rather than having a ton of columns in the views.

This can be done at any point... my main concern is just learning how to do all this joining in diesel, and making sure its properly type checking to make sure we're getting all the data we need.

**Comment by Nutomic** [comment]
The only table that matters for this issue is `post_aggregates_fast`, which has 37 columns. Everthing else seems under 32. So remove 5 of those and this issue is solved (and Lemmy will compile in half the time).

**Comment by dessalines** [comment]
This is done on the `move_views_to_diesel` branch, this is the performance difference:

```
Old:
Unit	Total	Codegen	Features
diesel v1.4.5	111.4s	1.2s (1%)	32-column-tables, 64-column-tables, bitflags, chrono, default, postgres, pq-sys, r2d2, serde_json, with-deprecated
lemmy_db v0.1.0	40.1s	14.5s (36%)
New:
lemmy_db v0.1.0	63.1s	14.2s (23%)
diesel v1.4.5	40.4s	2.0s (5%)	32-column-tables, bitflags, chrono, default, postgres, pq-sys, r2d2, serde_json, with-deprecated
```

**Comment by tgnottingham** [comment]
You may be interested in rust-lang/rust/issues/81262. If fixed, it should reduce the long compile times incurred by using the `N-column-tables` feature for larger N.
