### ISSUE TITLE
Federation idea

### ISSUE THREAD

**Issue by hialvaro** [LemmyNet/lemmy#951]
### Is your proposal related to a problem?
I was reading on a Lemmy post about federation (https://dev.lemmy.ml/post/31795/comment/3596).

I don't see what is the sense on federating if all communities are completelly separated. Imagine I want to follow the 'Linux' community on lemmy.ml but there are also a lot of good posts on this other instance which I don't even know it exists... Also this could make some people be confused about where to post and this would only beneficiate large instances as people won't follow the small ones as there is no visibility.

### Describe the solution you'd like

What about joining all the communities that share a name, just as if it was one. And let the user select (eg. Via checkboxes) which instances he wants to join (or merge) over that name? So I could join 3 or 4 "Linux" instances and hide the 2 that I don't like or that speak another language.

All the content then shoud be under the name of c/Linux but I would be posting to the join of this communities.

For example, I post to c/Linux@lemmy.ml. That's it, I just post on that instance. But what federation does is propagate that post to all other users that are "following" the c/Linux@lemmy.ml instance so they will also see it. If someone has unchecked that instance the post will not appear to their feed.

I know federation is complicated, but I think this solution would give a lot more sense to the fact of "federation" on a Reddit-like social network as, different from Mastodon where you follow individuals so there's no problem on usernames from other instances being completelly separated, on Lemmy you're following communities which are an agrupation of posts about a topic.

I'll leave here a "concept image" that I made so it may clarify some things.

### Additional context

Going a bit further, you could sort the instances by country, activity, followers... So it would be easier for the user to check the ones he/she wants.

### Concept image:
<img width="350" src="https://i.imgur.com/lYfT8nS.png"></img>

**Comment by dessalines** [comment]
> I don't see what is the sense on federating if all communities are completelly separated. Imagine I want to follow the 'Linux' community on lemmy.ml

You could follow `startrek.lemmy.ml/c/main`, and `startrek.lemmy.ml/c/main` Both communities are called main, yet they have nothing to do with each other. Why would I want to merge them?

Also, lets say two instances have a `/c/linux` community. One might have better moderation than another. Why would I want to merge them? I could subscribe to both, my preferred one, or neither. Its my choice.

> What about joining all the communities that share a name, just as if it was one.

I have no idea how any of this would work with activitypub groups, and I don't see how a single community could be managed by many different servers. Seems less like federation, and more like shared hosting. Ask yourself if it makes sense to merge a single user across multiple mastodon instances, and you'll have the same idea what the issue is.

"Merging communities across instances" is outside of scope here, and I have no idea how it would work for activitypub groups.

The idea of "discovering communities on different instances" is an important one, but a different issue from merging communities (and has its own set of difficulties).
