### ISSUE TITLE
How do you remove yourself as a moderator when you have created a community?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [LemmyNet/lemmy#956]
Not sure how to ask this question, but when you're the creator of a community, how do you remove yourself as a moderator?

**Comment by dessalines** [comment]
We don't have a good way to do this currently, because we don't allow most mod actions to yourself. Plus there's the danger of leaving a community "moderator-less", which is pretty dangerous.

The best way, is to transfer the community to someone else, then have them remove you.

Next best, is to have an admin de-mod you.

**Comment by TheEvilSkeleton** [comment]
> The best way, is to transfer the community to someone else, then have them remove you.

How do you do that? (I'm not a moderator so I can't really guess it)

**Comment by dessalines** [comment]
All mod actions are done on comments. Click the 3 dot expander and mod actions will appear (if you are a mod).

**Comment by TheEvilSkeleton** [comment]
Worked, thank you
