### ISSUE TITLE
Duplicate community names

### ISSUE THREAD

**Issue by elonmusksama** [LemmyNet/lemmy#957]
### Issue Summary

When trying to create a new community, if you name that community the same as an existing community, for example lets say /c/anime, you will be taken to that community and not be able to create it obviously, however, when going to your profile, it will appear as if you are a moderator of that community

### Steps to Reproduce

1. Go to create a community.
2. Name your community something that already exist, for example /c/anime.
3. Click **create**, and it will send you to the existing community.
4. Go to your profile and check **Moderates**.

**Comment by dessalines** [comment]
Yes this is a bug.

We have an issue with duplicate community names, mainly because I can't find a good way to add a SQL constraint on the community table now.

The problem, is that community_activitypub_ids are something like `dev.lemmy.ml/c/my_community`, but the default value on that column right now is `changeme`, and then an advanced code migration sets any one called changeme to fill the rest of the hostname.

But that also means I can't add a uniqueness constraint on that column :( 

The best long term solution is to create a DB migration that : 

- Changes all the `changeme`'s to `changeme_RANDOM_STRING`
- Change the default val on that column to the same `changeme_RANDOM_STRING`
- Add the uniqueness constraint
- Change the API and the advanced code migration to check for the new type, using `like %changme`...

Then we can have proper unique-constraint community `ap_ids` in the DB.

**Comment by dessalines** [comment]
I'll at least do a quick fix to make sure duplicate `ap_id` names aren't possible.

**Comment by eiknat** [comment]
correct me if i'm wrong, but from what i understand a single lemmy instance can have whatever community name they would like, so you'd want uniqueness on the community name and actor_id, which could be represented like this:

```
create unique index community_name_unique_idx on community (lower(name), (lower(actor_id))
```

this should preserve the casing the user defined in the column, while also ensuring uniqueness per actor_id

**Comment by dessalines** [comment]
The `name` one isn't necessary, it'd overlap with `actor_id` anyway.

> the migration should also make sure to rename duplicates if they exist

Here's where it gets difficult, where I have to do some default table name changes. The problem is the `actor_id` needs the hostname to build the full actor_id, which isn't stored in SQL anywhere. So to add the `actor_id` column, I made a default of `changeme` (which obvi couldn't be unique), then I have a code migration to rename that correctly.

In hindsight I should've done some random generator for that column like `changeme_randomstring` and made it unique. 

I still have to do this yet in order to properly fix the problem.

**Comment by eiknat** [comment]
yeah that was in the case a community would ever need to be referenced on a separate instance ^_^ probably overkill, but potential future proofing just in case
