### ISSUE TITLE
Waiving API Rate Limits

### ISSUE THREAD

**Issue by TheCreeper** [LemmyNet/lemmy#961]
It would be useful for instance owners and/or community mods to have the ability to waive or increase rate limits for certain accounts (bots/automated scripts). At the moment, it's only possible to raise those limits globally (for all accounts) which is not desirable. A possible solution might be to execute queries on the database instead of using the API however this would exclude community mods from running their own bots and/or scripts.

Perhaps a new admin/mod action on user posts (similar to remove/ban/appoint/etc...) that would mark the user as not needing to obey API rate limits?

**Comment by dessalines** [comment]
We **really** don't want to allow bots / scripts at all, let alone allow them to override rate limits. What is it you're trying to accomplish with a bot?

IMO, the main reason for bots, was that reddit had no good plugin architecture, and no way of showing that extended functionality to users in an optional, pluggable type way.

This needs to be thought out still for lemmy, possibly by making API endpoints that can batch request data efficiently, and then present it to users in an optional way, probably through user settings, and possibly behind the 3 dot menus on comments / posts. 

Rather than adding bots, it'd be better to build the functionality that a comment bot would do, directly into lemmy.

But really, in lemmy we don't want to allow bots at all (we'll eventually add some captchas, possibly periodic ones to block them out). If they are allowed in some form, they're to be a different identity type than users, and have an extremely restricted set of abilities (no voting, no posting, etc), but I really don't want to do that.

I could see waiving API rate limits maybe for instance admins or something, but that's a separate issue I think.

**Comment by Nutomic** [comment]
I dont think we can prevent bots on Lemmy, especially once we federate with Mastodon and Pleroma, as they have lots of bots already. That said, most bots I see on Mastodon post rather infrequently, so I'm not sure why they would need a higher rate limit.
