### ISSUE TITLE
[Minor UI Tweak] Use consistent syntax for displaying users and communities

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#991]
### Is your proposal related to a problem?

Lemmy currently does a poor job communicating that the proper convention for linking to a community is `!community@instance.tld`. Users often assume that the proper convention is `/c/community`.

![image](https://user-images.githubusercontent.com/46303203/87857034-827b1780-c8f1-11ea-8b54-f114faf2caf6.png)

### Describe the solution you'd like

Simply, wherever a user or community is displayed in the UI, they should be prefixed with a `!` and a `@` respectively.

![image](https://user-images.githubusercontent.com/46303203/87858796-8cefde00-c8fe-11ea-8179-d5de559d0d19.png)

![Screenshot_2020-07-18 Enterprise](https://user-images.githubusercontent.com/46303203/87858130-a4789800-c8f9-11ea-96bf-1d05ffcb574d.png)

The most common argument I see against of this approach concerns aesthetics. In my personal opinion, however, the screenshots above don't look half bad at all. Even if you think that it looks subjectively worse, this does not outweigh the objective benefits that it provides to the user—the added clarity for users.

A common argument I see for using `!` at all to refer to communities is that this syntax is unnatural for users. However, with this tweak, `!` on Lemmy will become as intuitive as `r/` on Reddit or `@` on Mastodon.

### Additional context

Reddit consitently prefixes subreddits with `r/`, and users with `u/` in its UI.
![Screenshot_20200717-193541_Firefox](https://user-images.githubusercontent.com/46303203/87858079-3e8c1080-c8f9-11ea-9723-69cd4c0cd8b2.jpg)

**Comment by dessalines** [comment]
Not a fan of the reddit UI in general, but my fav looking mobile app, boost, does it like this:

![image](https://user-images.githubusercontent.com/930215/87858930-801fba00-c8ff-11ea-83b6-8ade754b20d9.png)

I don't want to use `/u/` or `/c/` in the UI really at all, only for urls. The `@` and `!` aren't too necessary when you have `posted to X by X`, and they're confusing looking at first glance for post-listings.

I also have user names a different font-weight, and communities as the bootstrap primary color, so they're already standing out that way.

**Comment by Datdus** [comment]
Reddit uses these prefixes to enable a user to easily discern if it's a community, a user or a random hyperlink. It's actually really user friendly. 

Like, did archlinux post this to akerro? Archlinux has an avatar and comes first. You can't assume a user knows. 

But I agree that putting ! in front of a community name is just weird. It looks like a templating error or something and @ is used for mentioning a user, so that doesn't really apply either.

Another nitpick. Lemmy's usage of time notation is a weird mix between verbose like reddit and abbreviated. 
![afbeelding](https://user-images.githubusercontent.com/7544047/87859387-099daf00-c935-11ea-99f1-b3349580b470.png)
![afbeelding](https://user-images.githubusercontent.com/7544047/87859471-892b7e00-c935-11ea-822e-c9e36e35e431.png)
a day, what? While reddit writes it out in full. I'd say choose either '3 hours **ago**' or 3hr, 1d, 1m, 2y and use it consistently.

**Comment by kolgza** [comment]
>  The `@` and `!` aren't too necessary when you have `posted to X by X`

It's true that the `@` and `!` would be redundant, but that's the entire point of adding them.

Prefixing communities and users with `@` and `!` would not make it any easier to identifying communities and users. However, by putting `@` and `!` in this context, you are communicating to them the **convention** for referring to users and communities

You would be telling them that typing `!` in a comment/body will return a list of communities to autocomplete to, without having to refer them to the [guide page](https://dev.lemmy.ml/docs/about_guide.html) in the docs.

**Comment by dessalines** [comment]
I agree, its not as clear as what Lemmy is currently doing, which is why I include the by and to: 

![image](https://user-images.githubusercontent.com/930215/87859805-ead3f400-c905-11ea-8596-cd96ea1eaa87.png)

When we add community icons as well, it will stay clear.

> 3hr, 1d, 1m, 2y and use it consistently.

That's an english only shortening, that doesn't exist for most languages, at least with `moment.js`, and we have to import a LOT of time locales. I took off the `ago`, because it overflowed a lot on mobile.

**Comment by kolgza** [comment]
In other words:

- `by user to community` (what Lemmy currently uses) communicates who posted where, but fails to communicate what the correct syntax is.
- ` • @user • !community` (what Reddit uses) makes it somewhat ambiguous at first glance which is the community, and which is the user.
- `by @user to !community` communicates both who posted where, and what the correct syntax is.

**Comment by dessalines** [comment]
I agree. But I far prefer 1 to 3, mainly because I don't see a reason why autocomplete syntax has to exactly match up how things are visually represented on the site.

**Comment by kolgza** [comment]
It's better to teach users the autocomplete syntax without them having to look it up. 3 does this, and 1 does not.

**Comment by Nutomic** [comment]
I agree with this proposal, using `@user` and `!community` everywhere would make things much easier to understand for new users. Federation is already complicated enough, so we shouldnt complicate it more. In fact, @dessalines I dont see any reason why you dislike this proposal, except personal preference.

**Comment by kolgza** [comment]
> I don't want to use `/u/` or `/c/` in the UI really at all, only for urls.

Currently, Lemmy uses this scheme both in the page titles for communities, and in the user pages:

![Screenshot from 2020-07-23 14-52-36](https://user-images.githubusercontent.com/46303203/88326570-31559400-ccf4-11ea-97f4-11c8b01a802a.png)
![image](https://user-images.githubusercontent.com/46303203/88326682-4b8f7200-ccf4-11ea-91e8-e565127385d2.png)

**Comment by dessalines** [comment]
This is done.
