### ISSUE TITLE
Lemmy should retry inbox delivery if it failed

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#998]
There are many reasons why sending an outgoing activity might fail. For example the remote instance might be rebooting, temporarily taken down or otherwise unreachable. So Lemmy should take account of this, by repeating the request until it succeeds. Ideally this would use something like an exponential backoff, and also keep retrying after Lemmy is restarted.

Edit: At the same time, we need to make sure that Lemmy returns correct HTTP status codes for the inbox, so the sending server can tell accurately whether or not an activity was sent successfully. And there might be edge cases where the same activity gets delivered twice to the same server, Lemmy should handle that gracefully.

Edit 2 : We should use a job queue for this, or use an actix actor.

**Comment by dessalines** [comment]
Pinging @asonix as they have some retry logic already in fetcher, maybe it would be possible to add the same to `send_activity`.

**Comment by asonix** [comment]
the fetcher retry logic wouldn't be as useful here. In the event a server is offline (like my masto right now since I'm not quite done moving yet) an immediate retry would  have no effect.

Having some sort of exponential backoff mechanism outside of the normal request/response cycle would be important.

I do have a `background-jobs` library built on top of actix-rt with a basic in-memory job store that could fit this use-case (I'm using it in my relay already)

**Comment by dessalines** [comment]
We're not using any job queue or anything either, `send_activity` is async, but the API is still waiting for results from it (which it doesn't need to). I'm not sure if a job queue is necessary, or how to do an async call but not wait for the result.

If its not possible to just throw off an async call in the background but not wait for the result, then ya that background jobs, or a queue of some kind would be good.

**Comment by asonix** [comment]
you can throw a task into the background (on the current thread) by putting it in `actix_rt::spawn(async move { ... })`

**Comment by Axighi** [comment]
I'll have a try on this one.

**Comment by Nutomic** [comment]
We are using the background-jobs library now so this is fixed.
